// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package engine

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AgentStatusRequest_Status int32

const (
	AgentStatusRequest_ONLINE  AgentStatusRequest_Status = 0
	AgentStatusRequest_OFFLINE AgentStatusRequest_Status = 1
	AgentStatusRequest_PAUSE   AgentStatusRequest_Status = 2
)

var AgentStatusRequest_Status_name = map[int32]string{
	0: "ONLINE",
	1: "OFFLINE",
	2: "PAUSE",
}

var AgentStatusRequest_Status_value = map[string]int32{
	"ONLINE":  0,
	"OFFLINE": 1,
	"PAUSE":   2,
}

func (x AgentStatusRequest_Status) String() string {
	return proto.EnumName(AgentStatusRequest_Status_name, int32(x))
}

func (AgentStatusRequest_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{21, 0}
}

type SearchAgentInQueueStatisticsRequest struct {
	AgentId              int64    `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	DomainId             int64    `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchAgentInQueueStatisticsRequest) Reset()         { *m = SearchAgentInQueueStatisticsRequest{} }
func (m *SearchAgentInQueueStatisticsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchAgentInQueueStatisticsRequest) ProtoMessage()    {}
func (*SearchAgentInQueueStatisticsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *SearchAgentInQueueStatisticsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchAgentInQueueStatisticsRequest.Unmarshal(m, b)
}
func (m *SearchAgentInQueueStatisticsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchAgentInQueueStatisticsRequest.Marshal(b, m, deterministic)
}
func (m *SearchAgentInQueueStatisticsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchAgentInQueueStatisticsRequest.Merge(m, src)
}
func (m *SearchAgentInQueueStatisticsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchAgentInQueueStatisticsRequest.Size(m)
}
func (m *SearchAgentInQueueStatisticsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchAgentInQueueStatisticsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchAgentInQueueStatisticsRequest proto.InternalMessageInfo

func (m *SearchAgentInQueueStatisticsRequest) GetAgentId() int64 {
	if m != nil {
		return m.AgentId
	}
	return 0
}

func (m *SearchAgentInQueueStatisticsRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type AgentInQueueStatistics struct {
	Queue                *Lookup                                              `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Statistics           []*AgentInQueueStatistics_AgentInQueueStatisticsItem `protobuf:"bytes,2,rep,name=statistics,proto3" json:"statistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                             `json:"-"`
	XXX_unrecognized     []byte                                               `json:"-"`
	XXX_sizecache        int32                                                `json:"-"`
}

func (m *AgentInQueueStatistics) Reset()         { *m = AgentInQueueStatistics{} }
func (m *AgentInQueueStatistics) String() string { return proto.CompactTextString(m) }
func (*AgentInQueueStatistics) ProtoMessage()    {}
func (*AgentInQueueStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *AgentInQueueStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInQueueStatistics.Unmarshal(m, b)
}
func (m *AgentInQueueStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInQueueStatistics.Marshal(b, m, deterministic)
}
func (m *AgentInQueueStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInQueueStatistics.Merge(m, src)
}
func (m *AgentInQueueStatistics) XXX_Size() int {
	return xxx_messageInfo_AgentInQueueStatistics.Size(m)
}
func (m *AgentInQueueStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInQueueStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInQueueStatistics proto.InternalMessageInfo

func (m *AgentInQueueStatistics) GetQueue() *Lookup {
	if m != nil {
		return m.Queue
	}
	return nil
}

func (m *AgentInQueueStatistics) GetStatistics() []*AgentInQueueStatistics_AgentInQueueStatisticsItem {
	if m != nil {
		return m.Statistics
	}
	return nil
}

type AgentInQueueStatistics_AgentInQueueStatisticsItem struct {
	Bucket               *Lookup  `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Skill                *Lookup  `protobuf:"bytes,2,opt,name=skill,proto3" json:"skill,omitempty"`
	MemberWaiting        int32    `protobuf:"varint,3,opt,name=member_waiting,json=memberWaiting,proto3" json:"member_waiting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentInQueueStatistics_AgentInQueueStatisticsItem) Reset() {
	*m = AgentInQueueStatistics_AgentInQueueStatisticsItem{}
}
func (m *AgentInQueueStatistics_AgentInQueueStatisticsItem) String() string {
	return proto.CompactTextString(m)
}
func (*AgentInQueueStatistics_AgentInQueueStatisticsItem) ProtoMessage() {}
func (*AgentInQueueStatistics_AgentInQueueStatisticsItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1, 0}
}

func (m *AgentInQueueStatistics_AgentInQueueStatisticsItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInQueueStatistics_AgentInQueueStatisticsItem.Unmarshal(m, b)
}
func (m *AgentInQueueStatistics_AgentInQueueStatisticsItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInQueueStatistics_AgentInQueueStatisticsItem.Marshal(b, m, deterministic)
}
func (m *AgentInQueueStatistics_AgentInQueueStatisticsItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInQueueStatistics_AgentInQueueStatisticsItem.Merge(m, src)
}
func (m *AgentInQueueStatistics_AgentInQueueStatisticsItem) XXX_Size() int {
	return xxx_messageInfo_AgentInQueueStatistics_AgentInQueueStatisticsItem.Size(m)
}
func (m *AgentInQueueStatistics_AgentInQueueStatisticsItem) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInQueueStatistics_AgentInQueueStatisticsItem.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInQueueStatistics_AgentInQueueStatisticsItem proto.InternalMessageInfo

func (m *AgentInQueueStatistics_AgentInQueueStatisticsItem) GetBucket() *Lookup {
	if m != nil {
		return m.Bucket
	}
	return nil
}

func (m *AgentInQueueStatistics_AgentInQueueStatisticsItem) GetSkill() *Lookup {
	if m != nil {
		return m.Skill
	}
	return nil
}

func (m *AgentInQueueStatistics_AgentInQueueStatisticsItem) GetMemberWaiting() int32 {
	if m != nil {
		return m.MemberWaiting
	}
	return 0
}

type AgentInQueueStatisticsList struct {
	Items                []*AgentInQueueStatistics `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *AgentInQueueStatisticsList) Reset()         { *m = AgentInQueueStatisticsList{} }
func (m *AgentInQueueStatisticsList) String() string { return proto.CompactTextString(m) }
func (*AgentInQueueStatisticsList) ProtoMessage()    {}
func (*AgentInQueueStatisticsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *AgentInQueueStatisticsList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInQueueStatisticsList.Unmarshal(m, b)
}
func (m *AgentInQueueStatisticsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInQueueStatisticsList.Marshal(b, m, deterministic)
}
func (m *AgentInQueueStatisticsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInQueueStatisticsList.Merge(m, src)
}
func (m *AgentInQueueStatisticsList) XXX_Size() int {
	return xxx_messageInfo_AgentInQueueStatisticsList.Size(m)
}
func (m *AgentInQueueStatisticsList) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInQueueStatisticsList.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInQueueStatisticsList proto.InternalMessageInfo

func (m *AgentInQueueStatisticsList) GetItems() []*AgentInQueueStatistics {
	if m != nil {
		return m.Items
	}
	return nil
}

type ListAgentUser struct {
	Next                 bool         `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items                []*AgentUser `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListAgentUser) Reset()         { *m = ListAgentUser{} }
func (m *ListAgentUser) String() string { return proto.CompactTextString(m) }
func (*ListAgentUser) ProtoMessage()    {}
func (*ListAgentUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}

func (m *ListAgentUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAgentUser.Unmarshal(m, b)
}
func (m *ListAgentUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAgentUser.Marshal(b, m, deterministic)
}
func (m *ListAgentUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAgentUser.Merge(m, src)
}
func (m *ListAgentUser) XXX_Size() int {
	return xxx_messageInfo_ListAgentUser.Size(m)
}
func (m *ListAgentUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAgentUser.DiscardUnknown(m)
}

var xxx_messageInfo_ListAgentUser proto.InternalMessageInfo

func (m *ListAgentUser) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *ListAgentUser) GetItems() []*AgentUser {
	if m != nil {
		return m.Items
	}
	return nil
}

type AgentUser struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentUser) Reset()         { *m = AgentUser{} }
func (m *AgentUser) String() string { return proto.CompactTextString(m) }
func (*AgentUser) ProtoMessage()    {}
func (*AgentUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4}
}

func (m *AgentUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentUser.Unmarshal(m, b)
}
func (m *AgentUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentUser.Marshal(b, m, deterministic)
}
func (m *AgentUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentUser.Merge(m, src)
}
func (m *AgentUser) XXX_Size() int {
	return xxx_messageInfo_AgentUser.Size(m)
}
func (m *AgentUser) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentUser.DiscardUnknown(m)
}

var xxx_messageInfo_AgentUser proto.InternalMessageInfo

func (m *AgentUser) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AgentUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SearchLookupUsersAgentNotExistsRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Q                    string   `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	DomainId             int64    `protobuf:"varint,4,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchLookupUsersAgentNotExistsRequest) Reset() {
	*m = SearchLookupUsersAgentNotExistsRequest{}
}
func (m *SearchLookupUsersAgentNotExistsRequest) String() string { return proto.CompactTextString(m) }
func (*SearchLookupUsersAgentNotExistsRequest) ProtoMessage()    {}
func (*SearchLookupUsersAgentNotExistsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{5}
}

func (m *SearchLookupUsersAgentNotExistsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchLookupUsersAgentNotExistsRequest.Unmarshal(m, b)
}
func (m *SearchLookupUsersAgentNotExistsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchLookupUsersAgentNotExistsRequest.Marshal(b, m, deterministic)
}
func (m *SearchLookupUsersAgentNotExistsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchLookupUsersAgentNotExistsRequest.Merge(m, src)
}
func (m *SearchLookupUsersAgentNotExistsRequest) XXX_Size() int {
	return xxx_messageInfo_SearchLookupUsersAgentNotExistsRequest.Size(m)
}
func (m *SearchLookupUsersAgentNotExistsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchLookupUsersAgentNotExistsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchLookupUsersAgentNotExistsRequest proto.InternalMessageInfo

func (m *SearchLookupUsersAgentNotExistsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchLookupUsersAgentNotExistsRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchLookupUsersAgentNotExistsRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchLookupUsersAgentNotExistsRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type SearchAgentStateHistoryRequest struct {
	AgentId              int64    `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	TimeFrom             int64    `protobuf:"varint,4,opt,name=time_from,json=timeFrom,proto3" json:"time_from,omitempty"`
	TimeTo               int64    `protobuf:"varint,5,opt,name=time_to,json=timeTo,proto3" json:"time_to,omitempty"`
	Q                    string   `protobuf:"bytes,6,opt,name=q,proto3" json:"q,omitempty"`
	DomainId             int64    `protobuf:"varint,7,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchAgentStateHistoryRequest) Reset()         { *m = SearchAgentStateHistoryRequest{} }
func (m *SearchAgentStateHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*SearchAgentStateHistoryRequest) ProtoMessage()    {}
func (*SearchAgentStateHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{6}
}

func (m *SearchAgentStateHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchAgentStateHistoryRequest.Unmarshal(m, b)
}
func (m *SearchAgentStateHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchAgentStateHistoryRequest.Marshal(b, m, deterministic)
}
func (m *SearchAgentStateHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchAgentStateHistoryRequest.Merge(m, src)
}
func (m *SearchAgentStateHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_SearchAgentStateHistoryRequest.Size(m)
}
func (m *SearchAgentStateHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchAgentStateHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchAgentStateHistoryRequest proto.InternalMessageInfo

func (m *SearchAgentStateHistoryRequest) GetAgentId() int64 {
	if m != nil {
		return m.AgentId
	}
	return 0
}

func (m *SearchAgentStateHistoryRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchAgentStateHistoryRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchAgentStateHistoryRequest) GetTimeFrom() int64 {
	if m != nil {
		return m.TimeFrom
	}
	return 0
}

func (m *SearchAgentStateHistoryRequest) GetTimeTo() int64 {
	if m != nil {
		return m.TimeTo
	}
	return 0
}

func (m *SearchAgentStateHistoryRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchAgentStateHistoryRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type AgentState struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JoinedAt             int64    `protobuf:"varint,2,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	TimeoutAt            int64    `protobuf:"varint,4,opt,name=timeout_at,json=timeoutAt,proto3" json:"timeout_at,omitempty"`
	Queue                *Lookup  `protobuf:"bytes,5,opt,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentState) Reset()         { *m = AgentState{} }
func (m *AgentState) String() string { return proto.CompactTextString(m) }
func (*AgentState) ProtoMessage()    {}
func (*AgentState) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{7}
}

func (m *AgentState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentState.Unmarshal(m, b)
}
func (m *AgentState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentState.Marshal(b, m, deterministic)
}
func (m *AgentState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentState.Merge(m, src)
}
func (m *AgentState) XXX_Size() int {
	return xxx_messageInfo_AgentState.Size(m)
}
func (m *AgentState) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentState.DiscardUnknown(m)
}

var xxx_messageInfo_AgentState proto.InternalMessageInfo

func (m *AgentState) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AgentState) GetJoinedAt() int64 {
	if m != nil {
		return m.JoinedAt
	}
	return 0
}

func (m *AgentState) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AgentState) GetTimeoutAt() int64 {
	if m != nil {
		return m.TimeoutAt
	}
	return 0
}

func (m *AgentState) GetQueue() *Lookup {
	if m != nil {
		return m.Queue
	}
	return nil
}

type ListAgentStateHistory struct {
	Next                 bool          `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items                []*AgentState `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListAgentStateHistory) Reset()         { *m = ListAgentStateHistory{} }
func (m *ListAgentStateHistory) String() string { return proto.CompactTextString(m) }
func (*ListAgentStateHistory) ProtoMessage()    {}
func (*ListAgentStateHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{8}
}

func (m *ListAgentStateHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAgentStateHistory.Unmarshal(m, b)
}
func (m *ListAgentStateHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAgentStateHistory.Marshal(b, m, deterministic)
}
func (m *ListAgentStateHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAgentStateHistory.Merge(m, src)
}
func (m *ListAgentStateHistory) XXX_Size() int {
	return xxx_messageInfo_ListAgentStateHistory.Size(m)
}
func (m *ListAgentStateHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAgentStateHistory.DiscardUnknown(m)
}

var xxx_messageInfo_ListAgentStateHistory proto.InternalMessageInfo

func (m *ListAgentStateHistory) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *ListAgentStateHistory) GetItems() []*AgentState {
	if m != nil {
		return m.Items
	}
	return nil
}

type AgentInQueue struct {
	Queue                *Lookup  `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Priority             int32    `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Strategy             string   `protobuf:"bytes,4,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Enabled              bool     `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CountMember          int32    `protobuf:"varint,6,opt,name=count_member,json=countMember,proto3" json:"count_member,omitempty"`
	WaitingMember        int32    `protobuf:"varint,7,opt,name=waiting_member,json=waitingMember,proto3" json:"waiting_member,omitempty"`
	ActiveMember         int32    `protobuf:"varint,8,opt,name=active_member,json=activeMember,proto3" json:"active_member,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentInQueue) Reset()         { *m = AgentInQueue{} }
func (m *AgentInQueue) String() string { return proto.CompactTextString(m) }
func (*AgentInQueue) ProtoMessage()    {}
func (*AgentInQueue) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{9}
}

func (m *AgentInQueue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInQueue.Unmarshal(m, b)
}
func (m *AgentInQueue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInQueue.Marshal(b, m, deterministic)
}
func (m *AgentInQueue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInQueue.Merge(m, src)
}
func (m *AgentInQueue) XXX_Size() int {
	return xxx_messageInfo_AgentInQueue.Size(m)
}
func (m *AgentInQueue) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInQueue.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInQueue proto.InternalMessageInfo

func (m *AgentInQueue) GetQueue() *Lookup {
	if m != nil {
		return m.Queue
	}
	return nil
}

func (m *AgentInQueue) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *AgentInQueue) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *AgentInQueue) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *AgentInQueue) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *AgentInQueue) GetCountMember() int32 {
	if m != nil {
		return m.CountMember
	}
	return 0
}

func (m *AgentInQueue) GetWaitingMember() int32 {
	if m != nil {
		return m.WaitingMember
	}
	return 0
}

func (m *AgentInQueue) GetActiveMember() int32 {
	if m != nil {
		return m.ActiveMember
	}
	return 0
}

type ListAgentInQueue struct {
	Next                 bool            `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items                []*AgentInQueue `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListAgentInQueue) Reset()         { *m = ListAgentInQueue{} }
func (m *ListAgentInQueue) String() string { return proto.CompactTextString(m) }
func (*ListAgentInQueue) ProtoMessage()    {}
func (*ListAgentInQueue) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{10}
}

func (m *ListAgentInQueue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAgentInQueue.Unmarshal(m, b)
}
func (m *ListAgentInQueue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAgentInQueue.Marshal(b, m, deterministic)
}
func (m *ListAgentInQueue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAgentInQueue.Merge(m, src)
}
func (m *ListAgentInQueue) XXX_Size() int {
	return xxx_messageInfo_ListAgentInQueue.Size(m)
}
func (m *ListAgentInQueue) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAgentInQueue.DiscardUnknown(m)
}

var xxx_messageInfo_ListAgentInQueue proto.InternalMessageInfo

func (m *ListAgentInQueue) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *ListAgentInQueue) GetItems() []*AgentInQueue {
	if m != nil {
		return m.Items
	}
	return nil
}

type SearchAgentInQueueRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Q                    string   `protobuf:"bytes,4,opt,name=q,proto3" json:"q,omitempty"`
	DomainId             int64    `protobuf:"varint,5,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchAgentInQueueRequest) Reset()         { *m = SearchAgentInQueueRequest{} }
func (m *SearchAgentInQueueRequest) String() string { return proto.CompactTextString(m) }
func (*SearchAgentInQueueRequest) ProtoMessage()    {}
func (*SearchAgentInQueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{11}
}

func (m *SearchAgentInQueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchAgentInQueueRequest.Unmarshal(m, b)
}
func (m *SearchAgentInQueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchAgentInQueueRequest.Marshal(b, m, deterministic)
}
func (m *SearchAgentInQueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchAgentInQueueRequest.Merge(m, src)
}
func (m *SearchAgentInQueueRequest) XXX_Size() int {
	return xxx_messageInfo_SearchAgentInQueueRequest.Size(m)
}
func (m *SearchAgentInQueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchAgentInQueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchAgentInQueueRequest proto.InternalMessageInfo

func (m *SearchAgentInQueueRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SearchAgentInQueueRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchAgentInQueueRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchAgentInQueueRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchAgentInQueueRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type SearchAgentInTeamRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Q                    string   `protobuf:"bytes,4,opt,name=q,proto3" json:"q,omitempty"`
	DomainId             int64    `protobuf:"varint,5,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchAgentInTeamRequest) Reset()         { *m = SearchAgentInTeamRequest{} }
func (m *SearchAgentInTeamRequest) String() string { return proto.CompactTextString(m) }
func (*SearchAgentInTeamRequest) ProtoMessage()    {}
func (*SearchAgentInTeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{12}
}

func (m *SearchAgentInTeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchAgentInTeamRequest.Unmarshal(m, b)
}
func (m *SearchAgentInTeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchAgentInTeamRequest.Marshal(b, m, deterministic)
}
func (m *SearchAgentInTeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchAgentInTeamRequest.Merge(m, src)
}
func (m *SearchAgentInTeamRequest) XXX_Size() int {
	return xxx_messageInfo_SearchAgentInTeamRequest.Size(m)
}
func (m *SearchAgentInTeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchAgentInTeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchAgentInTeamRequest proto.InternalMessageInfo

func (m *SearchAgentInTeamRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SearchAgentInTeamRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchAgentInTeamRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchAgentInTeamRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchAgentInTeamRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type AgentInTeam struct {
	Team                 *Lookup  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	Strategy             string   `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentInTeam) Reset()         { *m = AgentInTeam{} }
func (m *AgentInTeam) String() string { return proto.CompactTextString(m) }
func (*AgentInTeam) ProtoMessage()    {}
func (*AgentInTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{13}
}

func (m *AgentInTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInTeam.Unmarshal(m, b)
}
func (m *AgentInTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInTeam.Marshal(b, m, deterministic)
}
func (m *AgentInTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInTeam.Merge(m, src)
}
func (m *AgentInTeam) XXX_Size() int {
	return xxx_messageInfo_AgentInTeam.Size(m)
}
func (m *AgentInTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInTeam.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInTeam proto.InternalMessageInfo

func (m *AgentInTeam) GetTeam() *Lookup {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *AgentInTeam) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

type ListAgentInTeam struct {
	Next                 bool           `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items                []*AgentInTeam `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListAgentInTeam) Reset()         { *m = ListAgentInTeam{} }
func (m *ListAgentInTeam) String() string { return proto.CompactTextString(m) }
func (*ListAgentInTeam) ProtoMessage()    {}
func (*ListAgentInTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{14}
}

func (m *ListAgentInTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAgentInTeam.Unmarshal(m, b)
}
func (m *ListAgentInTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAgentInTeam.Marshal(b, m, deterministic)
}
func (m *ListAgentInTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAgentInTeam.Merge(m, src)
}
func (m *ListAgentInTeam) XXX_Size() int {
	return xxx_messageInfo_ListAgentInTeam.Size(m)
}
func (m *ListAgentInTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAgentInTeam.DiscardUnknown(m)
}

var xxx_messageInfo_ListAgentInTeam proto.InternalMessageInfo

func (m *ListAgentInTeam) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *ListAgentInTeam) GetItems() []*AgentInTeam {
	if m != nil {
		return m.Items
	}
	return nil
}

type UpdateAgentRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *Lookup  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ProgressiveCount     int32    `protobuf:"varint,4,opt,name=progressive_count,json=progressiveCount,proto3" json:"progressive_count,omitempty"`
	DomainId             int64    `protobuf:"varint,5,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAgentRequest) Reset()         { *m = UpdateAgentRequest{} }
func (m *UpdateAgentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAgentRequest) ProtoMessage()    {}
func (*UpdateAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{15}
}

func (m *UpdateAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAgentRequest.Unmarshal(m, b)
}
func (m *UpdateAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAgentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAgentRequest.Merge(m, src)
}
func (m *UpdateAgentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAgentRequest.Size(m)
}
func (m *UpdateAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAgentRequest proto.InternalMessageInfo

func (m *UpdateAgentRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateAgentRequest) GetUser() *Lookup {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateAgentRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateAgentRequest) GetProgressiveCount() int32 {
	if m != nil {
		return m.ProgressiveCount
	}
	return 0
}

func (m *UpdateAgentRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type ReadAgentRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId             int64    `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAgentRequest) Reset()         { *m = ReadAgentRequest{} }
func (m *ReadAgentRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAgentRequest) ProtoMessage()    {}
func (*ReadAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{16}
}

func (m *ReadAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAgentRequest.Unmarshal(m, b)
}
func (m *ReadAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAgentRequest.Marshal(b, m, deterministic)
}
func (m *ReadAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAgentRequest.Merge(m, src)
}
func (m *ReadAgentRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAgentRequest.Size(m)
}
func (m *ReadAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAgentRequest proto.InternalMessageInfo

func (m *ReadAgentRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReadAgentRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type DeleteAgentRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId             int64    `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAgentRequest) Reset()         { *m = DeleteAgentRequest{} }
func (m *DeleteAgentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAgentRequest) ProtoMessage()    {}
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{17}
}

func (m *DeleteAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAgentRequest.Unmarshal(m, b)
}
func (m *DeleteAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAgentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAgentRequest.Merge(m, src)
}
func (m *DeleteAgentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAgentRequest.Size(m)
}
func (m *DeleteAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAgentRequest proto.InternalMessageInfo

func (m *DeleteAgentRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteAgentRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type SearchAgentRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Q                    string   `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	DomainId             int64    `protobuf:"varint,4,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Fields               []string `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	Sort                 string   `protobuf:"bytes,6,opt,name=sort,proto3" json:"sort,omitempty"`
	Id                   []string `protobuf:"bytes,7,rep,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchAgentRequest) Reset()         { *m = SearchAgentRequest{} }
func (m *SearchAgentRequest) String() string { return proto.CompactTextString(m) }
func (*SearchAgentRequest) ProtoMessage()    {}
func (*SearchAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{18}
}

func (m *SearchAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchAgentRequest.Unmarshal(m, b)
}
func (m *SearchAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchAgentRequest.Marshal(b, m, deterministic)
}
func (m *SearchAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchAgentRequest.Merge(m, src)
}
func (m *SearchAgentRequest) XXX_Size() int {
	return xxx_messageInfo_SearchAgentRequest.Size(m)
}
func (m *SearchAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchAgentRequest proto.InternalMessageInfo

func (m *SearchAgentRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchAgentRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchAgentRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchAgentRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

func (m *SearchAgentRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *SearchAgentRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *SearchAgentRequest) GetId() []string {
	if m != nil {
		return m.Id
	}
	return nil
}

type CreateAgentRequest struct {
	User                 *Lookup  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ProgressiveCount     int32    `protobuf:"varint,3,opt,name=progressive_count,json=progressiveCount,proto3" json:"progressive_count,omitempty"`
	DomainId             int64    `protobuf:"varint,4,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAgentRequest) Reset()         { *m = CreateAgentRequest{} }
func (m *CreateAgentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAgentRequest) ProtoMessage()    {}
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{19}
}

func (m *CreateAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAgentRequest.Unmarshal(m, b)
}
func (m *CreateAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAgentRequest.Marshal(b, m, deterministic)
}
func (m *CreateAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAgentRequest.Merge(m, src)
}
func (m *CreateAgentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAgentRequest.Size(m)
}
func (m *CreateAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAgentRequest proto.InternalMessageInfo

func (m *CreateAgentRequest) GetUser() *Lookup {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateAgentRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateAgentRequest) GetProgressiveCount() int32 {
	if m != nil {
		return m.ProgressiveCount
	}
	return 0
}

func (m *CreateAgentRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type SkillAgent struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Skill                *Lookup  `protobuf:"bytes,2,opt,name=skill,proto3" json:"skill,omitempty"`
	Agent                *Lookup  `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	Capacity             int32    `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillAgent) Reset()         { *m = SkillAgent{} }
func (m *SkillAgent) String() string { return proto.CompactTextString(m) }
func (*SkillAgent) ProtoMessage()    {}
func (*SkillAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{20}
}

func (m *SkillAgent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillAgent.Unmarshal(m, b)
}
func (m *SkillAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillAgent.Marshal(b, m, deterministic)
}
func (m *SkillAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillAgent.Merge(m, src)
}
func (m *SkillAgent) XXX_Size() int {
	return xxx_messageInfo_SkillAgent.Size(m)
}
func (m *SkillAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillAgent.DiscardUnknown(m)
}

var xxx_messageInfo_SkillAgent proto.InternalMessageInfo

func (m *SkillAgent) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SkillAgent) GetSkill() *Lookup {
	if m != nil {
		return m.Skill
	}
	return nil
}

func (m *SkillAgent) GetAgent() *Lookup {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *SkillAgent) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type AgentStatusRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OnDemand             bool     `protobuf:"varint,3,opt,name=on_demand,json=onDemand,proto3" json:"on_demand,omitempty"`
	DomainId             int64    `protobuf:"varint,4,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentStatusRequest) Reset()         { *m = AgentStatusRequest{} }
func (m *AgentStatusRequest) String() string { return proto.CompactTextString(m) }
func (*AgentStatusRequest) ProtoMessage()    {}
func (*AgentStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{21}
}

func (m *AgentStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentStatusRequest.Unmarshal(m, b)
}
func (m *AgentStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentStatusRequest.Marshal(b, m, deterministic)
}
func (m *AgentStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentStatusRequest.Merge(m, src)
}
func (m *AgentStatusRequest) XXX_Size() int {
	return xxx_messageInfo_AgentStatusRequest.Size(m)
}
func (m *AgentStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentStatusRequest proto.InternalMessageInfo

func (m *AgentStatusRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AgentStatusRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AgentStatusRequest) GetOnDemand() bool {
	if m != nil {
		return m.OnDemand
	}
	return false
}

func (m *AgentStatusRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type AgentChannel struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	JoinedAt             int64    `protobuf:"varint,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	Online               bool     `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentChannel) Reset()         { *m = AgentChannel{} }
func (m *AgentChannel) String() string { return proto.CompactTextString(m) }
func (*AgentChannel) ProtoMessage()    {}
func (*AgentChannel) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{22}
}

func (m *AgentChannel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentChannel.Unmarshal(m, b)
}
func (m *AgentChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentChannel.Marshal(b, m, deterministic)
}
func (m *AgentChannel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentChannel.Merge(m, src)
}
func (m *AgentChannel) XXX_Size() int {
	return xxx_messageInfo_AgentChannel.Size(m)
}
func (m *AgentChannel) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentChannel.DiscardUnknown(m)
}

var xxx_messageInfo_AgentChannel proto.InternalMessageInfo

func (m *AgentChannel) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *AgentChannel) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AgentChannel) GetJoinedAt() int64 {
	if m != nil {
		return m.JoinedAt
	}
	return 0
}

func (m *AgentChannel) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

type Agent struct {
	Id                   int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *Lookup         `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Status               string          `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Description          string          `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	LastStatusChange     int64           `protobuf:"varint,5,opt,name=last_status_change,json=lastStatusChange,proto3" json:"last_status_change,omitempty"`
	ProgressiveCount     int32           `protobuf:"varint,6,opt,name=progressive_count,json=progressiveCount,proto3" json:"progressive_count,omitempty"`
	Name                 string          `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Channels             []*AgentChannel `protobuf:"bytes,8,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{23}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Agent) GetUser() *Lookup {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Agent) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Agent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Agent) GetLastStatusChange() int64 {
	if m != nil {
		return m.LastStatusChange
	}
	return 0
}

func (m *Agent) GetProgressiveCount() int32 {
	if m != nil {
		return m.ProgressiveCount
	}
	return 0
}

func (m *Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Agent) GetChannels() []*AgentChannel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type ListAgent struct {
	Next                 bool     `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items                []*Agent `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAgent) Reset()         { *m = ListAgent{} }
func (m *ListAgent) String() string { return proto.CompactTextString(m) }
func (*ListAgent) ProtoMessage()    {}
func (*ListAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{24}
}

func (m *ListAgent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAgent.Unmarshal(m, b)
}
func (m *ListAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAgent.Marshal(b, m, deterministic)
}
func (m *ListAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAgent.Merge(m, src)
}
func (m *ListAgent) XXX_Size() int {
	return xxx_messageInfo_ListAgent.Size(m)
}
func (m *ListAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAgent.DiscardUnknown(m)
}

var xxx_messageInfo_ListAgent proto.InternalMessageInfo

func (m *ListAgent) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *ListAgent) GetItems() []*Agent {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterEnum("engine.AgentStatusRequest_Status", AgentStatusRequest_Status_name, AgentStatusRequest_Status_value)
	proto.RegisterType((*SearchAgentInQueueStatisticsRequest)(nil), "engine.SearchAgentInQueueStatisticsRequest")
	proto.RegisterType((*AgentInQueueStatistics)(nil), "engine.AgentInQueueStatistics")
	proto.RegisterType((*AgentInQueueStatistics_AgentInQueueStatisticsItem)(nil), "engine.AgentInQueueStatistics.AgentInQueueStatisticsItem")
	proto.RegisterType((*AgentInQueueStatisticsList)(nil), "engine.AgentInQueueStatisticsList")
	proto.RegisterType((*ListAgentUser)(nil), "engine.ListAgentUser")
	proto.RegisterType((*AgentUser)(nil), "engine.AgentUser")
	proto.RegisterType((*SearchLookupUsersAgentNotExistsRequest)(nil), "engine.SearchLookupUsersAgentNotExistsRequest")
	proto.RegisterType((*SearchAgentStateHistoryRequest)(nil), "engine.SearchAgentStateHistoryRequest")
	proto.RegisterType((*AgentState)(nil), "engine.AgentState")
	proto.RegisterType((*ListAgentStateHistory)(nil), "engine.ListAgentStateHistory")
	proto.RegisterType((*AgentInQueue)(nil), "engine.AgentInQueue")
	proto.RegisterType((*ListAgentInQueue)(nil), "engine.ListAgentInQueue")
	proto.RegisterType((*SearchAgentInQueueRequest)(nil), "engine.SearchAgentInQueueRequest")
	proto.RegisterType((*SearchAgentInTeamRequest)(nil), "engine.SearchAgentInTeamRequest")
	proto.RegisterType((*AgentInTeam)(nil), "engine.AgentInTeam")
	proto.RegisterType((*ListAgentInTeam)(nil), "engine.ListAgentInTeam")
	proto.RegisterType((*UpdateAgentRequest)(nil), "engine.UpdateAgentRequest")
	proto.RegisterType((*ReadAgentRequest)(nil), "engine.ReadAgentRequest")
	proto.RegisterType((*DeleteAgentRequest)(nil), "engine.DeleteAgentRequest")
	proto.RegisterType((*SearchAgentRequest)(nil), "engine.SearchAgentRequest")
	proto.RegisterType((*CreateAgentRequest)(nil), "engine.CreateAgentRequest")
	proto.RegisterType((*SkillAgent)(nil), "engine.SkillAgent")
	proto.RegisterType((*AgentStatusRequest)(nil), "engine.AgentStatusRequest")
	proto.RegisterType((*AgentChannel)(nil), "engine.AgentChannel")
	proto.RegisterType((*Agent)(nil), "engine.Agent")
	proto.RegisterType((*ListAgent)(nil), "engine.ListAgent")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 1495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xdd, 0x72, 0xdb, 0xc4,
	0x17, 0xff, 0x4b, 0x8e, 0xfc, 0x71, 0x9c, 0xf4, 0xef, 0x6c, 0xdb, 0xd4, 0x55, 0xda, 0xd4, 0x51,
	0x4a, 0x9a, 0xa6, 0x25, 0xee, 0x04, 0x98, 0x01, 0x6e, 0x98, 0x4c, 0xda, 0x0e, 0x99, 0x49, 0x3f,
	0x50, 0x1a, 0xa0, 0xcc, 0x74, 0x3c, 0x8a, 0xb5, 0x75, 0x45, 0x6d, 0xad, 0xa3, 0x5d, 0x97, 0xa6,
	0x9d, 0x72, 0xc1, 0x70, 0xc3, 0x25, 0x53, 0x3e, 0x1e, 0x00, 0x6e, 0xb8, 0xe0, 0x8e, 0x47, 0xe0,
	0x0d, 0x78, 0x05, 0x1e, 0x84, 0xd9, 0xb3, 0x92, 0x2c, 0x59, 0x92, 0xeb, 0x1b, 0xb8, 0xd3, 0x9e,
	0x3d, 0x7b, 0xf6, 0xb7, 0xbf, 0xf3, 0xb5, 0x2b, 0xa8, 0x3b, 0x3d, 0xea, 0x8b, 0xad, 0x61, 0xc0,
	0x04, 0x23, 0x65, 0xea, 0xf7, 0x3c, 0x9f, 0x9a, 0xf5, 0x2e, 0xf3, 0x79, 0x28, 0x34, 0x2f, 0xf4,
	0x18, 0xeb, 0xf5, 0x69, 0xdb, 0x19, 0x7a, 0x6d, 0xc7, 0xf7, 0x99, 0x70, 0x84, 0xc7, 0x7c, 0xae,
	0x66, 0xad, 0x47, 0xb0, 0x76, 0x40, 0x9d, 0xa0, 0xfb, 0x64, 0x47, 0xda, 0xd9, 0xf3, 0x3f, 0x19,
	0xd1, 0x11, 0x3d, 0x90, 0x3a, 0x5c, 0x78, 0x5d, 0x6e, 0xd3, 0xe3, 0x11, 0xe5, 0x82, 0x9c, 0x87,
	0x2a, 0x6e, 0xd4, 0xf1, 0xdc, 0xa6, 0xd6, 0xd2, 0x36, 0x4a, 0x76, 0x05, 0xc7, 0x7b, 0x2e, 0x59,
	0x86, 0x9a, 0xcb, 0x06, 0x8e, 0xe7, 0xcb, 0x39, 0x1d, 0xe7, 0xaa, 0x4a, 0xb0, 0xe7, 0x5a, 0xbf,
	0xeb, 0xb0, 0x94, 0x6f, 0x99, 0x5c, 0x06, 0xe3, 0x58, 0x8a, 0xd0, 0x5e, 0x7d, 0xfb, 0xd4, 0x96,
	0x02, 0xbf, 0xb5, 0xcf, 0xd8, 0xd3, 0xd1, 0xd0, 0x56, 0x93, 0xe4, 0x21, 0x00, 0x8f, 0xd7, 0x34,
	0xf5, 0x56, 0x69, 0xa3, 0xbe, 0xfd, 0x41, 0xa4, 0x9a, 0x6f, 0xb9, 0x40, 0xbc, 0x27, 0xe8, 0xc0,
	0x4e, 0x18, 0x33, 0xbf, 0xd7, 0xc0, 0x2c, 0x56, 0x25, 0xeb, 0x50, 0x3e, 0x1a, 0x75, 0x9f, 0x52,
	0x51, 0x00, 0x30, 0x9c, 0x95, 0xe7, 0xe0, 0x4f, 0xbd, 0x7e, 0x1f, 0xcf, 0x9e, 0x73, 0x0e, 0x9c,
	0x24, 0x6f, 0xc1, 0xa9, 0x01, 0x1d, 0x1c, 0xd1, 0xa0, 0xf3, 0x95, 0xe3, 0x09, 0xcf, 0xef, 0x35,
	0x4b, 0x2d, 0x6d, 0xc3, 0xb0, 0x17, 0x94, 0xf4, 0x33, 0x25, 0xb4, 0xec, 0x22, 0x48, 0xfb, 0x1e,
	0x17, 0xe4, 0x5d, 0x30, 0x3c, 0x41, 0x07, 0xbc, 0xa9, 0x21, 0x0f, 0x2b, 0xd3, 0x79, 0xb0, 0x95,
	0xb2, 0xb5, 0x0f, 0x0b, 0x72, 0x35, 0x2a, 0x1d, 0x72, 0x1a, 0x10, 0x02, 0x73, 0x3e, 0x7d, 0xae,
	0xce, 0x55, 0xb5, 0xf1, 0x9b, 0x5c, 0x89, 0x4c, 0x2b, 0x8a, 0x17, 0x53, 0xa6, 0xe5, 0xaa, 0xc8,
	0x5a, 0x1b, 0x6a, 0x63, 0x4b, 0xa7, 0x40, 0x8f, 0x03, 0x42, 0xf7, 0x5c, 0xb4, 0xec, 0x0c, 0x28,
	0x52, 0x51, 0xb3, 0xf1, 0xdb, 0x7a, 0x09, 0xeb, 0x2a, 0xc2, 0x14, 0x21, 0x72, 0x1d, 0x47, 0x0b,
	0x77, 0x99, 0xb8, 0xf5, 0xdc, 0xe3, 0x22, 0x0e, 0x32, 0x02, 0x73, 0x43, 0xa7, 0xa7, 0x02, 0xc2,
	0xb0, 0xf1, 0x5b, 0xca, 0xb8, 0xf7, 0x42, 0x59, 0x34, 0x6c, 0xfc, 0x26, 0xf3, 0xa0, 0x1d, 0x23,
	0x7d, 0x35, 0x5b, 0x3b, 0x4e, 0xc7, 0xdf, 0xdc, 0x44, 0xfc, 0xfd, 0xa9, 0xc1, 0x4a, 0x22, 0xbe,
	0x25, 0x39, 0xf4, 0x63, 0x8f, 0x0b, 0x16, 0x9c, 0xcc, 0x10, 0xda, 0x11, 0x20, 0x3d, 0x07, 0x50,
	0x29, 0x01, 0x68, 0x19, 0x6a, 0xc2, 0x1b, 0xd0, 0xce, 0xe3, 0x80, 0x0d, 0x22, 0x08, 0x52, 0x70,
	0x3b, 0x60, 0x03, 0x72, 0x0e, 0x2a, 0x38, 0x29, 0x58, 0xd3, 0xc0, 0xa9, 0xb2, 0x1c, 0x3e, 0x60,
	0xea, 0x18, 0xe5, 0xdc, 0x63, 0x54, 0x26, 0x8e, 0xf1, 0x83, 0x06, 0x30, 0x3e, 0x40, 0x86, 0xf6,
	0x65, 0xa8, 0x7d, 0xc9, 0x3c, 0x9f, 0xba, 0x1d, 0x47, 0x44, 0x29, 0xa8, 0x04, 0x3b, 0x82, 0x9c,
	0x01, 0x43, 0x06, 0x3d, 0x0d, 0x19, 0x53, 0x03, 0x72, 0x11, 0x40, 0xc2, 0x60, 0x23, 0x21, 0xd7,
	0x28, 0xcc, 0xb5, 0x50, 0xb2, 0x23, 0xc6, 0xc9, 0x69, 0x4c, 0x49, 0x4e, 0xeb, 0x10, 0xce, 0xc6,
	0x91, 0x95, 0xa4, 0x36, 0x37, 0xc2, 0x36, 0xd2, 0x11, 0x46, 0x52, 0x11, 0x86, 0xab, 0xa3, 0x10,
	0xfb, 0x4e, 0x87, 0xf9, 0x64, 0x48, 0xcf, 0x58, 0x2a, 0x4c, 0xa8, 0x0e, 0x03, 0x8f, 0x05, 0x9e,
	0x38, 0x09, 0x3d, 0x16, 0x8f, 0x25, 0x20, 0x71, 0x32, 0x8c, 0xbd, 0x26, 0xbf, 0xa5, 0x3e, 0x17,
	0x81, 0x23, 0x68, 0xef, 0x04, 0x09, 0xa8, 0xd9, 0xf1, 0x98, 0x34, 0xa1, 0x42, 0x7d, 0xe7, 0xa8,
	0x4f, 0x5d, 0x64, 0xa0, 0x6a, 0x47, 0x43, 0xb2, 0x0a, 0xf3, 0x5d, 0x36, 0xf2, 0x45, 0x47, 0x25,
	0x2e, 0x3a, 0xd0, 0xb0, 0xeb, 0x28, 0xbb, 0x83, 0x22, 0x99, 0xeb, 0x61, 0x92, 0x47, 0x4a, 0x15,
	0x95, 0xeb, 0xa1, 0x34, 0x54, 0x5b, 0x83, 0x05, 0xa7, 0x2b, 0xbc, 0x67, 0x34, 0xd2, 0xaa, 0xa2,
	0xd6, 0xbc, 0x12, 0x2a, 0x25, 0xcb, 0x86, 0x46, 0x4c, 0x71, 0x44, 0x47, 0x1e, 0xbb, 0x9b, 0x69,
	0x76, 0xcf, 0xe4, 0x95, 0x86, 0x88, 0xdf, 0xaf, 0xe1, 0x7c, 0xb6, 0xe6, 0x47, 0xe9, 0x90, 0x93,
	0xd2, 0x33, 0xe5, 0x00, 0x46, 0xf3, 0x5c, 0x6e, 0x34, 0x1b, 0x13, 0xd1, 0xfc, 0x0a, 0x9a, 0xa9,
	0xfd, 0x1f, 0x50, 0x67, 0xf0, 0x1f, 0x6e, 0x7f, 0x07, 0xea, 0x89, 0x8d, 0x89, 0x05, 0x73, 0x82,
	0x3a, 0x83, 0x82, 0xd8, 0xc2, 0xb9, 0x54, 0xa8, 0xe8, 0xe9, 0x50, 0xb1, 0xee, 0xc3, 0xff, 0x13,
	0x1e, 0x42, 0x93, 0x79, 0x0e, 0xba, 0x9a, 0x76, 0xd0, 0xe9, 0x09, 0x07, 0x21, 0x07, 0xa1, 0x7f,
	0xfe, 0xd0, 0x80, 0x1c, 0x0e, 0x5d, 0x47, 0x50, 0x9c, 0x2c, 0xa2, 0xc6, 0x82, 0xb9, 0x11, 0xa7,
	0x41, 0x41, 0xdf, 0xc1, 0x39, 0xd2, 0x82, 0xba, 0x4b, 0x79, 0x37, 0xf0, 0x86, 0xb2, 0xe9, 0x87,
	0x25, 0x20, 0x29, 0x22, 0xd7, 0x60, 0x71, 0x18, 0xb0, 0x5e, 0x40, 0x39, 0x97, 0xa1, 0x88, 0x71,
	0x8c, 0x44, 0x1a, 0x76, 0x23, 0x31, 0xb1, 0x2b, 0xe5, 0xd3, 0x79, 0xfd, 0x08, 0x1a, 0x36, 0x75,
	0xdc, 0xa9, 0x98, 0xa7, 0x5e, 0x16, 0x76, 0x80, 0xdc, 0xa4, 0x7d, 0xfa, 0x86, 0x63, 0x4f, 0x35,
	0xf1, 0x8b, 0x06, 0x24, 0x11, 0x5b, 0xff, 0x5e, 0x67, 0x21, 0x4b, 0x50, 0x7e, 0xec, 0xd1, 0xbe,
	0xcb, 0x9b, 0x46, 0xab, 0xb4, 0x51, 0xb3, 0xc3, 0x11, 0x9a, 0x65, 0x81, 0x08, 0x0b, 0x3b, 0x7e,
	0x87, 0x47, 0xa8, 0xa0, 0x9e, 0xee, 0xb9, 0xd6, 0xaf, 0x1a, 0x90, 0xdd, 0x80, 0x4e, 0x3a, 0x38,
	0x72, 0xa8, 0x36, 0xbb, 0x43, 0xf5, 0x19, 0x1d, 0x5a, 0x9a, 0xc5, 0xa1, 0x93, 0xcd, 0xf3, 0x5b,
	0x0d, 0xe0, 0x40, 0xde, 0x5e, 0x10, 0x65, 0xc6, 0x11, 0xb3, 0x5d, 0x7c, 0x2e, 0x83, 0x81, 0xed,
	0x14, 0x21, 0xe4, 0x68, 0xe1, 0xa4, 0x4c, 0xb0, 0xae, 0x33, 0x74, 0xba, 0xb2, 0x76, 0xab, 0xe0,
	0x8b, 0xc7, 0xc8, 0x56, 0xdc, 0x24, 0x46, 0xbc, 0x28, 0x2e, 0x96, 0xa0, 0xcc, 0x51, 0x21, 0x24,
	0x25, 0x1c, 0xc9, 0x23, 0x32, 0xbf, 0xe3, 0xd2, 0x81, 0xe3, 0xbb, 0x08, 0xa2, 0x6a, 0x57, 0x99,
	0x7f, 0x13, 0xc7, 0xd3, 0xcf, 0x7f, 0x1d, 0xca, 0x6a, 0x4b, 0x02, 0x50, 0xbe, 0x77, 0x77, 0x7f,
	0xef, 0xee, 0xad, 0xc6, 0xff, 0x48, 0x1d, 0x2a, 0xf7, 0x6e, 0xdf, 0xc6, 0x81, 0x46, 0x6a, 0x60,
	0xdc, 0xdf, 0x39, 0x3c, 0xb8, 0xd5, 0xd0, 0x2d, 0x1e, 0x36, 0xad, 0xdd, 0x27, 0x8e, 0xef, 0xd3,
	0xbe, 0x6c, 0x21, 0x5d, 0xf5, 0x89, 0x20, 0x6b, 0x76, 0x34, 0x1c, 0x77, 0x64, 0x3d, 0xd9, 0x91,
	0x53, 0x4d, 0xbc, 0x34, 0xd1, 0xc4, 0x97, 0xa0, 0xcc, 0xfc, 0xbe, 0xe7, 0x53, 0x04, 0x59, 0xb5,
	0xc3, 0x91, 0xf5, 0x93, 0x0e, 0x46, 0xbe, 0x77, 0x66, 0xa9, 0x0e, 0x63, 0xca, 0x4a, 0x29, 0xca,
	0x26, 0x82, 0x6c, 0x2e, 0x1b, 0x64, 0xd7, 0x81, 0xf4, 0x1d, 0x2e, 0x3a, 0x6a, 0x41, 0x47, 0x9e,
	0xac, 0x47, 0xc3, 0x8a, 0xd0, 0x90, 0x33, 0x8a, 0xb8, 0x5d, 0x94, 0xe7, 0x87, 0x64, 0xb9, 0x20,
	0x24, 0xa3, 0x3b, 0x64, 0x65, 0x7c, 0x87, 0x24, 0x37, 0xa0, 0x1a, 0x92, 0xc7, 0x9b, 0xd5, 0x9c,
	0x06, 0x17, 0x72, 0x6e, 0xc7, 0x5a, 0xd6, 0x4d, 0xa8, 0xc5, 0x55, 0x39, 0xb7, 0x1e, 0xaf, 0xa5,
	0xeb, 0xf1, 0x42, 0xca, 0x5e, 0x58, 0x89, 0xb7, 0x7f, 0x84, 0xd0, 0xa9, 0x07, 0x34, 0x78, 0xe6,
	0x75, 0x29, 0xf9, 0x1c, 0xea, 0x89, 0xc4, 0x25, 0x66, 0xb4, 0x2a, 0x9b, 0xcd, 0x66, 0xda, 0xa2,
	0xb5, 0xf2, 0xcd, 0x5f, 0x7f, 0xbf, 0xd6, 0x9b, 0xd6, 0xe9, 0x76, 0xd7, 0xe9, 0xf7, 0x3b, 0x5d,
	0xea, 0x0b, 0x1a, 0xb4, 0x31, 0xfa, 0xf9, 0x87, 0xda, 0x26, 0x79, 0x08, 0xf5, 0x44, 0xe1, 0x1a,
	0x5b, 0xce, 0x56, 0x33, 0x33, 0xbe, 0x9c, 0xc7, 0x27, 0xb4, 0x96, 0xd1, 0xfa, 0x59, 0x92, 0x67,
	0x9d, 0x7c, 0x0a, 0xb5, 0xb8, 0x30, 0x93, 0x66, 0xb4, 0x78, 0xb2, 0x56, 0x4f, 0x02, 0x6e, 0xa1,
	0x49, 0x93, 0x34, 0x73, 0x4c, 0xb6, 0x5f, 0x7a, 0xee, 0x2b, 0xf2, 0x08, 0xea, 0x89, 0x36, 0x35,
	0x86, 0x9c, 0xed, 0x5d, 0x93, 0xb6, 0xd7, 0xd0, 0xf6, 0x45, 0xb3, 0xd0, 0xb6, 0x64, 0xe4, 0x0b,
	0xa8, 0x27, 0xda, 0xc1, 0xd8, 0x7c, 0xb6, 0x47, 0x14, 0x40, 0xdf, 0x2c, 0x86, 0x3e, 0x80, 0xc5,
	0x04, 0xca, 0x30, 0xcb, 0xcd, 0xcc, 0x95, 0x34, 0xae, 0x36, 0x66, 0x63, 0x4c, 0x1b, 0x1f, 0x32,
	0x9f, 0x53, 0x6b, 0x13, 0x37, 0xb9, 0xbc, 0x7d, 0xa9, 0x68, 0x93, 0xb6, 0x4a, 0x0e, 0x79, 0x94,
	0x9f, 0x35, 0x38, 0x57, 0xf0, 0x0c, 0x21, 0xeb, 0x39, 0x9e, 0xce, 0x79, 0xa7, 0x98, 0x17, 0x33,
	0x5e, 0x4f, 0x6a, 0x59, 0xef, 0x21, 0x9c, 0x36, 0x79, 0x3b, 0x17, 0x4e, 0xf4, 0xc2, 0x51, 0xa0,
	0x28, 0x6f, 0x3f, 0x09, 0x77, 0x7f, 0x06, 0x8b, 0x99, 0xbb, 0x18, 0x69, 0xe5, 0x40, 0x4a, 0x5d,
	0xd3, 0xcc, 0x73, 0x19, 0x30, 0x6a, 0xde, 0x5a, 0x47, 0x18, 0x2d, 0xb2, 0x52, 0xc8, 0x8a, 0xbc,
	0x50, 0x71, 0xf2, 0x22, 0xd5, 0xa7, 0xa3, 0x9b, 0xed, 0x6a, 0xee, 0xc6, 0xc9, 0xfb, 0xa9, 0xd9,
	0xcc, 0xd9, 0x19, 0x15, 0xac, 0x2b, 0xb8, 0xf5, 0x2a, 0x29, 0x76, 0x08, 0xbe, 0x13, 0x38, 0xf9,
	0x4d, 0x83, 0x0b, 0xd3, 0x7e, 0x7a, 0x90, 0x6b, 0xc5, 0x30, 0x32, 0xbf, 0x46, 0x4c, 0x6b, 0xfa,
	0x2b, 0x5c, 0xc2, 0xb4, 0xde, 0x47, 0x68, 0xdb, 0xe4, 0xc6, 0x0c, 0xce, 0x51, 0xcb, 0x22, 0xac,
	0xaf, 0x35, 0xb8, 0xf4, 0x86, 0xe7, 0x33, 0xd9, 0x4a, 0xc3, 0x7d, 0xd3, 0x3b, 0xdb, 0x3c, 0x9b,
	0xa1, 0x50, 0x2a, 0x5b, 0x57, 0x11, 0xe4, 0x1a, 0x59, 0x4d, 0x81, 0xec, 0xa3, 0x35, 0x1e, 0x81,
	0x95, 0x7d, 0x83, 0x1f, 0x95, 0xf1, 0xe7, 0xd1, 0x3b, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x12,
	0x6e, 0x54, 0x1c, 0x7e, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentServiceClient interface {
	// Create Agent
	CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// List of Agent
	SearchAgent(ctx context.Context, in *SearchAgentRequest, opts ...grpc.CallOption) (*ListAgent, error)
	// Agent item
	ReadAgent(ctx context.Context, in *ReadAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// Update Agent
	UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// Remove Agent
	DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// Change agent status
	UpdateAgentStatus(ctx context.Context, in *AgentStatusRequest, opts ...grpc.CallOption) (*Response, error)
	// List of Agent
	SearchAgentStateHistory(ctx context.Context, in *SearchAgentStateHistoryRequest, opts ...grpc.CallOption) (*ListAgentStateHistory, error)
	SearchAgentInTeam(ctx context.Context, in *SearchAgentInTeamRequest, opts ...grpc.CallOption) (*ListAgentInTeam, error)
	SearchAgentInQueue(ctx context.Context, in *SearchAgentInQueueRequest, opts ...grpc.CallOption) (*ListAgentInQueue, error)
	SearchAgentInQueueStatistics(ctx context.Context, in *SearchAgentInQueueStatisticsRequest, opts ...grpc.CallOption) (*AgentInQueueStatisticsList, error)
	// SearchLookupAgentNotExistsUser
	SearchLookupUsersAgentNotExists(ctx context.Context, in *SearchLookupUsersAgentNotExistsRequest, opts ...grpc.CallOption) (*ListAgentUser, error)
}

type agentServiceClient struct {
	cc *grpc.ClientConn
}

func NewAgentServiceClient(cc *grpc.ClientConn) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, "/engine.AgentService/CreateAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SearchAgent(ctx context.Context, in *SearchAgentRequest, opts ...grpc.CallOption) (*ListAgent, error) {
	out := new(ListAgent)
	err := c.cc.Invoke(ctx, "/engine.AgentService/SearchAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReadAgent(ctx context.Context, in *ReadAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, "/engine.AgentService/ReadAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, "/engine.AgentService/UpdateAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	out := new(Agent)
	err := c.cc.Invoke(ctx, "/engine.AgentService/DeleteAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateAgentStatus(ctx context.Context, in *AgentStatusRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/engine.AgentService/UpdateAgentStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SearchAgentStateHistory(ctx context.Context, in *SearchAgentStateHistoryRequest, opts ...grpc.CallOption) (*ListAgentStateHistory, error) {
	out := new(ListAgentStateHistory)
	err := c.cc.Invoke(ctx, "/engine.AgentService/SearchAgentStateHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SearchAgentInTeam(ctx context.Context, in *SearchAgentInTeamRequest, opts ...grpc.CallOption) (*ListAgentInTeam, error) {
	out := new(ListAgentInTeam)
	err := c.cc.Invoke(ctx, "/engine.AgentService/SearchAgentInTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SearchAgentInQueue(ctx context.Context, in *SearchAgentInQueueRequest, opts ...grpc.CallOption) (*ListAgentInQueue, error) {
	out := new(ListAgentInQueue)
	err := c.cc.Invoke(ctx, "/engine.AgentService/SearchAgentInQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SearchAgentInQueueStatistics(ctx context.Context, in *SearchAgentInQueueStatisticsRequest, opts ...grpc.CallOption) (*AgentInQueueStatisticsList, error) {
	out := new(AgentInQueueStatisticsList)
	err := c.cc.Invoke(ctx, "/engine.AgentService/SearchAgentInQueueStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SearchLookupUsersAgentNotExists(ctx context.Context, in *SearchLookupUsersAgentNotExistsRequest, opts ...grpc.CallOption) (*ListAgentUser, error) {
	out := new(ListAgentUser)
	err := c.cc.Invoke(ctx, "/engine.AgentService/SearchLookupUsersAgentNotExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
type AgentServiceServer interface {
	// Create Agent
	CreateAgent(context.Context, *CreateAgentRequest) (*Agent, error)
	// List of Agent
	SearchAgent(context.Context, *SearchAgentRequest) (*ListAgent, error)
	// Agent item
	ReadAgent(context.Context, *ReadAgentRequest) (*Agent, error)
	// Update Agent
	UpdateAgent(context.Context, *UpdateAgentRequest) (*Agent, error)
	// Remove Agent
	DeleteAgent(context.Context, *DeleteAgentRequest) (*Agent, error)
	// Change agent status
	UpdateAgentStatus(context.Context, *AgentStatusRequest) (*Response, error)
	// List of Agent
	SearchAgentStateHistory(context.Context, *SearchAgentStateHistoryRequest) (*ListAgentStateHistory, error)
	SearchAgentInTeam(context.Context, *SearchAgentInTeamRequest) (*ListAgentInTeam, error)
	SearchAgentInQueue(context.Context, *SearchAgentInQueueRequest) (*ListAgentInQueue, error)
	SearchAgentInQueueStatistics(context.Context, *SearchAgentInQueueStatisticsRequest) (*AgentInQueueStatisticsList, error)
	// SearchLookupAgentNotExistsUser
	SearchLookupUsersAgentNotExists(context.Context, *SearchLookupUsersAgentNotExistsRequest) (*ListAgentUser, error)
}

// UnimplementedAgentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (*UnimplementedAgentServiceServer) CreateAgent(ctx context.Context, req *CreateAgentRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAgent not implemented")
}
func (*UnimplementedAgentServiceServer) SearchAgent(ctx context.Context, req *SearchAgentRequest) (*ListAgent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAgent not implemented")
}
func (*UnimplementedAgentServiceServer) ReadAgent(ctx context.Context, req *ReadAgentRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAgent not implemented")
}
func (*UnimplementedAgentServiceServer) UpdateAgent(ctx context.Context, req *UpdateAgentRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgent not implemented")
}
func (*UnimplementedAgentServiceServer) DeleteAgent(ctx context.Context, req *DeleteAgentRequest) (*Agent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAgent not implemented")
}
func (*UnimplementedAgentServiceServer) UpdateAgentStatus(ctx context.Context, req *AgentStatusRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgentStatus not implemented")
}
func (*UnimplementedAgentServiceServer) SearchAgentStateHistory(ctx context.Context, req *SearchAgentStateHistoryRequest) (*ListAgentStateHistory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAgentStateHistory not implemented")
}
func (*UnimplementedAgentServiceServer) SearchAgentInTeam(ctx context.Context, req *SearchAgentInTeamRequest) (*ListAgentInTeam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAgentInTeam not implemented")
}
func (*UnimplementedAgentServiceServer) SearchAgentInQueue(ctx context.Context, req *SearchAgentInQueueRequest) (*ListAgentInQueue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAgentInQueue not implemented")
}
func (*UnimplementedAgentServiceServer) SearchAgentInQueueStatistics(ctx context.Context, req *SearchAgentInQueueStatisticsRequest) (*AgentInQueueStatisticsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAgentInQueueStatistics not implemented")
}
func (*UnimplementedAgentServiceServer) SearchLookupUsersAgentNotExists(ctx context.Context, req *SearchLookupUsersAgentNotExistsRequest) (*ListAgentUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchLookupUsersAgentNotExists not implemented")
}

func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {
	s.RegisterService(&_AgentService_serviceDesc, srv)
}

func _AgentService_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentService/CreateAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateAgent(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SearchAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SearchAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentService/SearchAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SearchAgent(ctx, req.(*SearchAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReadAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReadAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentService/ReadAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReadAgent(ctx, req.(*ReadAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentService/UpdateAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateAgent(ctx, req.(*UpdateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeleteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeleteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentService/DeleteAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeleteAgent(ctx, req.(*DeleteAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentService/UpdateAgentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateAgentStatus(ctx, req.(*AgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SearchAgentStateHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAgentStateHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SearchAgentStateHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentService/SearchAgentStateHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SearchAgentStateHistory(ctx, req.(*SearchAgentStateHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SearchAgentInTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAgentInTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SearchAgentInTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentService/SearchAgentInTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SearchAgentInTeam(ctx, req.(*SearchAgentInTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SearchAgentInQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAgentInQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SearchAgentInQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentService/SearchAgentInQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SearchAgentInQueue(ctx, req.(*SearchAgentInQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SearchAgentInQueueStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAgentInQueueStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SearchAgentInQueueStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentService/SearchAgentInQueueStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SearchAgentInQueueStatistics(ctx, req.(*SearchAgentInQueueStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SearchLookupUsersAgentNotExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchLookupUsersAgentNotExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SearchLookupUsersAgentNotExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentService/SearchLookupUsersAgentNotExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SearchLookupUsersAgentNotExists(ctx, req.(*SearchLookupUsersAgentNotExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "engine.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgent",
			Handler:    _AgentService_CreateAgent_Handler,
		},
		{
			MethodName: "SearchAgent",
			Handler:    _AgentService_SearchAgent_Handler,
		},
		{
			MethodName: "ReadAgent",
			Handler:    _AgentService_ReadAgent_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _AgentService_UpdateAgent_Handler,
		},
		{
			MethodName: "DeleteAgent",
			Handler:    _AgentService_DeleteAgent_Handler,
		},
		{
			MethodName: "UpdateAgentStatus",
			Handler:    _AgentService_UpdateAgentStatus_Handler,
		},
		{
			MethodName: "SearchAgentStateHistory",
			Handler:    _AgentService_SearchAgentStateHistory_Handler,
		},
		{
			MethodName: "SearchAgentInTeam",
			Handler:    _AgentService_SearchAgentInTeam_Handler,
		},
		{
			MethodName: "SearchAgentInQueue",
			Handler:    _AgentService_SearchAgentInQueue_Handler,
		},
		{
			MethodName: "SearchAgentInQueueStatistics",
			Handler:    _AgentService_SearchAgentInQueueStatistics_Handler,
		},
		{
			MethodName: "SearchLookupUsersAgentNotExists",
			Handler:    _AgentService_SearchLookupUsersAgentNotExists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
