// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent_team.proto

package engine

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteAgentTeamRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId             int64    `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAgentTeamRequest) Reset()         { *m = DeleteAgentTeamRequest{} }
func (m *DeleteAgentTeamRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAgentTeamRequest) ProtoMessage()    {}
func (*DeleteAgentTeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3083856eea12172, []int{0}
}

func (m *DeleteAgentTeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAgentTeamRequest.Unmarshal(m, b)
}
func (m *DeleteAgentTeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAgentTeamRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAgentTeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAgentTeamRequest.Merge(m, src)
}
func (m *DeleteAgentTeamRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAgentTeamRequest.Size(m)
}
func (m *DeleteAgentTeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAgentTeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAgentTeamRequest proto.InternalMessageInfo

func (m *DeleteAgentTeamRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteAgentTeamRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type UpdateAgentTeamRequest struct {
	Id                    int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description           string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Strategy              string   `protobuf:"bytes,4,opt,name=strategy,proto3" json:"strategy,omitempty"`
	MaxNoAnswer           int32    `protobuf:"varint,5,opt,name=max_no_answer,json=maxNoAnswer,proto3" json:"max_no_answer,omitempty"`
	WrapUpTime            int32    `protobuf:"varint,6,opt,name=wrap_up_time,json=wrapUpTime,proto3" json:"wrap_up_time,omitempty"`
	RejectDelayTime       int32    `protobuf:"varint,7,opt,name=reject_delay_time,json=rejectDelayTime,proto3" json:"reject_delay_time,omitempty"`
	BusyDelayTime         int32    `protobuf:"varint,8,opt,name=busy_delay_time,json=busyDelayTime,proto3" json:"busy_delay_time,omitempty"`
	NoAnswerDelayTime     int32    `protobuf:"varint,9,opt,name=no_answer_delay_time,json=noAnswerDelayTime,proto3" json:"no_answer_delay_time,omitempty"`
	CallTimeout           int32    `protobuf:"varint,10,opt,name=call_timeout,json=callTimeout,proto3" json:"call_timeout,omitempty"`
	PostProcessing        bool     `protobuf:"varint,11,opt,name=post_processing,json=postProcessing,proto3" json:"post_processing,omitempty"`
	PostProcessingTimeout int32    `protobuf:"varint,12,opt,name=post_processing_timeout,json=postProcessingTimeout,proto3" json:"post_processing_timeout,omitempty"`
	DomainId              int64    `protobuf:"varint,13,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *UpdateAgentTeamRequest) Reset()         { *m = UpdateAgentTeamRequest{} }
func (m *UpdateAgentTeamRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAgentTeamRequest) ProtoMessage()    {}
func (*UpdateAgentTeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3083856eea12172, []int{1}
}

func (m *UpdateAgentTeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAgentTeamRequest.Unmarshal(m, b)
}
func (m *UpdateAgentTeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAgentTeamRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAgentTeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAgentTeamRequest.Merge(m, src)
}
func (m *UpdateAgentTeamRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAgentTeamRequest.Size(m)
}
func (m *UpdateAgentTeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAgentTeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAgentTeamRequest proto.InternalMessageInfo

func (m *UpdateAgentTeamRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateAgentTeamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateAgentTeamRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateAgentTeamRequest) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *UpdateAgentTeamRequest) GetMaxNoAnswer() int32 {
	if m != nil {
		return m.MaxNoAnswer
	}
	return 0
}

func (m *UpdateAgentTeamRequest) GetWrapUpTime() int32 {
	if m != nil {
		return m.WrapUpTime
	}
	return 0
}

func (m *UpdateAgentTeamRequest) GetRejectDelayTime() int32 {
	if m != nil {
		return m.RejectDelayTime
	}
	return 0
}

func (m *UpdateAgentTeamRequest) GetBusyDelayTime() int32 {
	if m != nil {
		return m.BusyDelayTime
	}
	return 0
}

func (m *UpdateAgentTeamRequest) GetNoAnswerDelayTime() int32 {
	if m != nil {
		return m.NoAnswerDelayTime
	}
	return 0
}

func (m *UpdateAgentTeamRequest) GetCallTimeout() int32 {
	if m != nil {
		return m.CallTimeout
	}
	return 0
}

func (m *UpdateAgentTeamRequest) GetPostProcessing() bool {
	if m != nil {
		return m.PostProcessing
	}
	return false
}

func (m *UpdateAgentTeamRequest) GetPostProcessingTimeout() int32 {
	if m != nil {
		return m.PostProcessingTimeout
	}
	return 0
}

func (m *UpdateAgentTeamRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type ReadAgentTeamRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId             int64    `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAgentTeamRequest) Reset()         { *m = ReadAgentTeamRequest{} }
func (m *ReadAgentTeamRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAgentTeamRequest) ProtoMessage()    {}
func (*ReadAgentTeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3083856eea12172, []int{2}
}

func (m *ReadAgentTeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAgentTeamRequest.Unmarshal(m, b)
}
func (m *ReadAgentTeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAgentTeamRequest.Marshal(b, m, deterministic)
}
func (m *ReadAgentTeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAgentTeamRequest.Merge(m, src)
}
func (m *ReadAgentTeamRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAgentTeamRequest.Size(m)
}
func (m *ReadAgentTeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAgentTeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAgentTeamRequest proto.InternalMessageInfo

func (m *ReadAgentTeamRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReadAgentTeamRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type SearchAgentTeamRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Q                    string   `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	DomainId             int64    `protobuf:"varint,4,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchAgentTeamRequest) Reset()         { *m = SearchAgentTeamRequest{} }
func (m *SearchAgentTeamRequest) String() string { return proto.CompactTextString(m) }
func (*SearchAgentTeamRequest) ProtoMessage()    {}
func (*SearchAgentTeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3083856eea12172, []int{3}
}

func (m *SearchAgentTeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchAgentTeamRequest.Unmarshal(m, b)
}
func (m *SearchAgentTeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchAgentTeamRequest.Marshal(b, m, deterministic)
}
func (m *SearchAgentTeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchAgentTeamRequest.Merge(m, src)
}
func (m *SearchAgentTeamRequest) XXX_Size() int {
	return xxx_messageInfo_SearchAgentTeamRequest.Size(m)
}
func (m *SearchAgentTeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchAgentTeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchAgentTeamRequest proto.InternalMessageInfo

func (m *SearchAgentTeamRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchAgentTeamRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchAgentTeamRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchAgentTeamRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type CreateAgentTeamRequest struct {
	Name                  string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description           string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Strategy              string   `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	MaxNoAnswer           int32    `protobuf:"varint,4,opt,name=max_no_answer,json=maxNoAnswer,proto3" json:"max_no_answer,omitempty"`
	WrapUpTime            int32    `protobuf:"varint,5,opt,name=wrap_up_time,json=wrapUpTime,proto3" json:"wrap_up_time,omitempty"`
	RejectDelayTime       int32    `protobuf:"varint,6,opt,name=reject_delay_time,json=rejectDelayTime,proto3" json:"reject_delay_time,omitempty"`
	BusyDelayTime         int32    `protobuf:"varint,7,opt,name=busy_delay_time,json=busyDelayTime,proto3" json:"busy_delay_time,omitempty"`
	NoAnswerDelayTime     int32    `protobuf:"varint,8,opt,name=no_answer_delay_time,json=noAnswerDelayTime,proto3" json:"no_answer_delay_time,omitempty"`
	CallTimeout           int32    `protobuf:"varint,9,opt,name=call_timeout,json=callTimeout,proto3" json:"call_timeout,omitempty"`
	PostProcessing        bool     `protobuf:"varint,10,opt,name=post_processing,json=postProcessing,proto3" json:"post_processing,omitempty"`
	PostProcessingTimeout int32    `protobuf:"varint,11,opt,name=post_processing_timeout,json=postProcessingTimeout,proto3" json:"post_processing_timeout,omitempty"`
	DomainId              int64    `protobuf:"varint,12,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *CreateAgentTeamRequest) Reset()         { *m = CreateAgentTeamRequest{} }
func (m *CreateAgentTeamRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAgentTeamRequest) ProtoMessage()    {}
func (*CreateAgentTeamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3083856eea12172, []int{4}
}

func (m *CreateAgentTeamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAgentTeamRequest.Unmarshal(m, b)
}
func (m *CreateAgentTeamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAgentTeamRequest.Marshal(b, m, deterministic)
}
func (m *CreateAgentTeamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAgentTeamRequest.Merge(m, src)
}
func (m *CreateAgentTeamRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAgentTeamRequest.Size(m)
}
func (m *CreateAgentTeamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAgentTeamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAgentTeamRequest proto.InternalMessageInfo

func (m *CreateAgentTeamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAgentTeamRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateAgentTeamRequest) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *CreateAgentTeamRequest) GetMaxNoAnswer() int32 {
	if m != nil {
		return m.MaxNoAnswer
	}
	return 0
}

func (m *CreateAgentTeamRequest) GetWrapUpTime() int32 {
	if m != nil {
		return m.WrapUpTime
	}
	return 0
}

func (m *CreateAgentTeamRequest) GetRejectDelayTime() int32 {
	if m != nil {
		return m.RejectDelayTime
	}
	return 0
}

func (m *CreateAgentTeamRequest) GetBusyDelayTime() int32 {
	if m != nil {
		return m.BusyDelayTime
	}
	return 0
}

func (m *CreateAgentTeamRequest) GetNoAnswerDelayTime() int32 {
	if m != nil {
		return m.NoAnswerDelayTime
	}
	return 0
}

func (m *CreateAgentTeamRequest) GetCallTimeout() int32 {
	if m != nil {
		return m.CallTimeout
	}
	return 0
}

func (m *CreateAgentTeamRequest) GetPostProcessing() bool {
	if m != nil {
		return m.PostProcessing
	}
	return false
}

func (m *CreateAgentTeamRequest) GetPostProcessingTimeout() int32 {
	if m != nil {
		return m.PostProcessingTimeout
	}
	return 0
}

func (m *CreateAgentTeamRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type AgentTeam struct {
	Id                    int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId              int64    `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Name                  string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description           string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Strategy              string   `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	MaxNoAnswer           int32    `protobuf:"varint,6,opt,name=max_no_answer,json=maxNoAnswer,proto3" json:"max_no_answer,omitempty"`
	WrapUpTime            int32    `protobuf:"varint,7,opt,name=wrap_up_time,json=wrapUpTime,proto3" json:"wrap_up_time,omitempty"`
	RejectDelayTime       int32    `protobuf:"varint,8,opt,name=reject_delay_time,json=rejectDelayTime,proto3" json:"reject_delay_time,omitempty"`
	BusyDelayTime         int32    `protobuf:"varint,9,opt,name=busy_delay_time,json=busyDelayTime,proto3" json:"busy_delay_time,omitempty"`
	NoAnswerDelayTime     int32    `protobuf:"varint,10,opt,name=no_answer_delay_time,json=noAnswerDelayTime,proto3" json:"no_answer_delay_time,omitempty"`
	CallTimeout           int32    `protobuf:"varint,11,opt,name=call_timeout,json=callTimeout,proto3" json:"call_timeout,omitempty"`
	UpdatedAt             int64    `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PostProcessing        bool     `protobuf:"varint,13,opt,name=post_processing,json=postProcessing,proto3" json:"post_processing,omitempty"`
	PostProcessingTimeout int32    `protobuf:"varint,14,opt,name=post_processing_timeout,json=postProcessingTimeout,proto3" json:"post_processing_timeout,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *AgentTeam) Reset()         { *m = AgentTeam{} }
func (m *AgentTeam) String() string { return proto.CompactTextString(m) }
func (*AgentTeam) ProtoMessage()    {}
func (*AgentTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3083856eea12172, []int{5}
}

func (m *AgentTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentTeam.Unmarshal(m, b)
}
func (m *AgentTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentTeam.Marshal(b, m, deterministic)
}
func (m *AgentTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentTeam.Merge(m, src)
}
func (m *AgentTeam) XXX_Size() int {
	return xxx_messageInfo_AgentTeam.Size(m)
}
func (m *AgentTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentTeam.DiscardUnknown(m)
}

var xxx_messageInfo_AgentTeam proto.InternalMessageInfo

func (m *AgentTeam) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AgentTeam) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

func (m *AgentTeam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AgentTeam) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AgentTeam) GetStrategy() string {
	if m != nil {
		return m.Strategy
	}
	return ""
}

func (m *AgentTeam) GetMaxNoAnswer() int32 {
	if m != nil {
		return m.MaxNoAnswer
	}
	return 0
}

func (m *AgentTeam) GetWrapUpTime() int32 {
	if m != nil {
		return m.WrapUpTime
	}
	return 0
}

func (m *AgentTeam) GetRejectDelayTime() int32 {
	if m != nil {
		return m.RejectDelayTime
	}
	return 0
}

func (m *AgentTeam) GetBusyDelayTime() int32 {
	if m != nil {
		return m.BusyDelayTime
	}
	return 0
}

func (m *AgentTeam) GetNoAnswerDelayTime() int32 {
	if m != nil {
		return m.NoAnswerDelayTime
	}
	return 0
}

func (m *AgentTeam) GetCallTimeout() int32 {
	if m != nil {
		return m.CallTimeout
	}
	return 0
}

func (m *AgentTeam) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *AgentTeam) GetPostProcessing() bool {
	if m != nil {
		return m.PostProcessing
	}
	return false
}

func (m *AgentTeam) GetPostProcessingTimeout() int32 {
	if m != nil {
		return m.PostProcessingTimeout
	}
	return 0
}

type ListAgentTeam struct {
	Next                 bool         `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items                []*AgentTeam `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListAgentTeam) Reset()         { *m = ListAgentTeam{} }
func (m *ListAgentTeam) String() string { return proto.CompactTextString(m) }
func (*ListAgentTeam) ProtoMessage()    {}
func (*ListAgentTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3083856eea12172, []int{6}
}

func (m *ListAgentTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAgentTeam.Unmarshal(m, b)
}
func (m *ListAgentTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAgentTeam.Marshal(b, m, deterministic)
}
func (m *ListAgentTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAgentTeam.Merge(m, src)
}
func (m *ListAgentTeam) XXX_Size() int {
	return xxx_messageInfo_ListAgentTeam.Size(m)
}
func (m *ListAgentTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAgentTeam.DiscardUnknown(m)
}

var xxx_messageInfo_ListAgentTeam proto.InternalMessageInfo

func (m *ListAgentTeam) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *ListAgentTeam) GetItems() []*AgentTeam {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*DeleteAgentTeamRequest)(nil), "engine.DeleteAgentTeamRequest")
	proto.RegisterType((*UpdateAgentTeamRequest)(nil), "engine.UpdateAgentTeamRequest")
	proto.RegisterType((*ReadAgentTeamRequest)(nil), "engine.ReadAgentTeamRequest")
	proto.RegisterType((*SearchAgentTeamRequest)(nil), "engine.SearchAgentTeamRequest")
	proto.RegisterType((*CreateAgentTeamRequest)(nil), "engine.CreateAgentTeamRequest")
	proto.RegisterType((*AgentTeam)(nil), "engine.AgentTeam")
	proto.RegisterType((*ListAgentTeam)(nil), "engine.ListAgentTeam")
}

func init() { proto.RegisterFile("agent_team.proto", fileDescriptor_e3083856eea12172) }

var fileDescriptor_e3083856eea12172 = []byte{
	// 732 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x4e, 0xdb, 0x4a,
	0x18, 0x95, 0xe3, 0x24, 0xd8, 0x5f, 0x12, 0x0c, 0x23, 0x08, 0xbe, 0xb9, 0x70, 0x6f, 0xae, 0x17,
	0x97, 0x88, 0x05, 0x91, 0xa8, 0xd4, 0x45, 0x77, 0x08, 0xba, 0xa8, 0x84, 0xaa, 0xca, 0xc0, 0xda,
	0x1a, 0xec, 0x4f, 0x66, 0xda, 0xf8, 0x07, 0x7b, 0x52, 0xa0, 0x55, 0x37, 0x7d, 0x83, 0xaa, 0x8f,
	0x56, 0xa9, 0x4f, 0x50, 0xf5, 0x19, 0xba, 0xac, 0x3c, 0x4e, 0x6c, 0xe2, 0x38, 0x89, 0xa3, 0xee,
	0xc6, 0x67, 0x8e, 0xbf, 0x33, 0x33, 0xe7, 0xe8, 0x9b, 0x81, 0x2d, 0xea, 0xa2, 0xcf, 0x2d, 0x8e,
	0xd4, 0x3b, 0x0e, 0xa3, 0x80, 0x07, 0xa4, 0x89, 0xbe, 0xcb, 0x7c, 0xec, 0xed, 0xbb, 0x41, 0xe0,
	0x8e, 0x70, 0x48, 0x43, 0x36, 0xa4, 0xbe, 0x1f, 0x70, 0xca, 0x59, 0xe0, 0xc7, 0x29, 0xcb, 0x78,
	0x09, 0xdd, 0x73, 0x1c, 0x21, 0xc7, 0xd3, 0xe4, 0xff, 0x2b, 0xa4, 0x9e, 0x89, 0x77, 0x63, 0x8c,
	0x39, 0xd9, 0x84, 0x1a, 0x73, 0x74, 0xa9, 0x2f, 0x0d, 0x64, 0xb3, 0xc6, 0x1c, 0xf2, 0x37, 0xa8,
	0x4e, 0xe0, 0x51, 0xe6, 0x5b, 0xcc, 0xd1, 0x6b, 0x02, 0x56, 0x52, 0xe0, 0x95, 0x63, 0xfc, 0x94,
	0xa1, 0x7b, 0x1d, 0x3a, 0xb4, 0x42, 0x1d, 0x02, 0x75, 0x9f, 0x7a, 0x28, 0x4a, 0xa8, 0xa6, 0x18,
	0x93, 0x3e, 0xb4, 0x1c, 0x8c, 0xed, 0x88, 0x85, 0xc9, 0xda, 0x74, 0x59, 0x4c, 0x3d, 0x85, 0x48,
	0x0f, 0x94, 0x98, 0x47, 0x94, 0xa3, 0xfb, 0xa8, 0xd7, 0xc5, 0x74, 0xf6, 0x4d, 0x0c, 0xe8, 0x78,
	0xf4, 0xc1, 0xf2, 0x03, 0x8b, 0xfa, 0xf1, 0x3d, 0x46, 0x7a, 0xa3, 0x2f, 0x0d, 0x1a, 0x66, 0xcb,
	0xa3, 0x0f, 0xaf, 0x83, 0x53, 0x01, 0x91, 0x3e, 0xb4, 0xef, 0x23, 0x1a, 0x5a, 0xe3, 0xd0, 0xe2,
	0xcc, 0x43, 0xbd, 0x29, 0x28, 0x90, 0x60, 0xd7, 0xe1, 0x15, 0xf3, 0x90, 0x1c, 0xc1, 0x76, 0x84,
	0x6f, 0xd1, 0xe6, 0x96, 0x83, 0x23, 0xfa, 0x98, 0xd2, 0x36, 0x04, 0x4d, 0x4b, 0x27, 0xce, 0x13,
	0x5c, 0x70, 0xff, 0x07, 0xed, 0x66, 0x1c, 0x3f, 0x3e, 0x65, 0x2a, 0x82, 0xd9, 0x49, 0xe0, 0x9c,
	0x37, 0x84, 0x9d, 0x6c, 0x55, 0x4f, 0xc9, 0xaa, 0x20, 0x6f, 0xfb, 0x93, 0xd5, 0xe5, 0x3f, 0xfc,
	0x07, 0x6d, 0x9b, 0x8e, 0x46, 0x82, 0x15, 0x8c, 0xb9, 0x0e, 0xe9, 0x4e, 0x12, 0xec, 0x2a, 0x85,
	0xc8, 0x21, 0x68, 0x61, 0x10, 0x73, 0x2b, 0x8c, 0x02, 0x1b, 0xe3, 0x98, 0xf9, 0xae, 0xde, 0xea,
	0x4b, 0x03, 0xc5, 0xdc, 0x4c, 0xe0, 0x37, 0x19, 0x4a, 0x9e, 0xc3, 0x5e, 0x81, 0x98, 0x95, 0x6d,
	0x8b, 0xb2, 0xbb, 0xb3, 0x3f, 0x4c, 0x05, 0x66, 0x8c, 0xee, 0x14, 0x8c, 0x3e, 0x83, 0x1d, 0x13,
	0xa9, 0xf3, 0x67, 0x69, 0x79, 0x07, 0xdd, 0x4b, 0xa4, 0x91, 0x7d, 0x3b, 0x57, 0x86, 0x40, 0x3d,
	0xa4, 0x2e, 0x8a, 0x42, 0x0d, 0x53, 0x8c, 0x13, 0x2c, 0x66, 0x1f, 0xd2, 0xc0, 0x34, 0x4c, 0x31,
	0x26, 0x6d, 0x90, 0xee, 0x26, 0x31, 0x91, 0xee, 0x66, 0xc5, 0xea, 0x05, 0xb1, 0xef, 0x32, 0x74,
	0xcf, 0x22, 0x2c, 0x8b, 0xe6, 0x34, 0x8a, 0xd2, 0xe2, 0x28, 0xd6, 0x96, 0x47, 0x51, 0x5e, 0x15,
	0xc5, 0xfa, 0xea, 0x28, 0x36, 0xaa, 0x45, 0xb1, 0x59, 0x39, 0x8a, 0x1b, 0xeb, 0x44, 0x51, 0xa9,
	0x1a, 0x45, 0xb5, 0x52, 0x14, 0x61, 0xdd, 0x28, 0xb6, 0x2a, 0x47, 0xb1, 0x5d, 0x30, 0xf6, 0x97,
	0x0c, 0x6a, 0x66, 0xe9, 0x5a, 0x01, 0xcc, 0x8c, 0x97, 0x17, 0x1b, 0x5f, 0x5f, 0x6e, 0x7c, 0x63,
	0x95, 0xf1, 0xcd, 0xd5, 0xc6, 0x6f, 0x54, 0x33, 0x5e, 0xa9, 0x6c, 0xbc, 0xba, 0x8e, 0xf1, 0x50,
	0xd5, 0xf8, 0xd6, 0xbc, 0xf1, 0x07, 0x00, 0x63, 0xd1, 0xed, 0x1d, 0x8b, 0xf2, 0x89, 0x31, 0xea,
	0x04, 0x39, 0x2d, 0xcd, 0x45, 0x67, 0xdd, 0x5c, 0x6c, 0x2e, 0xc9, 0x85, 0x71, 0x01, 0x9d, 0x0b,
	0x16, 0xf3, 0xdc, 0xfd, 0xc4, 0x50, 0x7c, 0xe0, 0xc2, 0x7f, 0xc5, 0x14, 0x63, 0x72, 0x08, 0x0d,
	0xc6, 0xd1, 0x8b, 0xf5, 0x5a, 0x5f, 0x1e, 0xb4, 0x4e, 0xb6, 0x8f, 0xd3, 0x0b, 0xf1, 0x38, 0x6f,
	0x03, 0xe9, 0xfc, 0xc9, 0x97, 0x3a, 0x6c, 0x65, 0xe0, 0x25, 0x46, 0xef, 0x99, 0x8d, 0xc4, 0x06,
	0xad, 0xd0, 0x35, 0xc8, 0x3f, 0xd3, 0x0a, 0xe5, 0xed, 0xa4, 0x37, 0xaf, 0x60, 0x1c, 0x7c, 0xfe,
	0xf6, 0xe3, 0x6b, 0x6d, 0xcf, 0x20, 0x43, 0x71, 0xa4, 0x36, 0xfa, 0x1c, 0xa3, 0x61, 0x72, 0x4b,
	0xc7, 0x2f, 0xa4, 0x23, 0xe2, 0x80, 0x56, 0x68, 0x84, 0xb9, 0x48, 0x79, 0x87, 0xec, 0xed, 0x4e,
	0xe7, 0x67, 0x0e, 0xc0, 0xe8, 0x09, 0xa1, 0x1d, 0x52, 0x22, 0x44, 0x28, 0x74, 0x66, 0x7a, 0x36,
	0xd9, 0x9f, 0xd6, 0x28, 0x6b, 0xe5, 0x65, 0xdb, 0xf8, 0x57, 0x54, 0xff, 0x8b, 0xec, 0xcd, 0x57,
	0x1f, 0x7e, 0x64, 0xce, 0x27, 0x72, 0x0b, 0x5a, 0xe1, 0xfa, 0xcf, 0x37, 0x52, 0xfe, 0x2e, 0x28,
	0x93, 0x31, 0x84, 0xcc, 0x7e, 0x6f, 0x91, 0x4c, 0x72, 0x64, 0x08, 0x5a, 0xe1, 0xc1, 0x92, 0x2b,
	0x95, 0xbf, 0x64, 0x96, 0x6c, 0xe8, 0x68, 0x91, 0xd2, 0x4d, 0x53, 0x3c, 0x8f, 0x9e, 0xfd, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0xbc, 0x88, 0x44, 0xaf, 0x58, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentTeamServiceClient is the client API for AgentTeamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentTeamServiceClient interface {
	// Create AgentTeam
	CreateAgentTeam(ctx context.Context, in *CreateAgentTeamRequest, opts ...grpc.CallOption) (*AgentTeam, error)
	// List of AgentTeam
	SearchAgentTeam(ctx context.Context, in *SearchAgentTeamRequest, opts ...grpc.CallOption) (*ListAgentTeam, error)
	// AgentTeam item
	ReadAgentTeam(ctx context.Context, in *ReadAgentTeamRequest, opts ...grpc.CallOption) (*AgentTeam, error)
	// Update AgentTeam
	UpdateAgentTeam(ctx context.Context, in *UpdateAgentTeamRequest, opts ...grpc.CallOption) (*AgentTeam, error)
	// Remove AgentTeam
	DeleteAgentTeam(ctx context.Context, in *DeleteAgentTeamRequest, opts ...grpc.CallOption) (*AgentTeam, error)
}

type agentTeamServiceClient struct {
	cc *grpc.ClientConn
}

func NewAgentTeamServiceClient(cc *grpc.ClientConn) AgentTeamServiceClient {
	return &agentTeamServiceClient{cc}
}

func (c *agentTeamServiceClient) CreateAgentTeam(ctx context.Context, in *CreateAgentTeamRequest, opts ...grpc.CallOption) (*AgentTeam, error) {
	out := new(AgentTeam)
	err := c.cc.Invoke(ctx, "/engine.AgentTeamService/CreateAgentTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentTeamServiceClient) SearchAgentTeam(ctx context.Context, in *SearchAgentTeamRequest, opts ...grpc.CallOption) (*ListAgentTeam, error) {
	out := new(ListAgentTeam)
	err := c.cc.Invoke(ctx, "/engine.AgentTeamService/SearchAgentTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentTeamServiceClient) ReadAgentTeam(ctx context.Context, in *ReadAgentTeamRequest, opts ...grpc.CallOption) (*AgentTeam, error) {
	out := new(AgentTeam)
	err := c.cc.Invoke(ctx, "/engine.AgentTeamService/ReadAgentTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentTeamServiceClient) UpdateAgentTeam(ctx context.Context, in *UpdateAgentTeamRequest, opts ...grpc.CallOption) (*AgentTeam, error) {
	out := new(AgentTeam)
	err := c.cc.Invoke(ctx, "/engine.AgentTeamService/UpdateAgentTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentTeamServiceClient) DeleteAgentTeam(ctx context.Context, in *DeleteAgentTeamRequest, opts ...grpc.CallOption) (*AgentTeam, error) {
	out := new(AgentTeam)
	err := c.cc.Invoke(ctx, "/engine.AgentTeamService/DeleteAgentTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentTeamServiceServer is the server API for AgentTeamService service.
type AgentTeamServiceServer interface {
	// Create AgentTeam
	CreateAgentTeam(context.Context, *CreateAgentTeamRequest) (*AgentTeam, error)
	// List of AgentTeam
	SearchAgentTeam(context.Context, *SearchAgentTeamRequest) (*ListAgentTeam, error)
	// AgentTeam item
	ReadAgentTeam(context.Context, *ReadAgentTeamRequest) (*AgentTeam, error)
	// Update AgentTeam
	UpdateAgentTeam(context.Context, *UpdateAgentTeamRequest) (*AgentTeam, error)
	// Remove AgentTeam
	DeleteAgentTeam(context.Context, *DeleteAgentTeamRequest) (*AgentTeam, error)
}

// UnimplementedAgentTeamServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAgentTeamServiceServer struct {
}

func (*UnimplementedAgentTeamServiceServer) CreateAgentTeam(ctx context.Context, req *CreateAgentTeamRequest) (*AgentTeam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAgentTeam not implemented")
}
func (*UnimplementedAgentTeamServiceServer) SearchAgentTeam(ctx context.Context, req *SearchAgentTeamRequest) (*ListAgentTeam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAgentTeam not implemented")
}
func (*UnimplementedAgentTeamServiceServer) ReadAgentTeam(ctx context.Context, req *ReadAgentTeamRequest) (*AgentTeam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAgentTeam not implemented")
}
func (*UnimplementedAgentTeamServiceServer) UpdateAgentTeam(ctx context.Context, req *UpdateAgentTeamRequest) (*AgentTeam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgentTeam not implemented")
}
func (*UnimplementedAgentTeamServiceServer) DeleteAgentTeam(ctx context.Context, req *DeleteAgentTeamRequest) (*AgentTeam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAgentTeam not implemented")
}

func RegisterAgentTeamServiceServer(s *grpc.Server, srv AgentTeamServiceServer) {
	s.RegisterService(&_AgentTeamService_serviceDesc, srv)
}

func _AgentTeamService_CreateAgentTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentTeamServiceServer).CreateAgentTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentTeamService/CreateAgentTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentTeamServiceServer).CreateAgentTeam(ctx, req.(*CreateAgentTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentTeamService_SearchAgentTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAgentTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentTeamServiceServer).SearchAgentTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentTeamService/SearchAgentTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentTeamServiceServer).SearchAgentTeam(ctx, req.(*SearchAgentTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentTeamService_ReadAgentTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAgentTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentTeamServiceServer).ReadAgentTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentTeamService/ReadAgentTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentTeamServiceServer).ReadAgentTeam(ctx, req.(*ReadAgentTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentTeamService_UpdateAgentTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentTeamServiceServer).UpdateAgentTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentTeamService/UpdateAgentTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentTeamServiceServer).UpdateAgentTeam(ctx, req.(*UpdateAgentTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentTeamService_DeleteAgentTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentTeamServiceServer).DeleteAgentTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.AgentTeamService/DeleteAgentTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentTeamServiceServer).DeleteAgentTeam(ctx, req.(*DeleteAgentTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentTeamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "engine.AgentTeamService",
	HandlerType: (*AgentTeamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgentTeam",
			Handler:    _AgentTeamService_CreateAgentTeam_Handler,
		},
		{
			MethodName: "SearchAgentTeam",
			Handler:    _AgentTeamService_SearchAgentTeam_Handler,
		},
		{
			MethodName: "ReadAgentTeam",
			Handler:    _AgentTeamService_ReadAgentTeam_Handler,
		},
		{
			MethodName: "UpdateAgentTeam",
			Handler:    _AgentTeamService_UpdateAgentTeam_Handler,
		},
		{
			MethodName: "DeleteAgentTeam",
			Handler:    _AgentTeamService_DeleteAgentTeam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_team.proto",
}
