// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calendar.proto

package engine

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Calendar struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId             int64          `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	CreatedAt            int64          `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            *Lookup        `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt            int64          `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy            *Lookup        `protobuf:"bytes,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Name                 string         `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	StartAt              int64          `protobuf:"varint,8,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                int64          `protobuf:"varint,9,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Timezone             *Lookup        `protobuf:"bytes,10,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Description          string         `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	Accepts              []*AcceptOfDay `protobuf:"bytes,12,rep,name=accepts,proto3" json:"accepts,omitempty"`
	Excepts              []*ExceptDate  `protobuf:"bytes,13,rep,name=excepts,proto3" json:"excepts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Calendar) Reset()         { *m = Calendar{} }
func (m *Calendar) String() string { return proto.CompactTextString(m) }
func (*Calendar) ProtoMessage()    {}
func (*Calendar) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{0}
}

func (m *Calendar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calendar.Unmarshal(m, b)
}
func (m *Calendar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calendar.Marshal(b, m, deterministic)
}
func (m *Calendar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calendar.Merge(m, src)
}
func (m *Calendar) XXX_Size() int {
	return xxx_messageInfo_Calendar.Size(m)
}
func (m *Calendar) XXX_DiscardUnknown() {
	xxx_messageInfo_Calendar.DiscardUnknown(m)
}

var xxx_messageInfo_Calendar proto.InternalMessageInfo

func (m *Calendar) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Calendar) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

func (m *Calendar) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Calendar) GetCreatedBy() *Lookup {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *Calendar) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Calendar) GetUpdatedBy() *Lookup {
	if m != nil {
		return m.UpdatedBy
	}
	return nil
}

func (m *Calendar) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Calendar) GetStartAt() int64 {
	if m != nil {
		return m.StartAt
	}
	return 0
}

func (m *Calendar) GetEndAt() int64 {
	if m != nil {
		return m.EndAt
	}
	return 0
}

func (m *Calendar) GetTimezone() *Lookup {
	if m != nil {
		return m.Timezone
	}
	return nil
}

func (m *Calendar) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Calendar) GetAccepts() []*AcceptOfDay {
	if m != nil {
		return m.Accepts
	}
	return nil
}

func (m *Calendar) GetExcepts() []*ExceptDate {
	if m != nil {
		return m.Excepts
	}
	return nil
}

type ExceptDate struct {
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Date                 int64    `protobuf:"varint,4,opt,name=date,proto3" json:"date,omitempty"`
	Repeat               bool     `protobuf:"varint,5,opt,name=repeat,proto3" json:"repeat,omitempty"`
	Disabled             bool     `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExceptDate) Reset()         { *m = ExceptDate{} }
func (m *ExceptDate) String() string { return proto.CompactTextString(m) }
func (*ExceptDate) ProtoMessage()    {}
func (*ExceptDate) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{1}
}

func (m *ExceptDate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExceptDate.Unmarshal(m, b)
}
func (m *ExceptDate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExceptDate.Marshal(b, m, deterministic)
}
func (m *ExceptDate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExceptDate.Merge(m, src)
}
func (m *ExceptDate) XXX_Size() int {
	return xxx_messageInfo_ExceptDate.Size(m)
}
func (m *ExceptDate) XXX_DiscardUnknown() {
	xxx_messageInfo_ExceptDate.DiscardUnknown(m)
}

var xxx_messageInfo_ExceptDate proto.InternalMessageInfo

func (m *ExceptDate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExceptDate) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *ExceptDate) GetRepeat() bool {
	if m != nil {
		return m.Repeat
	}
	return false
}

func (m *ExceptDate) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type AcceptOfDay struct {
	Day                  int32    `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	StartTimeOfDay       int32    `protobuf:"varint,3,opt,name=start_time_of_day,json=startTimeOfDay,proto3" json:"start_time_of_day,omitempty"`
	EndTimeOfDay         int32    `protobuf:"varint,4,opt,name=end_time_of_day,json=endTimeOfDay,proto3" json:"end_time_of_day,omitempty"`
	Disabled             bool     `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptOfDay) Reset()         { *m = AcceptOfDay{} }
func (m *AcceptOfDay) String() string { return proto.CompactTextString(m) }
func (*AcceptOfDay) ProtoMessage()    {}
func (*AcceptOfDay) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{2}
}

func (m *AcceptOfDay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptOfDay.Unmarshal(m, b)
}
func (m *AcceptOfDay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptOfDay.Marshal(b, m, deterministic)
}
func (m *AcceptOfDay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptOfDay.Merge(m, src)
}
func (m *AcceptOfDay) XXX_Size() int {
	return xxx_messageInfo_AcceptOfDay.Size(m)
}
func (m *AcceptOfDay) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptOfDay.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptOfDay proto.InternalMessageInfo

func (m *AcceptOfDay) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *AcceptOfDay) GetStartTimeOfDay() int32 {
	if m != nil {
		return m.StartTimeOfDay
	}
	return 0
}

func (m *AcceptOfDay) GetEndTimeOfDay() int32 {
	if m != nil {
		return m.EndTimeOfDay
	}
	return 0
}

func (m *AcceptOfDay) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type ListCalendar struct {
	Items                []*Calendar `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListCalendar) Reset()         { *m = ListCalendar{} }
func (m *ListCalendar) String() string { return proto.CompactTextString(m) }
func (*ListCalendar) ProtoMessage()    {}
func (*ListCalendar) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{3}
}

func (m *ListCalendar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCalendar.Unmarshal(m, b)
}
func (m *ListCalendar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCalendar.Marshal(b, m, deterministic)
}
func (m *ListCalendar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCalendar.Merge(m, src)
}
func (m *ListCalendar) XXX_Size() int {
	return xxx_messageInfo_ListCalendar.Size(m)
}
func (m *ListCalendar) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCalendar.DiscardUnknown(m)
}

var xxx_messageInfo_ListCalendar proto.InternalMessageInfo

func (m *ListCalendar) GetItems() []*Calendar {
	if m != nil {
		return m.Items
	}
	return nil
}

type CreateCalendarRequest struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartAt              int64          `protobuf:"varint,2,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                int64          `protobuf:"varint,3,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Timezone             *Lookup        `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Description          string         `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Accepts              []*AcceptOfDay `protobuf:"bytes,6,rep,name=accepts,proto3" json:"accepts,omitempty"`
	Excepts              []*ExceptDate  `protobuf:"bytes,7,rep,name=excepts,proto3" json:"excepts,omitempty"`
	DomainId             int64          `protobuf:"varint,8,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateCalendarRequest) Reset()         { *m = CreateCalendarRequest{} }
func (m *CreateCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCalendarRequest) ProtoMessage()    {}
func (*CreateCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{4}
}

func (m *CreateCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCalendarRequest.Unmarshal(m, b)
}
func (m *CreateCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCalendarRequest.Marshal(b, m, deterministic)
}
func (m *CreateCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCalendarRequest.Merge(m, src)
}
func (m *CreateCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCalendarRequest.Size(m)
}
func (m *CreateCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCalendarRequest proto.InternalMessageInfo

func (m *CreateCalendarRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCalendarRequest) GetStartAt() int64 {
	if m != nil {
		return m.StartAt
	}
	return 0
}

func (m *CreateCalendarRequest) GetEndAt() int64 {
	if m != nil {
		return m.EndAt
	}
	return 0
}

func (m *CreateCalendarRequest) GetTimezone() *Lookup {
	if m != nil {
		return m.Timezone
	}
	return nil
}

func (m *CreateCalendarRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateCalendarRequest) GetAccepts() []*AcceptOfDay {
	if m != nil {
		return m.Accepts
	}
	return nil
}

func (m *CreateCalendarRequest) GetExcepts() []*ExceptDate {
	if m != nil {
		return m.Excepts
	}
	return nil
}

func (m *CreateCalendarRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type SearchCalendarRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	DomainId             int64    `protobuf:"varint,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchCalendarRequest) Reset()         { *m = SearchCalendarRequest{} }
func (m *SearchCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*SearchCalendarRequest) ProtoMessage()    {}
func (*SearchCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{5}
}

func (m *SearchCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchCalendarRequest.Unmarshal(m, b)
}
func (m *SearchCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchCalendarRequest.Marshal(b, m, deterministic)
}
func (m *SearchCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchCalendarRequest.Merge(m, src)
}
func (m *SearchCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_SearchCalendarRequest.Size(m)
}
func (m *SearchCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchCalendarRequest proto.InternalMessageInfo

func (m *SearchCalendarRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchCalendarRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchCalendarRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type ReadCalendarRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId             int64    `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadCalendarRequest) Reset()         { *m = ReadCalendarRequest{} }
func (m *ReadCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*ReadCalendarRequest) ProtoMessage()    {}
func (*ReadCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{6}
}

func (m *ReadCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadCalendarRequest.Unmarshal(m, b)
}
func (m *ReadCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadCalendarRequest.Marshal(b, m, deterministic)
}
func (m *ReadCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadCalendarRequest.Merge(m, src)
}
func (m *ReadCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_ReadCalendarRequest.Size(m)
}
func (m *ReadCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadCalendarRequest proto.InternalMessageInfo

func (m *ReadCalendarRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReadCalendarRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type DeleteCalendarRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId             int64    `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCalendarRequest) Reset()         { *m = DeleteCalendarRequest{} }
func (m *DeleteCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCalendarRequest) ProtoMessage()    {}
func (*DeleteCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{7}
}

func (m *DeleteCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCalendarRequest.Unmarshal(m, b)
}
func (m *DeleteCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCalendarRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCalendarRequest.Merge(m, src)
}
func (m *DeleteCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCalendarRequest.Size(m)
}
func (m *DeleteCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCalendarRequest proto.InternalMessageInfo

func (m *DeleteCalendarRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteCalendarRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type UpdateCalendarRequest struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartAt              int64          `protobuf:"varint,3,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                int64          `protobuf:"varint,4,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Timezone             *Lookup        `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Description          string         `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Accepts              []*AcceptOfDay `protobuf:"bytes,7,rep,name=accepts,proto3" json:"accepts,omitempty"`
	Excepts              []*ExceptDate  `protobuf:"bytes,8,rep,name=excepts,proto3" json:"excepts,omitempty"`
	DomainId             int64          `protobuf:"varint,9,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateCalendarRequest) Reset()         { *m = UpdateCalendarRequest{} }
func (m *UpdateCalendarRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCalendarRequest) ProtoMessage()    {}
func (*UpdateCalendarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{8}
}

func (m *UpdateCalendarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCalendarRequest.Unmarshal(m, b)
}
func (m *UpdateCalendarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCalendarRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCalendarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCalendarRequest.Merge(m, src)
}
func (m *UpdateCalendarRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCalendarRequest.Size(m)
}
func (m *UpdateCalendarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCalendarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCalendarRequest proto.InternalMessageInfo

func (m *UpdateCalendarRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateCalendarRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateCalendarRequest) GetStartAt() int64 {
	if m != nil {
		return m.StartAt
	}
	return 0
}

func (m *UpdateCalendarRequest) GetEndAt() int64 {
	if m != nil {
		return m.EndAt
	}
	return 0
}

func (m *UpdateCalendarRequest) GetTimezone() *Lookup {
	if m != nil {
		return m.Timezone
	}
	return nil
}

func (m *UpdateCalendarRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateCalendarRequest) GetAccepts() []*AcceptOfDay {
	if m != nil {
		return m.Accepts
	}
	return nil
}

func (m *UpdateCalendarRequest) GetExcepts() []*ExceptDate {
	if m != nil {
		return m.Excepts
	}
	return nil
}

func (m *UpdateCalendarRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type SearchTimezonesRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchTimezonesRequest) Reset()         { *m = SearchTimezonesRequest{} }
func (m *SearchTimezonesRequest) String() string { return proto.CompactTextString(m) }
func (*SearchTimezonesRequest) ProtoMessage()    {}
func (*SearchTimezonesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{9}
}

func (m *SearchTimezonesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchTimezonesRequest.Unmarshal(m, b)
}
func (m *SearchTimezonesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchTimezonesRequest.Marshal(b, m, deterministic)
}
func (m *SearchTimezonesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchTimezonesRequest.Merge(m, src)
}
func (m *SearchTimezonesRequest) XXX_Size() int {
	return xxx_messageInfo_SearchTimezonesRequest.Size(m)
}
func (m *SearchTimezonesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchTimezonesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchTimezonesRequest proto.InternalMessageInfo

func (m *SearchTimezonesRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchTimezonesRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ListTimezoneResponse struct {
	Items                []*Timezone `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListTimezoneResponse) Reset()         { *m = ListTimezoneResponse{} }
func (m *ListTimezoneResponse) String() string { return proto.CompactTextString(m) }
func (*ListTimezoneResponse) ProtoMessage()    {}
func (*ListTimezoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{10}
}

func (m *ListTimezoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTimezoneResponse.Unmarshal(m, b)
}
func (m *ListTimezoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTimezoneResponse.Marshal(b, m, deterministic)
}
func (m *ListTimezoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTimezoneResponse.Merge(m, src)
}
func (m *ListTimezoneResponse) XXX_Size() int {
	return xxx_messageInfo_ListTimezoneResponse.Size(m)
}
func (m *ListTimezoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTimezoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTimezoneResponse proto.InternalMessageInfo

func (m *ListTimezoneResponse) GetItems() []*Timezone {
	if m != nil {
		return m.Items
	}
	return nil
}

type Timezone struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Offset               string   `protobuf:"bytes,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timezone) Reset()         { *m = Timezone{} }
func (m *Timezone) String() string { return proto.CompactTextString(m) }
func (*Timezone) ProtoMessage()    {}
func (*Timezone) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{11}
}

func (m *Timezone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timezone.Unmarshal(m, b)
}
func (m *Timezone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timezone.Marshal(b, m, deterministic)
}
func (m *Timezone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timezone.Merge(m, src)
}
func (m *Timezone) XXX_Size() int {
	return xxx_messageInfo_Timezone.Size(m)
}
func (m *Timezone) XXX_DiscardUnknown() {
	xxx_messageInfo_Timezone.DiscardUnknown(m)
}

var xxx_messageInfo_Timezone proto.InternalMessageInfo

func (m *Timezone) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Timezone) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Timezone) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func init() {
	proto.RegisterType((*Calendar)(nil), "engine.Calendar")
	proto.RegisterType((*ExceptDate)(nil), "engine.ExceptDate")
	proto.RegisterType((*AcceptOfDay)(nil), "engine.AcceptOfDay")
	proto.RegisterType((*ListCalendar)(nil), "engine.ListCalendar")
	proto.RegisterType((*CreateCalendarRequest)(nil), "engine.CreateCalendarRequest")
	proto.RegisterType((*SearchCalendarRequest)(nil), "engine.SearchCalendarRequest")
	proto.RegisterType((*ReadCalendarRequest)(nil), "engine.ReadCalendarRequest")
	proto.RegisterType((*DeleteCalendarRequest)(nil), "engine.DeleteCalendarRequest")
	proto.RegisterType((*UpdateCalendarRequest)(nil), "engine.UpdateCalendarRequest")
	proto.RegisterType((*SearchTimezonesRequest)(nil), "engine.SearchTimezonesRequest")
	proto.RegisterType((*ListTimezoneResponse)(nil), "engine.ListTimezoneResponse")
	proto.RegisterType((*Timezone)(nil), "engine.Timezone")
}

func init() { proto.RegisterFile("calendar.proto", fileDescriptor_e3d25d49f056cdb2) }

var fileDescriptor_e3d25d49f056cdb2 = []byte{
	// 832 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcd, 0x8e, 0xe3, 0x44,
	0x10, 0x96, 0xed, 0xd8, 0x71, 0x2a, 0xc1, 0xd9, 0xed, 0x9d, 0x0c, 0xc6, 0x3b, 0x8b, 0x22, 0x4b,
	0xa0, 0x61, 0xc4, 0xce, 0x48, 0x83, 0xc4, 0x81, 0x03, 0x62, 0x66, 0x03, 0x12, 0xd2, 0x4a, 0x48,
	0xde, 0x05, 0x01, 0x02, 0x45, 0x1d, 0xbb, 0x92, 0x6d, 0x91, 0xd8, 0xc6, 0xdd, 0x83, 0xc8, 0x22,
	0x2e, 0xdc, 0x39, 0xf1, 0x0c, 0x3c, 0x02, 0x6f, 0xc0, 0x81, 0x3b, 0xaf, 0xc0, 0x83, 0x20, 0xb7,
	0x7f, 0x62, 0x7b, 0xec, 0x9d, 0xf5, 0xad, 0xbb, 0xaa, 0xfa, 0xeb, 0xf2, 0xd7, 0xdf, 0x57, 0x09,
	0x58, 0x3e, 0xdd, 0x62, 0x18, 0xd0, 0xe4, 0x3c, 0x4e, 0x22, 0x11, 0x11, 0x03, 0xc3, 0x0d, 0x0b,
	0xd1, 0x19, 0xfb, 0x51, 0xc8, 0x45, 0x16, 0x74, 0x4e, 0x36, 0x51, 0xb4, 0xd9, 0xe2, 0x05, 0x8d,
	0xd9, 0x05, 0x0d, 0xc3, 0x48, 0x50, 0xc1, 0xa2, 0x90, 0x67, 0x59, 0xf7, 0x6f, 0x0d, 0xcc, 0x27,
	0x39, 0x0a, 0xb1, 0x40, 0x65, 0x81, 0xad, 0xcc, 0x95, 0x53, 0xcd, 0x53, 0x59, 0x40, 0x1e, 0xc2,
	0x28, 0x88, 0x76, 0x94, 0x85, 0x4b, 0x16, 0xd8, 0xaa, 0x0c, 0x9b, 0x59, 0xe0, 0xf3, 0x80, 0x3c,
	0x02, 0xf0, 0x13, 0xa4, 0x02, 0x83, 0x25, 0x15, 0xb6, 0x26, 0xb3, 0xa3, 0x3c, 0x72, 0x25, 0xc8,
	0xe3, 0x43, 0x7a, 0xb5, 0xb7, 0x07, 0x73, 0xe5, 0x74, 0x7c, 0x69, 0x9d, 0x67, 0x0d, 0x9e, 0x3f,
	0x8d, 0xa2, 0x1f, 0x6e, 0xe2, 0xb2, 0xfc, 0x7a, 0x9f, 0xa2, 0xdd, 0xc4, 0x41, 0x81, 0xa6, 0x67,
	0x68, 0x79, 0x24, 0x43, 0x2b, 0xd2, 0xab, 0xbd, 0x6d, 0xb4, 0xa3, 0xe5, 0x15, 0xd7, 0x7b, 0x42,
	0x60, 0x10, 0xd2, 0x1d, 0xda, 0xc3, 0xb9, 0x72, 0x3a, 0xf2, 0xe4, 0x9a, 0xbc, 0x05, 0x26, 0x17,
	0x34, 0x11, 0x29, 0xbe, 0x29, 0xf1, 0x87, 0x72, 0x7f, 0x25, 0xc8, 0x0c, 0x0c, 0x0c, 0xe5, 0xc5,
	0x23, 0x99, 0xd0, 0x31, 0x4c, 0x2f, 0x3d, 0x03, 0x53, 0xb0, 0x1d, 0xbe, 0x8c, 0x42, 0xb4, 0xa1,
	0xf5, 0xca, 0x32, 0x4f, 0xe6, 0x30, 0x0e, 0x90, 0xfb, 0x09, 0x8b, 0x53, 0x76, 0xed, 0xb1, 0xbc,
	0xb8, 0x1a, 0x22, 0x8f, 0x61, 0x48, 0x7d, 0x1f, 0x63, 0xc1, 0xed, 0xc9, 0x5c, 0x3b, 0x1d, 0x5f,
	0x3e, 0x28, 0xc0, 0xae, 0x64, 0xf8, 0x8b, 0xf5, 0x82, 0xee, 0xbd, 0xa2, 0x86, 0xbc, 0x0f, 0x43,
	0xfc, 0x39, 0x2b, 0x7f, 0x43, 0x96, 0x93, 0xa2, 0xfc, 0x53, 0x19, 0x5e, 0x50, 0x81, 0x5e, 0x51,
	0xe2, 0xbe, 0x00, 0x38, 0x84, 0xcb, 0xcf, 0xd7, 0x2a, 0x9f, 0x4f, 0x60, 0x90, 0xb2, 0x23, 0x5f,
	0x42, 0xf3, 0xe4, 0x9a, 0x1c, 0x83, 0x91, 0x60, 0x8c, 0x39, 0xe1, 0xa6, 0x97, 0xef, 0x88, 0x03,
	0x66, 0xc0, 0x38, 0x5d, 0x6d, 0x31, 0x90, 0x5c, 0x9b, 0x5e, 0xb9, 0x77, 0x7f, 0x57, 0x60, 0x5c,
	0x69, 0x98, 0xdc, 0x03, 0x2d, 0xa0, 0x7b, 0xa9, 0x0e, 0xdd, 0x4b, 0x97, 0xe4, 0x3d, 0xb8, 0x9f,
	0x11, 0x9d, 0x92, 0xb3, 0x8c, 0xd6, 0xcb, 0x34, 0xaf, 0xc9, 0xbc, 0x25, 0x13, 0xcf, 0xd9, 0x0e,
	0xb3, 0xc3, 0xef, 0xc0, 0x34, 0x25, 0xbe, 0x5a, 0x38, 0x90, 0x85, 0x13, 0x0c, 0x83, 0x43, 0x59,
	0xb5, 0x1f, 0xbd, 0xd1, 0xcf, 0x87, 0x30, 0x79, 0xca, 0xb8, 0x28, 0x35, 0xfc, 0x2e, 0xe8, 0x4c,
	0xe0, 0x8e, 0xdb, 0x8a, 0x64, 0xed, 0x5e, 0xc1, 0x5a, 0x51, 0xe0, 0x65, 0x69, 0xf7, 0x4f, 0x15,
	0x66, 0x4f, 0xa4, 0xfc, 0xca, 0x0c, 0xfe, 0x78, 0x83, 0x5c, 0x94, 0xec, 0x29, 0x1d, 0xe2, 0x51,
	0xbb, 0xc4, 0xa3, 0x75, 0x89, 0x67, 0xd0, 0x4f, 0x3c, 0xfa, 0x2b, 0xc5, 0x63, 0xf4, 0x13, 0xcf,
	0xf0, 0x4e, 0xf1, 0xd4, 0x6d, 0x6e, 0xd6, 0x6d, 0xee, 0x7e, 0x07, 0xb3, 0x67, 0x48, 0x13, 0xff,
	0x45, 0x0b, 0x4d, 0x31, 0xdd, 0x64, 0x34, 0xe9, 0x9e, 0x5c, 0xa7, 0x31, 0xce, 0x5e, 0x62, 0xae,
	0x06, 0xb9, 0xae, 0xa3, 0x6b, 0x0d, 0xf4, 0x6b, 0x78, 0xe0, 0x21, 0x0d, 0x9a, 0xd8, 0x7d, 0x06,
	0x91, 0xbb, 0x80, 0xd9, 0x02, 0xb7, 0x78, 0xfb, 0x21, 0x7b, 0xa1, 0xfc, 0xa5, 0xc2, 0xec, 0x4b,
	0x39, 0x40, 0xee, 0x82, 0x29, 0xf4, 0xa1, 0x76, 0xe8, 0x43, 0xeb, 0xd2, 0xc7, 0xa0, 0x4b, 0x1f,
	0x7a, 0x3f, 0x7d, 0x18, 0xaf, 0xd4, 0xc7, 0xb0, 0x9f, 0x3e, 0xcc, 0x9e, 0xfa, 0x18, 0x35, 0x78,
	0xfb, 0x04, 0x8e, 0x33, 0x7d, 0x3c, 0xcf, 0xbb, 0xe5, 0x3d, 0x05, 0xe2, 0x7e, 0x0c, 0x47, 0xa9,
	0x83, 0x8b, 0xf3, 0x1e, 0xf2, 0x38, 0x0a, 0x39, 0x76, 0x3a, 0xb9, 0x2c, 0xcc, 0x9d, 0xfc, 0x19,
	0x98, 0x45, 0xe8, 0xb5, 0xde, 0xea, 0x18, 0x8c, 0x68, 0xbd, 0xe6, 0x28, 0xf2, 0xf9, 0x98, 0xef,
	0x2e, 0xff, 0x19, 0xc0, 0xb4, 0x78, 0xfb, 0x67, 0x98, 0xfc, 0xc4, 0x7c, 0x24, 0x5f, 0x83, 0x55,
	0x1f, 0x12, 0xe4, 0x51, 0x39, 0x50, 0xda, 0x86, 0x87, 0x73, 0x6b, 0xde, 0xb8, 0xb3, 0xdf, 0xfe,
	0xfd, 0xef, 0x0f, 0x75, 0xea, 0xc2, 0x45, 0xf1, 0x6b, 0xcd, 0x3f, 0x52, 0xce, 0xc8, 0x37, 0x60,
	0xd5, 0x7d, 0x75, 0x40, 0x6e, 0xf5, 0x9b, 0x73, 0x54, 0xca, 0xa3, 0x32, 0xee, 0x5c, 0x22, 0xd1,
	0x27, 0xa4, 0x82, 0x4e, 0xbe, 0x82, 0x49, 0xd5, 0x54, 0xe4, 0x61, 0x71, 0xb2, 0xc5, 0x6a, 0x2d,
	0x0d, 0xbf, 0x29, 0x21, 0xef, 0x93, 0xe9, 0x01, 0xf2, 0xe2, 0x17, 0x16, 0xfc, 0x4a, 0xbe, 0x07,
	0xab, 0xee, 0x90, 0x43, 0xcb, 0xad, 0xce, 0x69, 0xc1, 0x76, 0x24, 0xf6, 0x91, 0xd3, 0xc4, 0x4e,
	0x19, 0xf9, 0x16, 0xac, 0xba, 0x8f, 0x0f, 0xf0, 0xad, 0xfe, 0xee, 0x6e, 0xfd, 0xec, 0x56, 0xeb,
	0x3b, 0x98, 0x36, 0x54, 0x4a, 0xde, 0xae, 0xd3, 0xdd, 0x94, 0xaf, 0x73, 0x52, 0xe5, 0xbb, 0x29,
	0x4e, 0xf7, 0x44, 0xde, 0x74, 0x4c, 0x8e, 0x2a, 0x37, 0x15, 0x7e, 0xe5, 0x2b, 0x43, 0xfe, 0xb9,
	0xfa, 0xe0, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xae, 0xc7, 0xe1, 0xa1, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalendarServiceClient is the client API for CalendarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalendarServiceClient interface {
	// Create calendar
	CreateCalendar(ctx context.Context, in *CreateCalendarRequest, opts ...grpc.CallOption) (*Calendar, error)
	// List of calendar
	SearchCalendar(ctx context.Context, in *SearchCalendarRequest, opts ...grpc.CallOption) (*ListCalendar, error)
	// Calendar item
	ReadCalendar(ctx context.Context, in *ReadCalendarRequest, opts ...grpc.CallOption) (*Calendar, error)
	// Update calendar
	UpdateCalendar(ctx context.Context, in *UpdateCalendarRequest, opts ...grpc.CallOption) (*Calendar, error)
	// Remove calendar
	DeleteCalendar(ctx context.Context, in *DeleteCalendarRequest, opts ...grpc.CallOption) (*Calendar, error)
	// List timezones
	SearchTimezones(ctx context.Context, in *SearchTimezonesRequest, opts ...grpc.CallOption) (*ListTimezoneResponse, error)
}

type calendarServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalendarServiceClient(cc *grpc.ClientConn) CalendarServiceClient {
	return &calendarServiceClient{cc}
}

func (c *calendarServiceClient) CreateCalendar(ctx context.Context, in *CreateCalendarRequest, opts ...grpc.CallOption) (*Calendar, error) {
	out := new(Calendar)
	err := c.cc.Invoke(ctx, "/engine.CalendarService/CreateCalendar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) SearchCalendar(ctx context.Context, in *SearchCalendarRequest, opts ...grpc.CallOption) (*ListCalendar, error) {
	out := new(ListCalendar)
	err := c.cc.Invoke(ctx, "/engine.CalendarService/SearchCalendar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) ReadCalendar(ctx context.Context, in *ReadCalendarRequest, opts ...grpc.CallOption) (*Calendar, error) {
	out := new(Calendar)
	err := c.cc.Invoke(ctx, "/engine.CalendarService/ReadCalendar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) UpdateCalendar(ctx context.Context, in *UpdateCalendarRequest, opts ...grpc.CallOption) (*Calendar, error) {
	out := new(Calendar)
	err := c.cc.Invoke(ctx, "/engine.CalendarService/UpdateCalendar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) DeleteCalendar(ctx context.Context, in *DeleteCalendarRequest, opts ...grpc.CallOption) (*Calendar, error) {
	out := new(Calendar)
	err := c.cc.Invoke(ctx, "/engine.CalendarService/DeleteCalendar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) SearchTimezones(ctx context.Context, in *SearchTimezonesRequest, opts ...grpc.CallOption) (*ListTimezoneResponse, error) {
	out := new(ListTimezoneResponse)
	err := c.cc.Invoke(ctx, "/engine.CalendarService/SearchTimezones", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalendarServiceServer is the server API for CalendarService service.
type CalendarServiceServer interface {
	// Create calendar
	CreateCalendar(context.Context, *CreateCalendarRequest) (*Calendar, error)
	// List of calendar
	SearchCalendar(context.Context, *SearchCalendarRequest) (*ListCalendar, error)
	// Calendar item
	ReadCalendar(context.Context, *ReadCalendarRequest) (*Calendar, error)
	// Update calendar
	UpdateCalendar(context.Context, *UpdateCalendarRequest) (*Calendar, error)
	// Remove calendar
	DeleteCalendar(context.Context, *DeleteCalendarRequest) (*Calendar, error)
	// List timezones
	SearchTimezones(context.Context, *SearchTimezonesRequest) (*ListTimezoneResponse, error)
}

// UnimplementedCalendarServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalendarServiceServer struct {
}

func (*UnimplementedCalendarServiceServer) CreateCalendar(ctx context.Context, req *CreateCalendarRequest) (*Calendar, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCalendar not implemented")
}
func (*UnimplementedCalendarServiceServer) SearchCalendar(ctx context.Context, req *SearchCalendarRequest) (*ListCalendar, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCalendar not implemented")
}
func (*UnimplementedCalendarServiceServer) ReadCalendar(ctx context.Context, req *ReadCalendarRequest) (*Calendar, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadCalendar not implemented")
}
func (*UnimplementedCalendarServiceServer) UpdateCalendar(ctx context.Context, req *UpdateCalendarRequest) (*Calendar, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCalendar not implemented")
}
func (*UnimplementedCalendarServiceServer) DeleteCalendar(ctx context.Context, req *DeleteCalendarRequest) (*Calendar, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCalendar not implemented")
}
func (*UnimplementedCalendarServiceServer) SearchTimezones(ctx context.Context, req *SearchTimezonesRequest) (*ListTimezoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTimezones not implemented")
}

func RegisterCalendarServiceServer(s *grpc.Server, srv CalendarServiceServer) {
	s.RegisterService(&_CalendarService_serviceDesc, srv)
}

func _CalendarService_CreateCalendar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCalendarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).CreateCalendar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CalendarService/CreateCalendar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).CreateCalendar(ctx, req.(*CreateCalendarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_SearchCalendar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCalendarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).SearchCalendar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CalendarService/SearchCalendar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).SearchCalendar(ctx, req.(*SearchCalendarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_ReadCalendar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCalendarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ReadCalendar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CalendarService/ReadCalendar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ReadCalendar(ctx, req.(*ReadCalendarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_UpdateCalendar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCalendarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).UpdateCalendar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CalendarService/UpdateCalendar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).UpdateCalendar(ctx, req.(*UpdateCalendarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_DeleteCalendar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCalendarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).DeleteCalendar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CalendarService/DeleteCalendar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).DeleteCalendar(ctx, req.(*DeleteCalendarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_SearchTimezones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTimezonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).SearchTimezones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CalendarService/SearchTimezones",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).SearchTimezones(ctx, req.(*SearchTimezonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalendarService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "engine.CalendarService",
	HandlerType: (*CalendarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCalendar",
			Handler:    _CalendarService_CreateCalendar_Handler,
		},
		{
			MethodName: "SearchCalendar",
			Handler:    _CalendarService_SearchCalendar_Handler,
		},
		{
			MethodName: "ReadCalendar",
			Handler:    _CalendarService_ReadCalendar_Handler,
		},
		{
			MethodName: "UpdateCalendar",
			Handler:    _CalendarService_UpdateCalendar_Handler,
		},
		{
			MethodName: "DeleteCalendar",
			Handler:    _CalendarService_DeleteCalendar_Handler,
		},
		{
			MethodName: "SearchTimezones",
			Handler:    _CalendarService_SearchTimezones_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calendar.proto",
}
