// Code generated by protoc-gen-go. DO NOT EDIT.
// source: call.proto

package engine

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchHistoryCallRequest struct {
	Page                 int32          `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32          `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt            *FilterBetween `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UserId               []int64        `protobuf:"varint,4,rep,packed,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AgentId              []int64        `protobuf:"varint,5,rep,packed,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	QueueId              []int64        `protobuf:"varint,6,rep,packed,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	TeamId               []int64        `protobuf:"varint,7,rep,packed,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	MemberId             []int64        `protobuf:"varint,8,rep,packed,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	GatewayId            []int64        `protobuf:"varint,9,rep,packed,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Number               string         `protobuf:"bytes,10,opt,name=number,proto3" json:"number,omitempty"`
	Duration             *FilterBetween `protobuf:"bytes,11,opt,name=duration,proto3" json:"duration,omitempty"`
	SkipParent           bool           `protobuf:"varint,12,opt,name=skip_parent,json=skipParent,proto3" json:"skip_parent,omitempty"`
	ParentId             string         `protobuf:"bytes,13,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Cause                string         `protobuf:"bytes,14,opt,name=cause,proto3" json:"cause,omitempty"`
	Fields               []string       `protobuf:"bytes,15,rep,name=fields,proto3" json:"fields,omitempty"`
	Sort                 string         `protobuf:"bytes,16,opt,name=sort,proto3" json:"sort,omitempty"`
	DomainId             int64          `protobuf:"varint,17,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SearchHistoryCallRequest) Reset()         { *m = SearchHistoryCallRequest{} }
func (m *SearchHistoryCallRequest) String() string { return proto.CompactTextString(m) }
func (*SearchHistoryCallRequest) ProtoMessage()    {}
func (*SearchHistoryCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{0}
}

func (m *SearchHistoryCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchHistoryCallRequest.Unmarshal(m, b)
}
func (m *SearchHistoryCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchHistoryCallRequest.Marshal(b, m, deterministic)
}
func (m *SearchHistoryCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchHistoryCallRequest.Merge(m, src)
}
func (m *SearchHistoryCallRequest) XXX_Size() int {
	return xxx_messageInfo_SearchHistoryCallRequest.Size(m)
}
func (m *SearchHistoryCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchHistoryCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchHistoryCallRequest proto.InternalMessageInfo

func (m *SearchHistoryCallRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchHistoryCallRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchHistoryCallRequest) GetCreatedAt() *FilterBetween {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *SearchHistoryCallRequest) GetUserId() []int64 {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *SearchHistoryCallRequest) GetAgentId() []int64 {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *SearchHistoryCallRequest) GetQueueId() []int64 {
	if m != nil {
		return m.QueueId
	}
	return nil
}

func (m *SearchHistoryCallRequest) GetTeamId() []int64 {
	if m != nil {
		return m.TeamId
	}
	return nil
}

func (m *SearchHistoryCallRequest) GetMemberId() []int64 {
	if m != nil {
		return m.MemberId
	}
	return nil
}

func (m *SearchHistoryCallRequest) GetGatewayId() []int64 {
	if m != nil {
		return m.GatewayId
	}
	return nil
}

func (m *SearchHistoryCallRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *SearchHistoryCallRequest) GetDuration() *FilterBetween {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *SearchHistoryCallRequest) GetSkipParent() bool {
	if m != nil {
		return m.SkipParent
	}
	return false
}

func (m *SearchHistoryCallRequest) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *SearchHistoryCallRequest) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *SearchHistoryCallRequest) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *SearchHistoryCallRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *SearchHistoryCallRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type ListHistoryCall struct {
	Next                 bool           `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items                []*HistoryCall `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListHistoryCall) Reset()         { *m = ListHistoryCall{} }
func (m *ListHistoryCall) String() string { return proto.CompactTextString(m) }
func (*ListHistoryCall) ProtoMessage()    {}
func (*ListHistoryCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{1}
}

func (m *ListHistoryCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHistoryCall.Unmarshal(m, b)
}
func (m *ListHistoryCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHistoryCall.Marshal(b, m, deterministic)
}
func (m *ListHistoryCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHistoryCall.Merge(m, src)
}
func (m *ListHistoryCall) XXX_Size() int {
	return xxx_messageInfo_ListHistoryCall.Size(m)
}
func (m *ListHistoryCall) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHistoryCall.DiscardUnknown(m)
}

var xxx_messageInfo_ListHistoryCall proto.InternalMessageInfo

func (m *ListHistoryCall) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *ListHistoryCall) GetItems() []*HistoryCall {
	if m != nil {
		return m.Items
	}
	return nil
}

type CallFile struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	MimeType             string   `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallFile) Reset()         { *m = CallFile{} }
func (m *CallFile) String() string { return proto.CompactTextString(m) }
func (*CallFile) ProtoMessage()    {}
func (*CallFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{2}
}

func (m *CallFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallFile.Unmarshal(m, b)
}
func (m *CallFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallFile.Marshal(b, m, deterministic)
}
func (m *CallFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallFile.Merge(m, src)
}
func (m *CallFile) XXX_Size() int {
	return xxx_messageInfo_CallFile.Size(m)
}
func (m *CallFile) XXX_DiscardUnknown() {
	xxx_messageInfo_CallFile.DiscardUnknown(m)
}

var xxx_messageInfo_CallFile proto.InternalMessageInfo

func (m *CallFile) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CallFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CallFile) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CallFile) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

type HistoryCall struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId                string            `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Type                 string            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	ParentId             string            `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	User                 *Lookup           `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Gateway              *Lookup           `protobuf:"bytes,6,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Direction            string            `protobuf:"bytes,7,opt,name=direction,proto3" json:"direction,omitempty"`
	Destination          string            `protobuf:"bytes,8,opt,name=destination,proto3" json:"destination,omitempty"`
	From                 *Endpoint         `protobuf:"bytes,9,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Endpoint         `protobuf:"bytes,10,opt,name=to,proto3" json:"to,omitempty"`
	Variables            map[string]string `protobuf:"bytes,11,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedAt            int64             `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	AnsweredAt           int64             `protobuf:"varint,13,opt,name=answered_at,json=answeredAt,proto3" json:"answered_at,omitempty"`
	BridgedAt            int64             `protobuf:"varint,14,opt,name=bridged_at,json=bridgedAt,proto3" json:"bridged_at,omitempty"`
	HangupAt             int64             `protobuf:"varint,15,opt,name=hangup_at,json=hangupAt,proto3" json:"hangup_at,omitempty"`
	HangupBy             string            `protobuf:"bytes,16,opt,name=hangup_by,json=hangupBy,proto3" json:"hangup_by,omitempty"`
	Cause                string            `protobuf:"bytes,17,opt,name=cause,proto3" json:"cause,omitempty"`
	Duration             int32             `protobuf:"varint,18,opt,name=duration,proto3" json:"duration,omitempty"`
	HoldSec              int32             `protobuf:"varint,19,opt,name=hold_sec,json=holdSec,proto3" json:"hold_sec,omitempty"`
	WaitSec              int32             `protobuf:"varint,20,opt,name=wait_sec,json=waitSec,proto3" json:"wait_sec,omitempty"`
	BillSec              int32             `protobuf:"varint,21,opt,name=bill_sec,json=billSec,proto3" json:"bill_sec,omitempty"`
	SipCode              int32             `protobuf:"varint,22,opt,name=sip_code,json=sipCode,proto3" json:"sip_code,omitempty"`
	Files                []*CallFile       `protobuf:"bytes,23,rep,name=files,proto3" json:"files,omitempty"`
	Queue                *Lookup           `protobuf:"bytes,24,opt,name=queue,proto3" json:"queue,omitempty"`
	Member               *Lookup           `protobuf:"bytes,25,opt,name=member,proto3" json:"member,omitempty"`
	Team                 *Lookup           `protobuf:"bytes,26,opt,name=team,proto3" json:"team,omitempty"`
	Agent                *Lookup           `protobuf:"bytes,27,opt,name=agent,proto3" json:"agent,omitempty"`
	JoinedAt             int64             `protobuf:"varint,28,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LeavingAt            int64             `protobuf:"varint,29,opt,name=leaving_at,json=leavingAt,proto3" json:"leaving_at,omitempty"`
	ReportingAt          int64             `protobuf:"varint,30,opt,name=reporting_at,json=reportingAt,proto3" json:"reporting_at,omitempty"`
	QueueBridgedAt       int64             `protobuf:"varint,31,opt,name=queue_bridged_at,json=queueBridgedAt,proto3" json:"queue_bridged_at,omitempty"`
	QueueWaitSec         int32             `protobuf:"varint,32,opt,name=queue_wait_sec,json=queueWaitSec,proto3" json:"queue_wait_sec,omitempty"`
	QueueDurationSec     int32             `protobuf:"varint,33,opt,name=queue_duration_sec,json=queueDurationSec,proto3" json:"queue_duration_sec,omitempty"`
	Result               string            `protobuf:"bytes,34,opt,name=result,proto3" json:"result,omitempty"`
	ReportingSec         int32             `protobuf:"varint,35,opt,name=reporting_sec,json=reportingSec,proto3" json:"reporting_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HistoryCall) Reset()         { *m = HistoryCall{} }
func (m *HistoryCall) String() string { return proto.CompactTextString(m) }
func (*HistoryCall) ProtoMessage()    {}
func (*HistoryCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{3}
}

func (m *HistoryCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryCall.Unmarshal(m, b)
}
func (m *HistoryCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryCall.Marshal(b, m, deterministic)
}
func (m *HistoryCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryCall.Merge(m, src)
}
func (m *HistoryCall) XXX_Size() int {
	return xxx_messageInfo_HistoryCall.Size(m)
}
func (m *HistoryCall) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryCall.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryCall proto.InternalMessageInfo

func (m *HistoryCall) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HistoryCall) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *HistoryCall) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *HistoryCall) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *HistoryCall) GetUser() *Lookup {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *HistoryCall) GetGateway() *Lookup {
	if m != nil {
		return m.Gateway
	}
	return nil
}

func (m *HistoryCall) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *HistoryCall) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *HistoryCall) GetFrom() *Endpoint {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *HistoryCall) GetTo() *Endpoint {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *HistoryCall) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *HistoryCall) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *HistoryCall) GetAnsweredAt() int64 {
	if m != nil {
		return m.AnsweredAt
	}
	return 0
}

func (m *HistoryCall) GetBridgedAt() int64 {
	if m != nil {
		return m.BridgedAt
	}
	return 0
}

func (m *HistoryCall) GetHangupAt() int64 {
	if m != nil {
		return m.HangupAt
	}
	return 0
}

func (m *HistoryCall) GetHangupBy() string {
	if m != nil {
		return m.HangupBy
	}
	return ""
}

func (m *HistoryCall) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *HistoryCall) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *HistoryCall) GetHoldSec() int32 {
	if m != nil {
		return m.HoldSec
	}
	return 0
}

func (m *HistoryCall) GetWaitSec() int32 {
	if m != nil {
		return m.WaitSec
	}
	return 0
}

func (m *HistoryCall) GetBillSec() int32 {
	if m != nil {
		return m.BillSec
	}
	return 0
}

func (m *HistoryCall) GetSipCode() int32 {
	if m != nil {
		return m.SipCode
	}
	return 0
}

func (m *HistoryCall) GetFiles() []*CallFile {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *HistoryCall) GetQueue() *Lookup {
	if m != nil {
		return m.Queue
	}
	return nil
}

func (m *HistoryCall) GetMember() *Lookup {
	if m != nil {
		return m.Member
	}
	return nil
}

func (m *HistoryCall) GetTeam() *Lookup {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *HistoryCall) GetAgent() *Lookup {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *HistoryCall) GetJoinedAt() int64 {
	if m != nil {
		return m.JoinedAt
	}
	return 0
}

func (m *HistoryCall) GetLeavingAt() int64 {
	if m != nil {
		return m.LeavingAt
	}
	return 0
}

func (m *HistoryCall) GetReportingAt() int64 {
	if m != nil {
		return m.ReportingAt
	}
	return 0
}

func (m *HistoryCall) GetQueueBridgedAt() int64 {
	if m != nil {
		return m.QueueBridgedAt
	}
	return 0
}

func (m *HistoryCall) GetQueueWaitSec() int32 {
	if m != nil {
		return m.QueueWaitSec
	}
	return 0
}

func (m *HistoryCall) GetQueueDurationSec() int32 {
	if m != nil {
		return m.QueueDurationSec
	}
	return 0
}

func (m *HistoryCall) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *HistoryCall) GetReportingSec() int32 {
	if m != nil {
		return m.ReportingSec
	}
	return 0
}

type EavesdropCallRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Control              bool     `protobuf:"varint,3,opt,name=control,proto3" json:"control,omitempty"`
	ListenA              bool     `protobuf:"varint,4,opt,name=listen_a,json=listenA,proto3" json:"listen_a,omitempty"`
	ListenB              bool     `protobuf:"varint,5,opt,name=listen_b,json=listenB,proto3" json:"listen_b,omitempty"`
	WhisperA             bool     `protobuf:"varint,6,opt,name=whisper_a,json=whisperA,proto3" json:"whisper_a,omitempty"`
	WhisperB             bool     `protobuf:"varint,7,opt,name=whisper_b,json=whisperB,proto3" json:"whisper_b,omitempty"`
	DomainId             int64    `protobuf:"varint,8,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EavesdropCallRequest) Reset()         { *m = EavesdropCallRequest{} }
func (m *EavesdropCallRequest) String() string { return proto.CompactTextString(m) }
func (*EavesdropCallRequest) ProtoMessage()    {}
func (*EavesdropCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{4}
}

func (m *EavesdropCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EavesdropCallRequest.Unmarshal(m, b)
}
func (m *EavesdropCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EavesdropCallRequest.Marshal(b, m, deterministic)
}
func (m *EavesdropCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EavesdropCallRequest.Merge(m, src)
}
func (m *EavesdropCallRequest) XXX_Size() int {
	return xxx_messageInfo_EavesdropCallRequest.Size(m)
}
func (m *EavesdropCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EavesdropCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EavesdropCallRequest proto.InternalMessageInfo

func (m *EavesdropCallRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EavesdropCallRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *EavesdropCallRequest) GetControl() bool {
	if m != nil {
		return m.Control
	}
	return false
}

func (m *EavesdropCallRequest) GetListenA() bool {
	if m != nil {
		return m.ListenA
	}
	return false
}

func (m *EavesdropCallRequest) GetListenB() bool {
	if m != nil {
		return m.ListenB
	}
	return false
}

func (m *EavesdropCallRequest) GetWhisperA() bool {
	if m != nil {
		return m.WhisperA
	}
	return false
}

func (m *EavesdropCallRequest) GetWhisperB() bool {
	if m != nil {
		return m.WhisperB
	}
	return false
}

func (m *EavesdropCallRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type BlindTransferCallRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	DomainId             int64    `protobuf:"varint,4,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlindTransferCallRequest) Reset()         { *m = BlindTransferCallRequest{} }
func (m *BlindTransferCallRequest) String() string { return proto.CompactTextString(m) }
func (*BlindTransferCallRequest) ProtoMessage()    {}
func (*BlindTransferCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{5}
}

func (m *BlindTransferCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlindTransferCallRequest.Unmarshal(m, b)
}
func (m *BlindTransferCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlindTransferCallRequest.Marshal(b, m, deterministic)
}
func (m *BlindTransferCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlindTransferCallRequest.Merge(m, src)
}
func (m *BlindTransferCallRequest) XXX_Size() int {
	return xxx_messageInfo_BlindTransferCallRequest.Size(m)
}
func (m *BlindTransferCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlindTransferCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlindTransferCallRequest proto.InternalMessageInfo

func (m *BlindTransferCallRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BlindTransferCallRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *BlindTransferCallRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *BlindTransferCallRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type BlindTransferCallResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlindTransferCallResponse) Reset()         { *m = BlindTransferCallResponse{} }
func (m *BlindTransferCallResponse) String() string { return proto.CompactTextString(m) }
func (*BlindTransferCallResponse) ProtoMessage()    {}
func (*BlindTransferCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{6}
}

func (m *BlindTransferCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlindTransferCallResponse.Unmarshal(m, b)
}
func (m *BlindTransferCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlindTransferCallResponse.Marshal(b, m, deterministic)
}
func (m *BlindTransferCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlindTransferCallResponse.Merge(m, src)
}
func (m *BlindTransferCallResponse) XXX_Size() int {
	return xxx_messageInfo_BlindTransferCallResponse.Size(m)
}
func (m *BlindTransferCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlindTransferCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlindTransferCallResponse proto.InternalMessageInfo

type DtmfCallResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DtmfCallResponse) Reset()         { *m = DtmfCallResponse{} }
func (m *DtmfCallResponse) String() string { return proto.CompactTextString(m) }
func (*DtmfCallResponse) ProtoMessage()    {}
func (*DtmfCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{7}
}

func (m *DtmfCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DtmfCallResponse.Unmarshal(m, b)
}
func (m *DtmfCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DtmfCallResponse.Marshal(b, m, deterministic)
}
func (m *DtmfCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DtmfCallResponse.Merge(m, src)
}
func (m *DtmfCallResponse) XXX_Size() int {
	return xxx_messageInfo_DtmfCallResponse.Size(m)
}
func (m *DtmfCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DtmfCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DtmfCallResponse proto.InternalMessageInfo

type DtmfCallRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Digit                string   `protobuf:"bytes,3,opt,name=digit,proto3" json:"digit,omitempty"`
	DomainId             int64    `protobuf:"varint,4,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DtmfCallRequest) Reset()         { *m = DtmfCallRequest{} }
func (m *DtmfCallRequest) String() string { return proto.CompactTextString(m) }
func (*DtmfCallRequest) ProtoMessage()    {}
func (*DtmfCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{8}
}

func (m *DtmfCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DtmfCallRequest.Unmarshal(m, b)
}
func (m *DtmfCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DtmfCallRequest.Marshal(b, m, deterministic)
}
func (m *DtmfCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DtmfCallRequest.Merge(m, src)
}
func (m *DtmfCallRequest) XXX_Size() int {
	return xxx_messageInfo_DtmfCallRequest.Size(m)
}
func (m *DtmfCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DtmfCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DtmfCallRequest proto.InternalMessageInfo

func (m *DtmfCallRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DtmfCallRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DtmfCallRequest) GetDigit() string {
	if m != nil {
		return m.Digit
	}
	return ""
}

func (m *DtmfCallRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type UserCallRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DomainId             int64    `protobuf:"varint,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCallRequest) Reset()         { *m = UserCallRequest{} }
func (m *UserCallRequest) String() string { return proto.CompactTextString(m) }
func (*UserCallRequest) ProtoMessage()    {}
func (*UserCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{9}
}

func (m *UserCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCallRequest.Unmarshal(m, b)
}
func (m *UserCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCallRequest.Marshal(b, m, deterministic)
}
func (m *UserCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCallRequest.Merge(m, src)
}
func (m *UserCallRequest) XXX_Size() int {
	return xxx_messageInfo_UserCallRequest.Size(m)
}
func (m *UserCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserCallRequest proto.InternalMessageInfo

func (m *UserCallRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserCallRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *UserCallRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type HoldCallResponse struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoldCallResponse) Reset()         { *m = HoldCallResponse{} }
func (m *HoldCallResponse) String() string { return proto.CompactTextString(m) }
func (*HoldCallResponse) ProtoMessage()    {}
func (*HoldCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{10}
}

func (m *HoldCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoldCallResponse.Unmarshal(m, b)
}
func (m *HoldCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoldCallResponse.Marshal(b, m, deterministic)
}
func (m *HoldCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoldCallResponse.Merge(m, src)
}
func (m *HoldCallResponse) XXX_Size() int {
	return xxx_messageInfo_HoldCallResponse.Size(m)
}
func (m *HoldCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HoldCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HoldCallResponse proto.InternalMessageInfo

func (m *HoldCallResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type CreateCallResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCallResponse) Reset()         { *m = CreateCallResponse{} }
func (m *CreateCallResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCallResponse) ProtoMessage()    {}
func (*CreateCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{11}
}

func (m *CreateCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCallResponse.Unmarshal(m, b)
}
func (m *CreateCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCallResponse.Marshal(b, m, deterministic)
}
func (m *CreateCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCallResponse.Merge(m, src)
}
func (m *CreateCallResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCallResponse.Size(m)
}
func (m *CreateCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCallResponse proto.InternalMessageInfo

func (m *CreateCallResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type HangupCallResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HangupCallResponse) Reset()         { *m = HangupCallResponse{} }
func (m *HangupCallResponse) String() string { return proto.CompactTextString(m) }
func (*HangupCallResponse) ProtoMessage()    {}
func (*HangupCallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{12}
}

func (m *HangupCallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupCallResponse.Unmarshal(m, b)
}
func (m *HangupCallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupCallResponse.Marshal(b, m, deterministic)
}
func (m *HangupCallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupCallResponse.Merge(m, src)
}
func (m *HangupCallResponse) XXX_Size() int {
	return xxx_messageInfo_HangupCallResponse.Size(m)
}
func (m *HangupCallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupCallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HangupCallResponse proto.InternalMessageInfo

type HangupCallRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cause                string   `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
	AppId                string   `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DomainId             int64    `protobuf:"varint,4,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HangupCallRequest) Reset()         { *m = HangupCallRequest{} }
func (m *HangupCallRequest) String() string { return proto.CompactTextString(m) }
func (*HangupCallRequest) ProtoMessage()    {}
func (*HangupCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{13}
}

func (m *HangupCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HangupCallRequest.Unmarshal(m, b)
}
func (m *HangupCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HangupCallRequest.Marshal(b, m, deterministic)
}
func (m *HangupCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HangupCallRequest.Merge(m, src)
}
func (m *HangupCallRequest) XXX_Size() int {
	return xxx_messageInfo_HangupCallRequest.Size(m)
}
func (m *HangupCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HangupCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HangupCallRequest proto.InternalMessageInfo

func (m *HangupCallRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HangupCallRequest) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *HangupCallRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *HangupCallRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type ReadCallRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DomainId             int64    `protobuf:"varint,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadCallRequest) Reset()         { *m = ReadCallRequest{} }
func (m *ReadCallRequest) String() string { return proto.CompactTextString(m) }
func (*ReadCallRequest) ProtoMessage()    {}
func (*ReadCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{14}
}

func (m *ReadCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadCallRequest.Unmarshal(m, b)
}
func (m *ReadCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadCallRequest.Marshal(b, m, deterministic)
}
func (m *ReadCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadCallRequest.Merge(m, src)
}
func (m *ReadCallRequest) XXX_Size() int {
	return xxx_messageInfo_ReadCallRequest.Size(m)
}
func (m *ReadCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadCallRequest proto.InternalMessageInfo

func (m *ReadCallRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadCallRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type SearchCallRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Q                    string   `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	DomainId             int64    `protobuf:"varint,4,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchCallRequest) Reset()         { *m = SearchCallRequest{} }
func (m *SearchCallRequest) String() string { return proto.CompactTextString(m) }
func (*SearchCallRequest) ProtoMessage()    {}
func (*SearchCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{15}
}

func (m *SearchCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchCallRequest.Unmarshal(m, b)
}
func (m *SearchCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchCallRequest.Marshal(b, m, deterministic)
}
func (m *SearchCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchCallRequest.Merge(m, src)
}
func (m *SearchCallRequest) XXX_Size() int {
	return xxx_messageInfo_SearchCallRequest.Size(m)
}
func (m *SearchCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchCallRequest proto.InternalMessageInfo

func (m *SearchCallRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchCallRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchCallRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchCallRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type ListCall struct {
	Next                 bool     `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items                []*Call  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCall) Reset()         { *m = ListCall{} }
func (m *ListCall) String() string { return proto.CompactTextString(m) }
func (*ListCall) ProtoMessage()    {}
func (*ListCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{16}
}

func (m *ListCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCall.Unmarshal(m, b)
}
func (m *ListCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCall.Marshal(b, m, deterministic)
}
func (m *ListCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCall.Merge(m, src)
}
func (m *ListCall) XXX_Size() int {
	return xxx_messageInfo_ListCall.Size(m)
}
func (m *ListCall) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCall.DiscardUnknown(m)
}

var xxx_messageInfo_ListCall proto.InternalMessageInfo

func (m *ListCall) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *ListCall) GetItems() []*Call {
	if m != nil {
		return m.Items
	}
	return nil
}

type CreateCallRequest struct {
	From                 *CreateCallRequest_EndpointRequest `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *CreateCallRequest_EndpointRequest `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Destination          string                             `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Params               *CreateCallRequest_CallSettings    `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	DomainId             int64                              `protobuf:"varint,5,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *CreateCallRequest) Reset()         { *m = CreateCallRequest{} }
func (m *CreateCallRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCallRequest) ProtoMessage()    {}
func (*CreateCallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{17}
}

func (m *CreateCallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCallRequest.Unmarshal(m, b)
}
func (m *CreateCallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCallRequest.Marshal(b, m, deterministic)
}
func (m *CreateCallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCallRequest.Merge(m, src)
}
func (m *CreateCallRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCallRequest.Size(m)
}
func (m *CreateCallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCallRequest proto.InternalMessageInfo

func (m *CreateCallRequest) GetFrom() *CreateCallRequest_EndpointRequest {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *CreateCallRequest) GetTo() *CreateCallRequest_EndpointRequest {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *CreateCallRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *CreateCallRequest) GetParams() *CreateCallRequest_CallSettings {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *CreateCallRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type CreateCallRequest_CallSettings struct {
	Timeout              int32             `protobuf:"varint,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Audio                bool              `protobuf:"varint,2,opt,name=audio,proto3" json:"audio,omitempty"`
	Video                bool              `protobuf:"varint,3,opt,name=video,proto3" json:"video,omitempty"`
	Screen               bool              `protobuf:"varint,4,opt,name=screen,proto3" json:"screen,omitempty"`
	Record               bool              `protobuf:"varint,5,opt,name=record,proto3" json:"record,omitempty"`
	Variables            map[string]string `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateCallRequest_CallSettings) Reset()         { *m = CreateCallRequest_CallSettings{} }
func (m *CreateCallRequest_CallSettings) String() string { return proto.CompactTextString(m) }
func (*CreateCallRequest_CallSettings) ProtoMessage()    {}
func (*CreateCallRequest_CallSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{17, 0}
}

func (m *CreateCallRequest_CallSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCallRequest_CallSettings.Unmarshal(m, b)
}
func (m *CreateCallRequest_CallSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCallRequest_CallSettings.Marshal(b, m, deterministic)
}
func (m *CreateCallRequest_CallSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCallRequest_CallSettings.Merge(m, src)
}
func (m *CreateCallRequest_CallSettings) XXX_Size() int {
	return xxx_messageInfo_CreateCallRequest_CallSettings.Size(m)
}
func (m *CreateCallRequest_CallSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCallRequest_CallSettings.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCallRequest_CallSettings proto.InternalMessageInfo

func (m *CreateCallRequest_CallSettings) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *CreateCallRequest_CallSettings) GetAudio() bool {
	if m != nil {
		return m.Audio
	}
	return false
}

func (m *CreateCallRequest_CallSettings) GetVideo() bool {
	if m != nil {
		return m.Video
	}
	return false
}

func (m *CreateCallRequest_CallSettings) GetScreen() bool {
	if m != nil {
		return m.Screen
	}
	return false
}

func (m *CreateCallRequest_CallSettings) GetRecord() bool {
	if m != nil {
		return m.Record
	}
	return false
}

func (m *CreateCallRequest_CallSettings) GetVariables() map[string]string {
	if m != nil {
		return m.Variables
	}
	return nil
}

type CreateCallRequest_EndpointRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCallRequest_EndpointRequest) Reset()         { *m = CreateCallRequest_EndpointRequest{} }
func (m *CreateCallRequest_EndpointRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCallRequest_EndpointRequest) ProtoMessage()    {}
func (*CreateCallRequest_EndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{17, 1}
}

func (m *CreateCallRequest_EndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCallRequest_EndpointRequest.Unmarshal(m, b)
}
func (m *CreateCallRequest_EndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCallRequest_EndpointRequest.Marshal(b, m, deterministic)
}
func (m *CreateCallRequest_EndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCallRequest_EndpointRequest.Merge(m, src)
}
func (m *CreateCallRequest_EndpointRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCallRequest_EndpointRequest.Size(m)
}
func (m *CreateCallRequest_EndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCallRequest_EndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCallRequest_EndpointRequest proto.InternalMessageInfo

func (m *CreateCallRequest_EndpointRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *CreateCallRequest_EndpointRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateCallRequest_EndpointRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Endpoint struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Number               string   `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{18}
}

func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Endpoint) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Endpoint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Endpoint) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Call struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            int64     `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            *Lookup   `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Timestamp            int64     `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ParentId             string    `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	AppId                string    `protobuf:"bytes,6,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	State                string    `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Direction            string    `protobuf:"bytes,8,opt,name=direction,proto3" json:"direction,omitempty"`
	From                 *Endpoint `protobuf:"bytes,9,opt,name=from,proto3" json:"from,omitempty"`
	To                   *Endpoint `protobuf:"bytes,10,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}
func (*Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_caa5955d5eab2d2d, []int{19}
}

func (m *Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call.Unmarshal(m, b)
}
func (m *Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call.Marshal(b, m, deterministic)
}
func (m *Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call.Merge(m, src)
}
func (m *Call) XXX_Size() int {
	return xxx_messageInfo_Call.Size(m)
}
func (m *Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Call proto.InternalMessageInfo

func (m *Call) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Call) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Call) GetCreatedBy() *Lookup {
	if m != nil {
		return m.CreatedBy
	}
	return nil
}

func (m *Call) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Call) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *Call) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Call) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Call) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *Call) GetFrom() *Endpoint {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Call) GetTo() *Endpoint {
	if m != nil {
		return m.To
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchHistoryCallRequest)(nil), "engine.SearchHistoryCallRequest")
	proto.RegisterType((*ListHistoryCall)(nil), "engine.ListHistoryCall")
	proto.RegisterType((*CallFile)(nil), "engine.CallFile")
	proto.RegisterType((*HistoryCall)(nil), "engine.HistoryCall")
	proto.RegisterMapType((map[string]string)(nil), "engine.HistoryCall.VariablesEntry")
	proto.RegisterType((*EavesdropCallRequest)(nil), "engine.EavesdropCallRequest")
	proto.RegisterType((*BlindTransferCallRequest)(nil), "engine.BlindTransferCallRequest")
	proto.RegisterType((*BlindTransferCallResponse)(nil), "engine.BlindTransferCallResponse")
	proto.RegisterType((*DtmfCallResponse)(nil), "engine.DtmfCallResponse")
	proto.RegisterType((*DtmfCallRequest)(nil), "engine.DtmfCallRequest")
	proto.RegisterType((*UserCallRequest)(nil), "engine.UserCallRequest")
	proto.RegisterType((*HoldCallResponse)(nil), "engine.HoldCallResponse")
	proto.RegisterType((*CreateCallResponse)(nil), "engine.CreateCallResponse")
	proto.RegisterType((*HangupCallResponse)(nil), "engine.HangupCallResponse")
	proto.RegisterType((*HangupCallRequest)(nil), "engine.HangupCallRequest")
	proto.RegisterType((*ReadCallRequest)(nil), "engine.ReadCallRequest")
	proto.RegisterType((*SearchCallRequest)(nil), "engine.SearchCallRequest")
	proto.RegisterType((*ListCall)(nil), "engine.ListCall")
	proto.RegisterType((*CreateCallRequest)(nil), "engine.CreateCallRequest")
	proto.RegisterType((*CreateCallRequest_CallSettings)(nil), "engine.CreateCallRequest.CallSettings")
	proto.RegisterMapType((map[string]string)(nil), "engine.CreateCallRequest.CallSettings.VariablesEntry")
	proto.RegisterType((*CreateCallRequest_EndpointRequest)(nil), "engine.CreateCallRequest.EndpointRequest")
	proto.RegisterType((*Endpoint)(nil), "engine.Endpoint")
	proto.RegisterType((*Call)(nil), "engine.Call")
}

func init() { proto.RegisterFile("call.proto", fileDescriptor_caa5955d5eab2d2d) }

var fileDescriptor_caa5955d5eab2d2d = []byte{
	// 1782 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x5f, 0x6f, 0xdb, 0xc8,
	0x11, 0x07, 0xa9, 0x7f, 0xd4, 0xc8, 0x7f, 0xe4, 0x3d, 0x27, 0xa6, 0x15, 0xe7, 0xa2, 0xf0, 0x8c,
	0x54, 0x17, 0xb4, 0x31, 0xea, 0xb6, 0x40, 0x1b, 0xb4, 0x87, 0x5a, 0xb9, 0x1c, 0x22, 0x20, 0x05,
	0x0e, 0xf4, 0x25, 0x05, 0xfa, 0x22, 0xac, 0xc8, 0xb5, 0xbc, 0x0d, 0x45, 0x32, 0xe4, 0xca, 0xae,
	0x5a, 0x14, 0x38, 0x14, 0xfd, 0x06, 0x7d, 0xe8, 0xf7, 0xe8, 0xe7, 0xe8, 0x5b, 0xbf, 0xc2, 0x7d,
	0x84, 0x3e, 0xf6, 0xa1, 0xd8, 0xd9, 0xe5, 0x5f, 0xd3, 0xee, 0x5d, 0xae, 0x6f, 0x9c, 0xf9, 0xcd,
	0xce, 0xcc, 0xee, 0xcc, 0xce, 0xfe, 0x24, 0x00, 0x8f, 0x06, 0xc1, 0xb3, 0x38, 0x89, 0x44, 0x44,
	0xba, 0x2c, 0x5c, 0xf2, 0x90, 0x8d, 0x06, 0x5e, 0x14, 0xa6, 0x42, 0x29, 0x47, 0x47, 0xcb, 0x28,
	0x5a, 0x06, 0xec, 0x84, 0xc6, 0xfc, 0x84, 0x86, 0x61, 0x24, 0xa8, 0xe0, 0x51, 0x98, 0x2a, 0xd4,
	0xf9, 0x6b, 0x1b, 0xec, 0x73, 0x46, 0x13, 0xef, 0xf2, 0x15, 0x4f, 0x45, 0x94, 0x6c, 0x5e, 0xd0,
	0x20, 0x70, 0xd9, 0xfb, 0x35, 0x4b, 0x05, 0x21, 0xd0, 0x8e, 0xe9, 0x92, 0xd9, 0xc6, 0xd8, 0x98,
	0x74, 0x5c, 0xfc, 0x96, 0xba, 0x94, 0xff, 0x91, 0xd9, 0xa6, 0xd2, 0xc9, 0x6f, 0xf2, 0x53, 0x00,
	0x2f, 0x61, 0x54, 0x30, 0x7f, 0x4e, 0x85, 0xdd, 0x1a, 0x1b, 0x93, 0xc1, 0xe9, 0xbd, 0x67, 0x2a,
	0x99, 0x67, 0x5f, 0xf0, 0x40, 0xb0, 0x64, 0xca, 0xc4, 0x35, 0x63, 0xa1, 0xdb, 0xd7, 0x86, 0x67,
	0x82, 0x1c, 0x40, 0x6f, 0x9d, 0xb2, 0x64, 0xce, 0x7d, 0xbb, 0x3d, 0x6e, 0x4d, 0x5a, 0x6e, 0x57,
	0x8a, 0x33, 0x9f, 0x1c, 0x82, 0x45, 0x97, 0x2c, 0x14, 0x12, 0xe9, 0x20, 0xd2, 0x43, 0x59, 0x41,
	0xef, 0xd7, 0x6c, 0xcd, 0x24, 0xd4, 0x55, 0x10, 0xca, 0x33, 0x5f, 0xba, 0x13, 0x8c, 0xae, 0x24,
	0xd2, 0x53, 0xee, 0xa4, 0x38, 0xf3, 0xc9, 0x03, 0xe8, 0xaf, 0xd8, 0x6a, 0xa1, 0x22, 0x59, 0x08,
	0x59, 0x4a, 0x31, 0xf3, 0xc9, 0x43, 0x80, 0x25, 0x15, 0xec, 0x9a, 0x6e, 0x24, 0xda, 0x47, 0xb4,
	0xaf, 0x35, 0x33, 0x9f, 0xdc, 0x87, 0x6e, 0xb8, 0x96, 0xa6, 0x36, 0x8c, 0x8d, 0x49, 0xdf, 0xd5,
	0x12, 0xf9, 0x31, 0x58, 0xfe, 0x3a, 0xc1, 0x93, 0xb4, 0x07, 0x77, 0xed, 0x37, 0x37, 0x23, 0x8f,
	0x60, 0x90, 0xbe, 0xe3, 0xf1, 0x3c, 0xa6, 0x09, 0x0b, 0x85, 0xbd, 0x35, 0x36, 0x26, 0x96, 0x0b,
	0x52, 0xf5, 0x25, 0x6a, 0x64, 0x9e, 0x0a, 0x93, 0x99, 0x6c, 0x63, 0x38, 0x4b, 0x29, 0x66, 0x3e,
	0xd9, 0x87, 0x8e, 0x47, 0xd7, 0x29, 0xb3, 0x77, 0x10, 0x50, 0x82, 0x4c, 0xef, 0x82, 0xb3, 0xc0,
	0x4f, 0xed, 0xdd, 0x71, 0x4b, 0xa6, 0xa7, 0x24, 0x2c, 0x52, 0x94, 0x08, 0x7b, 0x88, 0xc6, 0xf8,
	0x2d, 0xdd, 0xfb, 0xd1, 0x8a, 0xf2, 0x50, 0xba, 0xdf, 0x1b, 0x1b, 0xf2, 0x18, 0x94, 0x62, 0xe6,
	0x3b, 0x5f, 0xc2, 0xee, 0x6b, 0x9e, 0x8a, 0x52, 0x0f, 0x48, 0x1f, 0x21, 0xfb, 0x83, 0xc0, 0xe2,
	0x5b, 0x2e, 0x7e, 0x93, 0x4f, 0xa1, 0xc3, 0x05, 0x5b, 0xa5, 0xb6, 0x39, 0x6e, 0x4d, 0x06, 0xa7,
	0x1f, 0x65, 0x7b, 0x2e, 0xf7, 0x8e, 0xb2, 0x70, 0xe6, 0x60, 0x49, 0xf1, 0x0b, 0x1e, 0x30, 0xb2,
	0x03, 0x26, 0xf7, 0xd1, 0x51, 0xcb, 0x35, 0xb9, 0x8f, 0xae, 0xe9, 0x4a, 0xf5, 0x50, 0xdf, 0xc5,
	0xef, 0xbc, 0xaf, 0x5a, 0x68, 0xa5, 0xfa, 0x4a, 0x56, 0x8e, 0xaf, 0xd8, 0x5c, 0x6c, 0x62, 0x66,
	0xb7, 0xd5, 0x89, 0x48, 0xc5, 0x57, 0x9b, 0x98, 0x39, 0xff, 0xec, 0xc3, 0xa0, 0x9c, 0x6f, 0x11,
	0xa4, 0x8f, 0x41, 0xee, 0x41, 0x97, 0xc6, 0xb1, 0xdc, 0xac, 0x0a, 0xd3, 0xa1, 0x71, 0x3c, 0xc3,
	0xd8, 0xe8, 0xae, 0xa5, 0x62, 0xcb, 0xef, 0xea, 0xc9, 0xb7, 0x6b, 0x27, 0xef, 0x40, 0x5b, 0xf6,
	0xa5, 0xdd, 0xc1, 0x32, 0xef, 0x64, 0x5b, 0x7e, 0x1d, 0x45, 0xef, 0xd6, 0xb1, 0x8b, 0x18, 0x99,
	0x40, 0x4f, 0xf7, 0x8c, 0xdd, 0x6d, 0x34, 0xcb, 0x60, 0x72, 0x04, 0x7d, 0x9f, 0x27, 0xcc, 0xc3,
	0xce, 0xe9, 0x61, 0xa8, 0x42, 0x41, 0xc6, 0x30, 0xf0, 0x59, 0x2a, 0x78, 0xa8, 0x3a, 0xcb, 0x42,
	0xbc, 0xac, 0x22, 0xc7, 0xd0, 0xbe, 0x48, 0xa2, 0x95, 0xdd, 0xc7, 0x30, 0xc3, 0x2c, 0xcc, 0xcb,
	0xd0, 0x8f, 0x23, 0x1e, 0x0a, 0x17, 0x51, 0x32, 0x06, 0x53, 0x44, 0xd8, 0xb2, 0x4d, 0x36, 0xa6,
	0x88, 0xc8, 0xaf, 0xa1, 0x7f, 0x45, 0x13, 0x4e, 0x17, 0x01, 0x4b, 0xed, 0x01, 0x56, 0xd3, 0x69,
	0xa8, 0xe6, 0xb3, 0xb7, 0x99, 0xd1, 0xcb, 0x50, 0x24, 0x1b, 0xb7, 0x58, 0x24, 0x6f, 0x4e, 0xe9,
	0xd2, 0x6f, 0x61, 0xd9, 0x4a, 0xb7, 0xfb, 0x11, 0x0c, 0x68, 0x98, 0x5e, 0xb3, 0x44, 0xe1, 0xdb,
	0x88, 0x43, 0xa6, 0x3a, 0x13, 0x72, 0xfd, 0x22, 0xe1, 0xfe, 0x52, 0xe1, 0x3b, 0x6a, 0xbd, 0xd6,
	0x9c, 0x61, 0xbb, 0x5e, 0xd2, 0x70, 0xb9, 0x8e, 0x25, 0xba, 0xab, 0xda, 0x55, 0x29, 0x2a, 0xe0,
	0x62, 0xa3, 0x9b, 0x5c, 0x83, 0xd3, 0x4d, 0x71, 0x55, 0xf6, 0xca, 0x57, 0x65, 0x54, 0xba, 0xb1,
	0x04, 0x67, 0x57, 0x71, 0x35, 0x0f, 0xc1, 0xba, 0x8c, 0x02, 0x7f, 0x9e, 0x32, 0xcf, 0xfe, 0x08,
	0xb1, 0x9e, 0x94, 0xcf, 0x99, 0x27, 0xa1, 0x6b, 0xca, 0x05, 0x42, 0xfb, 0x0a, 0x92, 0xb2, 0x86,
	0x16, 0x3c, 0x08, 0x10, 0xba, 0xa7, 0x20, 0x29, 0x6b, 0x28, 0xe5, 0xf1, 0xdc, 0x8b, 0x7c, 0x66,
	0xdf, 0x57, 0x50, 0xca, 0xe3, 0x17, 0x91, 0xcf, 0xc8, 0x13, 0xe8, 0x5c, 0x70, 0x79, 0xe8, 0x07,
	0x78, 0xe8, 0x79, 0x75, 0xb2, 0xcb, 0xe2, 0x2a, 0x98, 0x1c, 0x43, 0x07, 0x27, 0x9b, 0x6d, 0x37,
	0x36, 0x94, 0x02, 0xc9, 0x13, 0xe8, 0xaa, 0x51, 0x66, 0x1f, 0x36, 0x9a, 0x69, 0x54, 0x36, 0xb1,
	0x9c, 0x86, 0xf6, 0xa8, 0xb9, 0x89, 0x25, 0x26, 0x23, 0xe2, 0x98, 0xb5, 0x1f, 0x34, 0x47, 0x44,
	0x50, 0x1e, 0xfd, 0xef, 0x23, 0x1e, 0xaa, 0xaa, 0x1d, 0xa9, 0xba, 0x28, 0x85, 0xaa, 0x69, 0xc0,
	0xe8, 0x15, 0x0f, 0x97, 0x12, 0x7d, 0xa8, 0x6a, 0xaa, 0x35, 0x67, 0x82, 0x3c, 0x86, 0xad, 0x84,
	0xc5, 0x51, 0x22, 0xb4, 0xc1, 0xc7, 0x68, 0x30, 0xc8, 0x75, 0x67, 0x82, 0x4c, 0x60, 0xa8, 0x06,
	0x7c, 0xa9, 0x37, 0x1e, 0xa1, 0xd9, 0x0e, 0xea, 0xa7, 0x79, 0x83, 0x1c, 0x83, 0xd2, 0xcc, 0xf3,
	0xfa, 0x8c, 0xf1, 0xa4, 0xb7, 0x50, 0xfb, 0x5b, 0x5d, 0xa4, 0x1f, 0x02, 0x51, 0x56, 0x59, 0xb1,
	0xd1, 0xf2, 0x31, 0x5a, 0xaa, 0x48, 0x9f, 0x6b, 0x40, 0x5a, 0xdf, 0x87, 0x6e, 0xc2, 0xd2, 0x75,
	0x20, 0x6c, 0x47, 0x8d, 0x7b, 0x25, 0x91, 0x4f, 0x60, 0xbb, 0x48, 0x5c, 0x3a, 0xf8, 0x44, 0x85,
	0xca, 0x95, 0xe7, 0xcc, 0x1b, 0xfd, 0x12, 0x76, 0xaa, 0xb7, 0x85, 0x0c, 0xa1, 0xf5, 0x8e, 0x6d,
	0xf4, 0x4c, 0x92, 0x9f, 0xb2, 0x37, 0xaf, 0x68, 0xb0, 0xce, 0x46, 0x9f, 0x12, 0x9e, 0x9b, 0x3f,
	0x37, 0x9c, 0x6f, 0x0c, 0xd8, 0x7f, 0x49, 0xaf, 0x58, 0xea, 0x27, 0x51, 0x5c, 0x7e, 0x84, 0xbf,
	0xe5, 0x5c, 0xb3, 0xa1, 0xe7, 0x45, 0xa1, 0x48, 0xa2, 0x00, 0x47, 0x9b, 0xe5, 0x66, 0xa2, 0x6c,
	0xc6, 0x80, 0xa7, 0x82, 0x85, 0x73, 0x8a, 0xc3, 0xcd, 0x72, 0x7b, 0x4a, 0x3e, 0x2b, 0x41, 0x0b,
	0x9c, 0x6f, 0x39, 0x34, 0x95, 0x75, 0xbe, 0xbe, 0xe4, 0x69, 0xcc, 0x92, 0x39, 0xc5, 0xa1, 0x66,
	0xb9, 0x96, 0x56, 0x9c, 0x95, 0xc1, 0x05, 0x4e, 0xb1, 0x02, 0x9c, 0x56, 0x1f, 0x1a, 0xab, 0xf6,
	0xd0, 0x7c, 0x6d, 0x80, 0x3d, 0x0d, 0x78, 0xe8, 0x7f, 0x95, 0xd0, 0x30, 0xbd, 0x60, 0xc9, 0x07,
	0x6c, 0xb5, 0x36, 0x25, 0x5b, 0x37, 0xa7, 0x64, 0x25, 0x85, 0x76, 0x2d, 0x85, 0x07, 0x70, 0xd8,
	0x90, 0x41, 0x1a, 0x47, 0x61, 0xca, 0x1c, 0x02, 0xc3, 0xcf, 0xc5, 0xea, 0xa2, 0xa2, 0x7b, 0x07,
	0xbb, 0x85, 0xee, 0x3b, 0x65, 0xba, 0x0f, 0x1d, 0x9f, 0x2f, 0xb9, 0xd0, 0x39, 0x2a, 0xe1, 0xee,
	0xec, 0xde, 0xc0, 0xee, 0x9b, 0xf4, 0x83, 0x8e, 0xa5, 0xe2, 0xb6, 0x55, 0x73, 0x3b, 0x81, 0xe1,
	0xab, 0x28, 0xf0, 0xcb, 0xfb, 0x92, 0xd9, 0xa5, 0x82, 0x0a, 0xa6, 0x5d, 0x2b, 0xc1, 0x39, 0x06,
	0xf2, 0x02, 0xa7, 0x78, 0xc5, 0xb6, 0x96, 0x83, 0xb3, 0x0f, 0xe4, 0x15, 0x0e, 0xdc, 0xca, 0x49,
	0xad, 0x60, 0xaf, 0xac, 0x6d, 0x4e, 0x3f, 0x9f, 0xcf, 0x66, 0x79, 0x3e, 0x17, 0x9b, 0x6a, 0xdd,
	0xba, 0xa9, 0xfa, 0x59, 0x7d, 0x06, 0xbb, 0x2e, 0xa3, 0xfe, 0x5d, 0xc1, 0x2a, 0xeb, 0xcd, 0xda,
	0xfa, 0x0b, 0xd8, 0x53, 0xdc, 0xf7, 0x43, 0x48, 0xef, 0x16, 0x18, 0xef, 0x75, 0xae, 0xc6, 0xfb,
	0xbb, 0xf3, 0x9c, 0x82, 0x25, 0xd9, 0xd5, 0xad, 0xb4, 0xca, 0xa9, 0xd2, 0xaa, 0xad, 0xf2, 0x9b,
	0x90, 0xf1, 0xa9, 0x7f, 0xb7, 0x61, 0xaf, 0x5c, 0x17, 0x95, 0xec, 0xaf, 0x34, 0x1d, 0x30, 0x70,
	0x64, 0x7f, 0x9a, 0x2f, 0xac, 0x1b, 0x16, 0x8f, 0xbf, 0x92, 0x35, 0x4f, 0xf8, 0x05, 0xf2, 0x04,
	0xf3, 0xbb, 0x2e, 0x96, 0x04, 0xe2, 0x7f, 0x5f, 0xc2, 0xcf, 0xa0, 0x1b, 0xd3, 0x84, 0xae, 0x52,
	0x3c, 0x8f, 0xc1, 0xe9, 0x93, 0xdb, 0x03, 0xc8, 0xef, 0x73, 0x26, 0xe4, 0x24, 0x4d, 0x5d, 0xbd,
	0xaa, 0x7a, 0xa4, 0x9d, 0xea, 0x91, 0x8e, 0xfe, 0x6e, 0xc2, 0x56, 0x79, 0x95, 0x9c, 0x7f, 0x82,
	0xaf, 0x58, 0xb4, 0x16, 0xba, 0x72, 0x99, 0x28, 0xfb, 0x8d, 0xae, 0x7d, 0xae, 0xf6, 0x69, 0xb9,
	0x4a, 0xc0, 0x49, 0xcc, 0x7d, 0x16, 0xe9, 0x69, 0xa9, 0x04, 0xf9, 0x00, 0xa4, 0x5e, 0xc2, 0x58,
	0xa8, 0x27, 0xa5, 0x96, 0xd4, 0xc3, 0xe0, 0x45, 0x89, 0xaf, 0xc7, 0xa4, 0x96, 0xc8, 0x79, 0x99,
	0x46, 0x75, 0xb1, 0x7a, 0x3f, 0xfb, 0x76, 0xdb, 0xbc, 0x9d, 0x59, 0x7d, 0xbf, 0x87, 0x64, 0xf4,
	0x1a, 0x76, 0x6b, 0xf5, 0x2a, 0xdd, 0x2d, 0xa3, 0x89, 0x0a, 0x9b, 0x25, 0x2a, 0xac, 0xee, 0x4f,
	0x2b, 0xa3, 0xea, 0xce, 0xef, 0xc0, 0xca, 0xbc, 0xe5, 0xf6, 0x46, 0xc9, 0xbe, 0xf8, 0x81, 0x64,
	0x56, 0x7e, 0x20, 0x15, 0x7e, 0xfa, 0x15, 0xca, 0xdf, 0x2e, 0x28, 0xbf, 0xf3, 0x0f, 0x13, 0xda,
	0x8d, 0xd4, 0xbd, 0x4a, 0x2d, 0xcd, 0x3a, 0xb5, 0xfc, 0x51, 0x01, 0x2f, 0x36, 0xfa, 0xe7, 0x66,
	0x9d, 0xad, 0x64, 0xe6, 0x53, 0xa4, 0xdc, 0xb2, 0x15, 0x52, 0x41, 0x57, 0xb1, 0xbe, 0x9a, 0x85,
	0xa2, 0xca, 0xfd, 0x3b, 0x35, 0xee, 0x5f, 0x1c, 0x5c, 0xb7, 0x36, 0xd6, 0xd5, 0xe0, 0xec, 0x95,
	0x06, 0x67, 0x95, 0xda, 0x5b, 0x75, 0x6a, 0xff, 0x7f, 0x22, 0xee, 0xa7, 0xff, 0xe9, 0xc1, 0x40,
	0xf5, 0x51, 0x72, 0xc5, 0x3d, 0x46, 0xf2, 0x19, 0x56, 0xfe, 0x2d, 0x34, 0xce, 0x96, 0xde, 0xf6,
	0xd3, 0x7e, 0x74, 0x90, 0x9f, 0x57, 0xf5, 0x67, 0x9f, 0x73, 0xff, 0x2f, 0xff, 0xfa, 0xe6, 0x6f,
	0xe6, 0x90, 0xec, 0x9c, 0x78, 0x34, 0x08, 0xd2, 0x93, 0x4b, 0x85, 0x91, 0xb7, 0x30, 0x54, 0xce,
	0xce, 0x3c, 0xc1, 0xaf, 0xb0, 0xad, 0xc9, 0x61, 0x35, 0x4c, 0xd9, 0xff, 0xb0, 0xec, 0x1f, 0x1d,
	0xdf, 0x43, 0xc7, 0xbb, 0x64, 0x5b, 0x3b, 0xa6, 0xe8, 0x87, 0xfc, 0x06, 0xac, 0x6c, 0x86, 0x93,
	0x3c, 0xa9, 0xda, 0x54, 0x1f, 0x55, 0x26, 0xa2, 0x33, 0x42, 0x4f, 0xfb, 0x84, 0x54, 0x3c, 0x9d,
	0xfc, 0x89, 0xfb, 0x7f, 0x26, 0x6f, 0x01, 0x8a, 0x7b, 0x57, 0x24, 0x78, 0xe3, 0x2e, 0x8e, 0x46,
	0x4d, 0x90, 0x7e, 0xc6, 0xf6, 0x30, 0xc0, 0xc0, 0xe9, 0xaa, 0x00, 0xcf, 0x8d, 0xa7, 0x64, 0x01,
	0x50, 0xbc, 0x6c, 0x85, 0xdf, 0x1b, 0xaf, 0x5d, 0xe1, 0xb7, 0xe1, 0x79, 0x7c, 0x88, 0x7e, 0x0f,
	0x9e, 0x36, 0x24, 0x2e, 0x63, 0x50, 0xb0, 0xb2, 0x37, 0xba, 0x38, 0x8a, 0x1a, 0x19, 0x18, 0xd9,
	0xb9, 0xff, 0xda, 0x73, 0xee, 0x38, 0xe8, 0xfd, 0xe8, 0xf4, 0xe0, 0xa6, 0xf7, 0x13, 0xf9, 0x73,
	0x46, 0x86, 0x60, 0x00, 0x6f, 0xc2, 0xef, 0x13, 0xe4, 0x18, 0x83, 0x7c, 0x7c, 0x7a, 0xd8, 0x10,
	0x64, 0x1d, 0x66, 0x61, 0x28, 0x58, 0x19, 0x63, 0x2a, 0x82, 0xd4, 0x38, 0x54, 0x11, 0xe4, 0x06,
	0xe1, 0xba, 0x6b, 0x27, 0xbe, 0x58, 0x5d, 0xc8, 0x10, 0x5f, 0x1b, 0xb0, 0x77, 0x83, 0xc6, 0x15,
	0x8d, 0x7f, 0x1b, 0xc7, 0x1c, 0x3d, 0xbe, 0xc3, 0x42, 0x87, 0x7f, 0x82, 0xe1, 0xc7, 0xa7, 0x0f,
	0x1a, 0xc2, 0x0b, 0xbd, 0x40, 0xa6, 0x90, 0xc0, 0x76, 0x85, 0xb1, 0x93, 0xa3, 0xfc, 0xc6, 0x36,
	0x10, 0xf9, 0x3b, 0x3b, 0xee, 0x07, 0x18, 0xf2, 0xb1, 0x73, 0xd4, 0x10, 0x92, 0x65, 0xce, 0x9e,
	0x1b, 0x4f, 0x17, 0x5d, 0xfc, 0xdb, 0xee, 0x27, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x76,
	0xf4, 0x02, 0xf7, 0x13, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CallServiceClient is the client API for CallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CallServiceClient interface {
	// List of call
	SearchHistoryCall(ctx context.Context, in *SearchHistoryCallRequest, opts ...grpc.CallOption) (*ListHistoryCall, error)
	SearchActiveCall(ctx context.Context, in *SearchCallRequest, opts ...grpc.CallOption) (*ListCall, error)
	// Call item
	ReadCall(ctx context.Context, in *ReadCallRequest, opts ...grpc.CallOption) (*Call, error)
	// Create e call
	CreateCall(ctx context.Context, in *CreateCallRequest, opts ...grpc.CallOption) (*CreateCallResponse, error)
	HangupCall(ctx context.Context, in *HangupCallRequest, opts ...grpc.CallOption) (*HangupCallResponse, error)
	HoldCall(ctx context.Context, in *UserCallRequest, opts ...grpc.CallOption) (*HoldCallResponse, error)
	UnHoldCall(ctx context.Context, in *UserCallRequest, opts ...grpc.CallOption) (*HoldCallResponse, error)
	DtmfCall(ctx context.Context, in *DtmfCallRequest, opts ...grpc.CallOption) (*DtmfCallResponse, error)
	BlindTransferCall(ctx context.Context, in *BlindTransferCallRequest, opts ...grpc.CallOption) (*BlindTransferCallResponse, error)
	EavesdropCall(ctx context.Context, in *EavesdropCallRequest, opts ...grpc.CallOption) (*CreateCallResponse, error)
}

type callServiceClient struct {
	cc *grpc.ClientConn
}

func NewCallServiceClient(cc *grpc.ClientConn) CallServiceClient {
	return &callServiceClient{cc}
}

func (c *callServiceClient) SearchHistoryCall(ctx context.Context, in *SearchHistoryCallRequest, opts ...grpc.CallOption) (*ListHistoryCall, error) {
	out := new(ListHistoryCall)
	err := c.cc.Invoke(ctx, "/engine.CallService/SearchHistoryCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) SearchActiveCall(ctx context.Context, in *SearchCallRequest, opts ...grpc.CallOption) (*ListCall, error) {
	out := new(ListCall)
	err := c.cc.Invoke(ctx, "/engine.CallService/SearchActiveCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) ReadCall(ctx context.Context, in *ReadCallRequest, opts ...grpc.CallOption) (*Call, error) {
	out := new(Call)
	err := c.cc.Invoke(ctx, "/engine.CallService/ReadCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) CreateCall(ctx context.Context, in *CreateCallRequest, opts ...grpc.CallOption) (*CreateCallResponse, error) {
	out := new(CreateCallResponse)
	err := c.cc.Invoke(ctx, "/engine.CallService/CreateCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) HangupCall(ctx context.Context, in *HangupCallRequest, opts ...grpc.CallOption) (*HangupCallResponse, error) {
	out := new(HangupCallResponse)
	err := c.cc.Invoke(ctx, "/engine.CallService/HangupCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) HoldCall(ctx context.Context, in *UserCallRequest, opts ...grpc.CallOption) (*HoldCallResponse, error) {
	out := new(HoldCallResponse)
	err := c.cc.Invoke(ctx, "/engine.CallService/HoldCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) UnHoldCall(ctx context.Context, in *UserCallRequest, opts ...grpc.CallOption) (*HoldCallResponse, error) {
	out := new(HoldCallResponse)
	err := c.cc.Invoke(ctx, "/engine.CallService/UnHoldCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) DtmfCall(ctx context.Context, in *DtmfCallRequest, opts ...grpc.CallOption) (*DtmfCallResponse, error) {
	out := new(DtmfCallResponse)
	err := c.cc.Invoke(ctx, "/engine.CallService/DtmfCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) BlindTransferCall(ctx context.Context, in *BlindTransferCallRequest, opts ...grpc.CallOption) (*BlindTransferCallResponse, error) {
	out := new(BlindTransferCallResponse)
	err := c.cc.Invoke(ctx, "/engine.CallService/BlindTransferCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callServiceClient) EavesdropCall(ctx context.Context, in *EavesdropCallRequest, opts ...grpc.CallOption) (*CreateCallResponse, error) {
	out := new(CreateCallResponse)
	err := c.cc.Invoke(ctx, "/engine.CallService/EavesdropCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallServiceServer is the server API for CallService service.
type CallServiceServer interface {
	// List of call
	SearchHistoryCall(context.Context, *SearchHistoryCallRequest) (*ListHistoryCall, error)
	SearchActiveCall(context.Context, *SearchCallRequest) (*ListCall, error)
	// Call item
	ReadCall(context.Context, *ReadCallRequest) (*Call, error)
	// Create e call
	CreateCall(context.Context, *CreateCallRequest) (*CreateCallResponse, error)
	HangupCall(context.Context, *HangupCallRequest) (*HangupCallResponse, error)
	HoldCall(context.Context, *UserCallRequest) (*HoldCallResponse, error)
	UnHoldCall(context.Context, *UserCallRequest) (*HoldCallResponse, error)
	DtmfCall(context.Context, *DtmfCallRequest) (*DtmfCallResponse, error)
	BlindTransferCall(context.Context, *BlindTransferCallRequest) (*BlindTransferCallResponse, error)
	EavesdropCall(context.Context, *EavesdropCallRequest) (*CreateCallResponse, error)
}

// UnimplementedCallServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCallServiceServer struct {
}

func (*UnimplementedCallServiceServer) SearchHistoryCall(ctx context.Context, req *SearchHistoryCallRequest) (*ListHistoryCall, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchHistoryCall not implemented")
}
func (*UnimplementedCallServiceServer) SearchActiveCall(ctx context.Context, req *SearchCallRequest) (*ListCall, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchActiveCall not implemented")
}
func (*UnimplementedCallServiceServer) ReadCall(ctx context.Context, req *ReadCallRequest) (*Call, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadCall not implemented")
}
func (*UnimplementedCallServiceServer) CreateCall(ctx context.Context, req *CreateCallRequest) (*CreateCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCall not implemented")
}
func (*UnimplementedCallServiceServer) HangupCall(ctx context.Context, req *HangupCallRequest) (*HangupCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HangupCall not implemented")
}
func (*UnimplementedCallServiceServer) HoldCall(ctx context.Context, req *UserCallRequest) (*HoldCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HoldCall not implemented")
}
func (*UnimplementedCallServiceServer) UnHoldCall(ctx context.Context, req *UserCallRequest) (*HoldCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnHoldCall not implemented")
}
func (*UnimplementedCallServiceServer) DtmfCall(ctx context.Context, req *DtmfCallRequest) (*DtmfCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DtmfCall not implemented")
}
func (*UnimplementedCallServiceServer) BlindTransferCall(ctx context.Context, req *BlindTransferCallRequest) (*BlindTransferCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlindTransferCall not implemented")
}
func (*UnimplementedCallServiceServer) EavesdropCall(ctx context.Context, req *EavesdropCallRequest) (*CreateCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EavesdropCall not implemented")
}

func RegisterCallServiceServer(s *grpc.Server, srv CallServiceServer) {
	s.RegisterService(&_CallService_serviceDesc, srv)
}

func _CallService_SearchHistoryCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchHistoryCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).SearchHistoryCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CallService/SearchHistoryCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).SearchHistoryCall(ctx, req.(*SearchHistoryCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_SearchActiveCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).SearchActiveCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CallService/SearchActiveCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).SearchActiveCall(ctx, req.(*SearchCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_ReadCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).ReadCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CallService/ReadCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).ReadCall(ctx, req.(*ReadCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_CreateCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).CreateCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CallService/CreateCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).CreateCall(ctx, req.(*CreateCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_HangupCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HangupCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).HangupCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CallService/HangupCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).HangupCall(ctx, req.(*HangupCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_HoldCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).HoldCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CallService/HoldCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).HoldCall(ctx, req.(*UserCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_UnHoldCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).UnHoldCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CallService/UnHoldCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).UnHoldCall(ctx, req.(*UserCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_DtmfCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DtmfCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).DtmfCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CallService/DtmfCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).DtmfCall(ctx, req.(*DtmfCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_BlindTransferCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlindTransferCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).BlindTransferCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CallService/BlindTransferCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).BlindTransferCall(ctx, req.(*BlindTransferCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallService_EavesdropCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EavesdropCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).EavesdropCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.CallService/EavesdropCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).EavesdropCall(ctx, req.(*EavesdropCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CallService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "engine.CallService",
	HandlerType: (*CallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchHistoryCall",
			Handler:    _CallService_SearchHistoryCall_Handler,
		},
		{
			MethodName: "SearchActiveCall",
			Handler:    _CallService_SearchActiveCall_Handler,
		},
		{
			MethodName: "ReadCall",
			Handler:    _CallService_ReadCall_Handler,
		},
		{
			MethodName: "CreateCall",
			Handler:    _CallService_CreateCall_Handler,
		},
		{
			MethodName: "HangupCall",
			Handler:    _CallService_HangupCall_Handler,
		},
		{
			MethodName: "HoldCall",
			Handler:    _CallService_HoldCall_Handler,
		},
		{
			MethodName: "UnHoldCall",
			Handler:    _CallService_UnHoldCall_Handler,
		},
		{
			MethodName: "DtmfCall",
			Handler:    _CallService_DtmfCall_Handler,
		},
		{
			MethodName: "BlindTransferCall",
			Handler:    _CallService_BlindTransferCall_Handler,
		},
		{
			MethodName: "EavesdropCall",
			Handler:    _CallService_EavesdropCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "call.proto",
}
