// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resource_in_team.proto

package engine

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateResourceTeamAgentRequest struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId               int64     `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Agent                *Lookup   `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	Buckets              []*Lookup `protobuf:"bytes,4,rep,name=buckets,proto3" json:"buckets,omitempty"`
	Lvl                  int32     `protobuf:"varint,5,opt,name=lvl,proto3" json:"lvl,omitempty"`
	DomainId             int64     `protobuf:"varint,6,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateResourceTeamAgentRequest) Reset()         { *m = UpdateResourceTeamAgentRequest{} }
func (m *UpdateResourceTeamAgentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateResourceTeamAgentRequest) ProtoMessage()    {}
func (*UpdateResourceTeamAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5a3bd9f62e0a29d, []int{0}
}

func (m *UpdateResourceTeamAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResourceTeamAgentRequest.Unmarshal(m, b)
}
func (m *UpdateResourceTeamAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResourceTeamAgentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateResourceTeamAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResourceTeamAgentRequest.Merge(m, src)
}
func (m *UpdateResourceTeamAgentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateResourceTeamAgentRequest.Size(m)
}
func (m *UpdateResourceTeamAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResourceTeamAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResourceTeamAgentRequest proto.InternalMessageInfo

func (m *UpdateResourceTeamAgentRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateResourceTeamAgentRequest) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *UpdateResourceTeamAgentRequest) GetAgent() *Lookup {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *UpdateResourceTeamAgentRequest) GetBuckets() []*Lookup {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *UpdateResourceTeamAgentRequest) GetLvl() int32 {
	if m != nil {
		return m.Lvl
	}
	return 0
}

func (m *UpdateResourceTeamAgentRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type SearchResourceTeamAgentRequest struct {
	TeamId               int64    `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Q                    string   `protobuf:"bytes,4,opt,name=q,proto3" json:"q,omitempty"`
	DomainId             int64    `protobuf:"varint,5,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResourceTeamAgentRequest) Reset()         { *m = SearchResourceTeamAgentRequest{} }
func (m *SearchResourceTeamAgentRequest) String() string { return proto.CompactTextString(m) }
func (*SearchResourceTeamAgentRequest) ProtoMessage()    {}
func (*SearchResourceTeamAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5a3bd9f62e0a29d, []int{1}
}

func (m *SearchResourceTeamAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResourceTeamAgentRequest.Unmarshal(m, b)
}
func (m *SearchResourceTeamAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResourceTeamAgentRequest.Marshal(b, m, deterministic)
}
func (m *SearchResourceTeamAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResourceTeamAgentRequest.Merge(m, src)
}
func (m *SearchResourceTeamAgentRequest) XXX_Size() int {
	return xxx_messageInfo_SearchResourceTeamAgentRequest.Size(m)
}
func (m *SearchResourceTeamAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResourceTeamAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResourceTeamAgentRequest proto.InternalMessageInfo

func (m *SearchResourceTeamAgentRequest) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *SearchResourceTeamAgentRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchResourceTeamAgentRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchResourceTeamAgentRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchResourceTeamAgentRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type CreateResourceTeamAgentRequest struct {
	TeamId               int64     `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Agent                *Lookup   `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Buckets              []*Lookup `protobuf:"bytes,3,rep,name=buckets,proto3" json:"buckets,omitempty"`
	Lvl                  int32     `protobuf:"varint,4,opt,name=lvl,proto3" json:"lvl,omitempty"`
	DomainId             int64     `protobuf:"varint,5,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateResourceTeamAgentRequest) Reset()         { *m = CreateResourceTeamAgentRequest{} }
func (m *CreateResourceTeamAgentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateResourceTeamAgentRequest) ProtoMessage()    {}
func (*CreateResourceTeamAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5a3bd9f62e0a29d, []int{2}
}

func (m *CreateResourceTeamAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResourceTeamAgentRequest.Unmarshal(m, b)
}
func (m *CreateResourceTeamAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResourceTeamAgentRequest.Marshal(b, m, deterministic)
}
func (m *CreateResourceTeamAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResourceTeamAgentRequest.Merge(m, src)
}
func (m *CreateResourceTeamAgentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateResourceTeamAgentRequest.Size(m)
}
func (m *CreateResourceTeamAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResourceTeamAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResourceTeamAgentRequest proto.InternalMessageInfo

func (m *CreateResourceTeamAgentRequest) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *CreateResourceTeamAgentRequest) GetAgent() *Lookup {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *CreateResourceTeamAgentRequest) GetBuckets() []*Lookup {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *CreateResourceTeamAgentRequest) GetLvl() int32 {
	if m != nil {
		return m.Lvl
	}
	return 0
}

func (m *CreateResourceTeamAgentRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type ReadResourceTeamAgentRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId               int64    `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	DomainId             int64    `protobuf:"varint,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResourceTeamAgentRequest) Reset()         { *m = ReadResourceTeamAgentRequest{} }
func (m *ReadResourceTeamAgentRequest) String() string { return proto.CompactTextString(m) }
func (*ReadResourceTeamAgentRequest) ProtoMessage()    {}
func (*ReadResourceTeamAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5a3bd9f62e0a29d, []int{3}
}

func (m *ReadResourceTeamAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResourceTeamAgentRequest.Unmarshal(m, b)
}
func (m *ReadResourceTeamAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResourceTeamAgentRequest.Marshal(b, m, deterministic)
}
func (m *ReadResourceTeamAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResourceTeamAgentRequest.Merge(m, src)
}
func (m *ReadResourceTeamAgentRequest) XXX_Size() int {
	return xxx_messageInfo_ReadResourceTeamAgentRequest.Size(m)
}
func (m *ReadResourceTeamAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResourceTeamAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResourceTeamAgentRequest proto.InternalMessageInfo

func (m *ReadResourceTeamAgentRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReadResourceTeamAgentRequest) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *ReadResourceTeamAgentRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type DeleteResourceTeamAgentRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId               int64    `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	DomainId             int64    `protobuf:"varint,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResourceTeamAgentRequest) Reset()         { *m = DeleteResourceTeamAgentRequest{} }
func (m *DeleteResourceTeamAgentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteResourceTeamAgentRequest) ProtoMessage()    {}
func (*DeleteResourceTeamAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5a3bd9f62e0a29d, []int{4}
}

func (m *DeleteResourceTeamAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResourceTeamAgentRequest.Unmarshal(m, b)
}
func (m *DeleteResourceTeamAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResourceTeamAgentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteResourceTeamAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResourceTeamAgentRequest.Merge(m, src)
}
func (m *DeleteResourceTeamAgentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteResourceTeamAgentRequest.Size(m)
}
func (m *DeleteResourceTeamAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResourceTeamAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResourceTeamAgentRequest proto.InternalMessageInfo

func (m *DeleteResourceTeamAgentRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteResourceTeamAgentRequest) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *DeleteResourceTeamAgentRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type ResourceTeamAgent struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId               int64     `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Agent                *Lookup   `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	Buckets              []*Lookup `protobuf:"bytes,4,rep,name=buckets,proto3" json:"buckets,omitempty"`
	Lvl                  int32     `protobuf:"varint,5,opt,name=lvl,proto3" json:"lvl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResourceTeamAgent) Reset()         { *m = ResourceTeamAgent{} }
func (m *ResourceTeamAgent) String() string { return proto.CompactTextString(m) }
func (*ResourceTeamAgent) ProtoMessage()    {}
func (*ResourceTeamAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5a3bd9f62e0a29d, []int{5}
}

func (m *ResourceTeamAgent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceTeamAgent.Unmarshal(m, b)
}
func (m *ResourceTeamAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceTeamAgent.Marshal(b, m, deterministic)
}
func (m *ResourceTeamAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceTeamAgent.Merge(m, src)
}
func (m *ResourceTeamAgent) XXX_Size() int {
	return xxx_messageInfo_ResourceTeamAgent.Size(m)
}
func (m *ResourceTeamAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceTeamAgent.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceTeamAgent proto.InternalMessageInfo

func (m *ResourceTeamAgent) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResourceTeamAgent) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *ResourceTeamAgent) GetAgent() *Lookup {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *ResourceTeamAgent) GetBuckets() []*Lookup {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *ResourceTeamAgent) GetLvl() int32 {
	if m != nil {
		return m.Lvl
	}
	return 0
}

type ListResourceTeamAgent struct {
	Next                 bool                 `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items                []*ResourceTeamAgent `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListResourceTeamAgent) Reset()         { *m = ListResourceTeamAgent{} }
func (m *ListResourceTeamAgent) String() string { return proto.CompactTextString(m) }
func (*ListResourceTeamAgent) ProtoMessage()    {}
func (*ListResourceTeamAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5a3bd9f62e0a29d, []int{6}
}

func (m *ListResourceTeamAgent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResourceTeamAgent.Unmarshal(m, b)
}
func (m *ListResourceTeamAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResourceTeamAgent.Marshal(b, m, deterministic)
}
func (m *ListResourceTeamAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResourceTeamAgent.Merge(m, src)
}
func (m *ListResourceTeamAgent) XXX_Size() int {
	return xxx_messageInfo_ListResourceTeamAgent.Size(m)
}
func (m *ListResourceTeamAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResourceTeamAgent.DiscardUnknown(m)
}

var xxx_messageInfo_ListResourceTeamAgent proto.InternalMessageInfo

func (m *ListResourceTeamAgent) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *ListResourceTeamAgent) GetItems() []*ResourceTeamAgent {
	if m != nil {
		return m.Items
	}
	return nil
}

type UpdateResourceTeamSkillRequest struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId               int64     `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Skill                *Lookup   `protobuf:"bytes,3,opt,name=skill,proto3" json:"skill,omitempty"`
	Buckets              []*Lookup `protobuf:"bytes,4,rep,name=buckets,proto3" json:"buckets,omitempty"`
	Lvl                  int32     `protobuf:"varint,5,opt,name=lvl,proto3" json:"lvl,omitempty"`
	MinCapacity          int32     `protobuf:"varint,6,opt,name=min_capacity,json=minCapacity,proto3" json:"min_capacity,omitempty"`
	MaxCapacity          int32     `protobuf:"varint,7,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"`
	DomainId             int64     `protobuf:"varint,8,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateResourceTeamSkillRequest) Reset()         { *m = UpdateResourceTeamSkillRequest{} }
func (m *UpdateResourceTeamSkillRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateResourceTeamSkillRequest) ProtoMessage()    {}
func (*UpdateResourceTeamSkillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5a3bd9f62e0a29d, []int{7}
}

func (m *UpdateResourceTeamSkillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResourceTeamSkillRequest.Unmarshal(m, b)
}
func (m *UpdateResourceTeamSkillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResourceTeamSkillRequest.Marshal(b, m, deterministic)
}
func (m *UpdateResourceTeamSkillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResourceTeamSkillRequest.Merge(m, src)
}
func (m *UpdateResourceTeamSkillRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateResourceTeamSkillRequest.Size(m)
}
func (m *UpdateResourceTeamSkillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResourceTeamSkillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResourceTeamSkillRequest proto.InternalMessageInfo

func (m *UpdateResourceTeamSkillRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateResourceTeamSkillRequest) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *UpdateResourceTeamSkillRequest) GetSkill() *Lookup {
	if m != nil {
		return m.Skill
	}
	return nil
}

func (m *UpdateResourceTeamSkillRequest) GetBuckets() []*Lookup {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *UpdateResourceTeamSkillRequest) GetLvl() int32 {
	if m != nil {
		return m.Lvl
	}
	return 0
}

func (m *UpdateResourceTeamSkillRequest) GetMinCapacity() int32 {
	if m != nil {
		return m.MinCapacity
	}
	return 0
}

func (m *UpdateResourceTeamSkillRequest) GetMaxCapacity() int32 {
	if m != nil {
		return m.MaxCapacity
	}
	return 0
}

func (m *UpdateResourceTeamSkillRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type SearchResourceTeamSkillRequest struct {
	TeamId               int64    `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Q                    string   `protobuf:"bytes,4,opt,name=q,proto3" json:"q,omitempty"`
	DomainId             int64    `protobuf:"varint,5,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResourceTeamSkillRequest) Reset()         { *m = SearchResourceTeamSkillRequest{} }
func (m *SearchResourceTeamSkillRequest) String() string { return proto.CompactTextString(m) }
func (*SearchResourceTeamSkillRequest) ProtoMessage()    {}
func (*SearchResourceTeamSkillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5a3bd9f62e0a29d, []int{8}
}

func (m *SearchResourceTeamSkillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResourceTeamSkillRequest.Unmarshal(m, b)
}
func (m *SearchResourceTeamSkillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResourceTeamSkillRequest.Marshal(b, m, deterministic)
}
func (m *SearchResourceTeamSkillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResourceTeamSkillRequest.Merge(m, src)
}
func (m *SearchResourceTeamSkillRequest) XXX_Size() int {
	return xxx_messageInfo_SearchResourceTeamSkillRequest.Size(m)
}
func (m *SearchResourceTeamSkillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResourceTeamSkillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResourceTeamSkillRequest proto.InternalMessageInfo

func (m *SearchResourceTeamSkillRequest) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *SearchResourceTeamSkillRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchResourceTeamSkillRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchResourceTeamSkillRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *SearchResourceTeamSkillRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type CreateResourceTeamSkillRequest struct {
	TeamId               int64     `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Skill                *Lookup   `protobuf:"bytes,2,opt,name=skill,proto3" json:"skill,omitempty"`
	Buckets              []*Lookup `protobuf:"bytes,3,rep,name=buckets,proto3" json:"buckets,omitempty"`
	Lvl                  int32     `protobuf:"varint,4,opt,name=lvl,proto3" json:"lvl,omitempty"`
	MinCapacity          int32     `protobuf:"varint,5,opt,name=min_capacity,json=minCapacity,proto3" json:"min_capacity,omitempty"`
	MaxCapacity          int32     `protobuf:"varint,6,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"`
	DomainId             int64     `protobuf:"varint,7,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateResourceTeamSkillRequest) Reset()         { *m = CreateResourceTeamSkillRequest{} }
func (m *CreateResourceTeamSkillRequest) String() string { return proto.CompactTextString(m) }
func (*CreateResourceTeamSkillRequest) ProtoMessage()    {}
func (*CreateResourceTeamSkillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5a3bd9f62e0a29d, []int{9}
}

func (m *CreateResourceTeamSkillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResourceTeamSkillRequest.Unmarshal(m, b)
}
func (m *CreateResourceTeamSkillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResourceTeamSkillRequest.Marshal(b, m, deterministic)
}
func (m *CreateResourceTeamSkillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResourceTeamSkillRequest.Merge(m, src)
}
func (m *CreateResourceTeamSkillRequest) XXX_Size() int {
	return xxx_messageInfo_CreateResourceTeamSkillRequest.Size(m)
}
func (m *CreateResourceTeamSkillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResourceTeamSkillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResourceTeamSkillRequest proto.InternalMessageInfo

func (m *CreateResourceTeamSkillRequest) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *CreateResourceTeamSkillRequest) GetSkill() *Lookup {
	if m != nil {
		return m.Skill
	}
	return nil
}

func (m *CreateResourceTeamSkillRequest) GetBuckets() []*Lookup {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *CreateResourceTeamSkillRequest) GetLvl() int32 {
	if m != nil {
		return m.Lvl
	}
	return 0
}

func (m *CreateResourceTeamSkillRequest) GetMinCapacity() int32 {
	if m != nil {
		return m.MinCapacity
	}
	return 0
}

func (m *CreateResourceTeamSkillRequest) GetMaxCapacity() int32 {
	if m != nil {
		return m.MaxCapacity
	}
	return 0
}

func (m *CreateResourceTeamSkillRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type ReadResourceTeamSkillRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId               int64    `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	DomainId             int64    `protobuf:"varint,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResourceTeamSkillRequest) Reset()         { *m = ReadResourceTeamSkillRequest{} }
func (m *ReadResourceTeamSkillRequest) String() string { return proto.CompactTextString(m) }
func (*ReadResourceTeamSkillRequest) ProtoMessage()    {}
func (*ReadResourceTeamSkillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5a3bd9f62e0a29d, []int{10}
}

func (m *ReadResourceTeamSkillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResourceTeamSkillRequest.Unmarshal(m, b)
}
func (m *ReadResourceTeamSkillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResourceTeamSkillRequest.Marshal(b, m, deterministic)
}
func (m *ReadResourceTeamSkillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResourceTeamSkillRequest.Merge(m, src)
}
func (m *ReadResourceTeamSkillRequest) XXX_Size() int {
	return xxx_messageInfo_ReadResourceTeamSkillRequest.Size(m)
}
func (m *ReadResourceTeamSkillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResourceTeamSkillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResourceTeamSkillRequest proto.InternalMessageInfo

func (m *ReadResourceTeamSkillRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReadResourceTeamSkillRequest) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *ReadResourceTeamSkillRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type DeleteResourceTeamSkillRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId               int64    `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	DomainId             int64    `protobuf:"varint,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResourceTeamSkillRequest) Reset()         { *m = DeleteResourceTeamSkillRequest{} }
func (m *DeleteResourceTeamSkillRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteResourceTeamSkillRequest) ProtoMessage()    {}
func (*DeleteResourceTeamSkillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5a3bd9f62e0a29d, []int{11}
}

func (m *DeleteResourceTeamSkillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResourceTeamSkillRequest.Unmarshal(m, b)
}
func (m *DeleteResourceTeamSkillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResourceTeamSkillRequest.Marshal(b, m, deterministic)
}
func (m *DeleteResourceTeamSkillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResourceTeamSkillRequest.Merge(m, src)
}
func (m *DeleteResourceTeamSkillRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteResourceTeamSkillRequest.Size(m)
}
func (m *DeleteResourceTeamSkillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResourceTeamSkillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResourceTeamSkillRequest proto.InternalMessageInfo

func (m *DeleteResourceTeamSkillRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteResourceTeamSkillRequest) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *DeleteResourceTeamSkillRequest) GetDomainId() int64 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

type ResourceTeamSkill struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId               int64     `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Skill                *Lookup   `protobuf:"bytes,3,opt,name=skill,proto3" json:"skill,omitempty"`
	Buckets              []*Lookup `protobuf:"bytes,4,rep,name=buckets,proto3" json:"buckets,omitempty"`
	Lvl                  int32     `protobuf:"varint,5,opt,name=lvl,proto3" json:"lvl,omitempty"`
	MinCapacity          int32     `protobuf:"varint,6,opt,name=min_capacity,json=minCapacity,proto3" json:"min_capacity,omitempty"`
	MaxCapacity          int32     `protobuf:"varint,7,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResourceTeamSkill) Reset()         { *m = ResourceTeamSkill{} }
func (m *ResourceTeamSkill) String() string { return proto.CompactTextString(m) }
func (*ResourceTeamSkill) ProtoMessage()    {}
func (*ResourceTeamSkill) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5a3bd9f62e0a29d, []int{12}
}

func (m *ResourceTeamSkill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceTeamSkill.Unmarshal(m, b)
}
func (m *ResourceTeamSkill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceTeamSkill.Marshal(b, m, deterministic)
}
func (m *ResourceTeamSkill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceTeamSkill.Merge(m, src)
}
func (m *ResourceTeamSkill) XXX_Size() int {
	return xxx_messageInfo_ResourceTeamSkill.Size(m)
}
func (m *ResourceTeamSkill) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceTeamSkill.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceTeamSkill proto.InternalMessageInfo

func (m *ResourceTeamSkill) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResourceTeamSkill) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *ResourceTeamSkill) GetSkill() *Lookup {
	if m != nil {
		return m.Skill
	}
	return nil
}

func (m *ResourceTeamSkill) GetBuckets() []*Lookup {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *ResourceTeamSkill) GetLvl() int32 {
	if m != nil {
		return m.Lvl
	}
	return 0
}

func (m *ResourceTeamSkill) GetMinCapacity() int32 {
	if m != nil {
		return m.MinCapacity
	}
	return 0
}

func (m *ResourceTeamSkill) GetMaxCapacity() int32 {
	if m != nil {
		return m.MaxCapacity
	}
	return 0
}

type ListResourceTeamSkill struct {
	Next                 bool                 `protobuf:"varint,1,opt,name=next,proto3" json:"next,omitempty"`
	Items                []*ResourceTeamSkill `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListResourceTeamSkill) Reset()         { *m = ListResourceTeamSkill{} }
func (m *ListResourceTeamSkill) String() string { return proto.CompactTextString(m) }
func (*ListResourceTeamSkill) ProtoMessage()    {}
func (*ListResourceTeamSkill) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5a3bd9f62e0a29d, []int{13}
}

func (m *ListResourceTeamSkill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResourceTeamSkill.Unmarshal(m, b)
}
func (m *ListResourceTeamSkill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResourceTeamSkill.Marshal(b, m, deterministic)
}
func (m *ListResourceTeamSkill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResourceTeamSkill.Merge(m, src)
}
func (m *ListResourceTeamSkill) XXX_Size() int {
	return xxx_messageInfo_ListResourceTeamSkill.Size(m)
}
func (m *ListResourceTeamSkill) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResourceTeamSkill.DiscardUnknown(m)
}

var xxx_messageInfo_ListResourceTeamSkill proto.InternalMessageInfo

func (m *ListResourceTeamSkill) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *ListResourceTeamSkill) GetItems() []*ResourceTeamSkill {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateResourceTeamAgentRequest)(nil), "engine.UpdateResourceTeamAgentRequest")
	proto.RegisterType((*SearchResourceTeamAgentRequest)(nil), "engine.SearchResourceTeamAgentRequest")
	proto.RegisterType((*CreateResourceTeamAgentRequest)(nil), "engine.CreateResourceTeamAgentRequest")
	proto.RegisterType((*ReadResourceTeamAgentRequest)(nil), "engine.ReadResourceTeamAgentRequest")
	proto.RegisterType((*DeleteResourceTeamAgentRequest)(nil), "engine.DeleteResourceTeamAgentRequest")
	proto.RegisterType((*ResourceTeamAgent)(nil), "engine.ResourceTeamAgent")
	proto.RegisterType((*ListResourceTeamAgent)(nil), "engine.ListResourceTeamAgent")
	proto.RegisterType((*UpdateResourceTeamSkillRequest)(nil), "engine.UpdateResourceTeamSkillRequest")
	proto.RegisterType((*SearchResourceTeamSkillRequest)(nil), "engine.SearchResourceTeamSkillRequest")
	proto.RegisterType((*CreateResourceTeamSkillRequest)(nil), "engine.CreateResourceTeamSkillRequest")
	proto.RegisterType((*ReadResourceTeamSkillRequest)(nil), "engine.ReadResourceTeamSkillRequest")
	proto.RegisterType((*DeleteResourceTeamSkillRequest)(nil), "engine.DeleteResourceTeamSkillRequest")
	proto.RegisterType((*ResourceTeamSkill)(nil), "engine.ResourceTeamSkill")
	proto.RegisterType((*ListResourceTeamSkill)(nil), "engine.ListResourceTeamSkill")
}

func init() { proto.RegisterFile("resource_in_team.proto", fileDescriptor_d5a3bd9f62e0a29d) }

var fileDescriptor_d5a3bd9f62e0a29d = []byte{
	// 767 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x97, 0x41, 0x6f, 0xd3, 0x3c,
	0x18, 0xc7, 0xe5, 0xb4, 0x69, 0x37, 0x77, 0x9a, 0xde, 0xd7, 0x68, 0xb4, 0x94, 0x51, 0x95, 0x30,
	0x50, 0x54, 0x44, 0x83, 0xb6, 0x1b, 0x37, 0x34, 0x2e, 0x93, 0x76, 0xca, 0xe0, 0x86, 0x54, 0x79,
	0x89, 0x29, 0xd6, 0x52, 0xa7, 0x4b, 0xdc, 0x69, 0x30, 0xed, 0xc2, 0x11, 0x8d, 0x49, 0x88, 0x3b,
	0x5f, 0x03, 0x3e, 0x02, 0x77, 0xbe, 0xc2, 0x3e, 0x07, 0x42, 0xb1, 0xbb, 0x76, 0xcd, 0x62, 0xcf,
	0xdb, 0x00, 0x21, 0x6e, 0x9e, 0xed, 0xe6, 0xf9, 0xf9, 0xff, 0xfc, 0xfd, 0xf8, 0x19, 0xbc, 0x99,
	0x90, 0x34, 0x1e, 0x25, 0x01, 0xe9, 0x51, 0xd6, 0xe3, 0x04, 0x0f, 0xba, 0xc3, 0x24, 0xe6, 0x31,
	0xaa, 0x10, 0xd6, 0xa7, 0x8c, 0x34, 0x6b, 0x41, 0xcc, 0x52, 0x2e, 0x27, 0x9b, 0xcb, 0xfd, 0x38,
	0xee, 0x47, 0xc4, 0xc3, 0x43, 0xea, 0x61, 0xc6, 0x62, 0x8e, 0x39, 0x8d, 0x59, 0x2a, 0x57, 0x9d,
	0x6f, 0x00, 0xb6, 0x5e, 0x0c, 0x43, 0xcc, 0x89, 0x3f, 0xfe, 0xe6, 0x73, 0x82, 0x07, 0x4f, 0xfb,
	0x84, 0x71, 0x9f, 0xec, 0x8e, 0x48, 0xca, 0xd1, 0x22, 0xb4, 0x68, 0xd8, 0x00, 0x6d, 0xe0, 0x96,
	0x7c, 0x8b, 0x86, 0xa8, 0x0e, 0xab, 0x59, 0xcc, 0x1e, 0x0d, 0x1b, 0x96, 0x98, 0xac, 0x64, 0x7f,
	0x6e, 0x84, 0x68, 0x05, 0xda, 0x38, 0xfb, 0x61, 0xa3, 0xd4, 0x06, 0x6e, 0x6d, 0x75, 0xb1, 0x2b,
	0x71, 0xba, 0x9b, 0x71, 0xbc, 0x33, 0x1a, 0xfa, 0x72, 0x11, 0xb9, 0xb0, 0xba, 0x3d, 0x0a, 0x76,
	0x08, 0x4f, 0x1b, 0xe5, 0x76, 0xa9, 0x60, 0xdf, 0xe9, 0x32, 0xfa, 0x0f, 0x96, 0xa2, 0xbd, 0xa8,
	0x61, 0xb7, 0x81, 0x6b, 0xfb, 0xd9, 0x10, 0xdd, 0x86, 0xf3, 0x61, 0x3c, 0xc0, 0x94, 0x65, 0xc1,
	0x2b, 0x22, 0xf8, 0x9c, 0x9c, 0xd8, 0x08, 0x9d, 0x23, 0x00, 0x5b, 0x5b, 0x04, 0x27, 0xc1, 0x6b,
	0xe5, 0x51, 0xce, 0xa0, 0x83, 0x19, 0x74, 0x04, 0xcb, 0x43, 0xdc, 0x27, 0xe2, 0x40, 0xb6, 0x2f,
	0xc6, 0xd9, 0x5c, 0x4a, 0xdf, 0x12, 0x71, 0x1a, 0xdb, 0x17, 0x63, 0xb4, 0x00, 0xc1, 0x6e, 0xa3,
	0xdc, 0x06, 0xee, 0xbc, 0x0f, 0x76, 0x67, 0x71, 0xec, 0x1c, 0xce, 0x57, 0x00, 0x5b, 0xeb, 0x09,
	0xd1, 0x29, 0xab, 0xc4, 0x99, 0x28, 0x69, 0x19, 0x2a, 0x59, 0x32, 0x52, 0xb2, 0xac, 0x50, 0x32,
	0x8f, 0x1e, 0xc2, 0x65, 0x9f, 0xe0, 0xf0, 0xfa, 0x8e, 0x98, 0x89, 0x52, 0xca, 0x45, 0x79, 0x05,
	0x5b, 0xcf, 0x48, 0x44, 0x7e, 0x85, 0xf3, 0xb4, 0x71, 0x3e, 0x03, 0xf8, 0xff, 0xb9, 0x10, 0x7f,
	0x91, 0xab, 0x9d, 0x97, 0x70, 0x69, 0x93, 0xa6, 0xfc, 0x3c, 0x23, 0x82, 0x65, 0x46, 0xf6, 0xb9,
	0xa0, 0x9c, 0xf3, 0xc5, 0x18, 0x79, 0xd0, 0xa6, 0x9c, 0x0c, 0xd2, 0x86, 0x25, 0xc2, 0xdc, 0x3a,
	0x0d, 0x73, 0x5e, 0x44, 0xb9, 0xcf, 0x39, 0xb6, 0x8a, 0x6e, 0xf8, 0xd6, 0x0e, 0x8d, 0xa2, 0xab,
	0xdc, 0xf0, 0x34, 0xfb, 0xa1, 0x4a, 0x0b, 0xb1, 0x78, 0xad, 0x1b, 0x7e, 0x17, 0x2e, 0x0c, 0x28,
	0xeb, 0x05, 0x78, 0x88, 0x03, 0xca, 0xdf, 0x88, 0x4b, 0x6e, 0xfb, 0xb5, 0x01, 0x65, 0xeb, 0xe3,
	0x29, 0xb1, 0x05, 0xef, 0x4f, 0xb7, 0x54, 0xc7, 0x5b, 0xf0, 0xfe, 0x64, 0xcb, 0x8c, 0x1f, 0xe6,
	0x8c, 0xea, 0xc4, 0x8c, 0x20, 0x7f, 0xb2, 0x4e, 0xfc, 0x28, 0xac, 0x13, 0x66, 0x38, 0x93, 0x7c,
	0x58, 0x86, 0xf9, 0xb8, 0x74, 0x9d, 0xc8, 0xe7, 0xc3, 0xbe, 0x38, 0x1f, 0x95, 0x0b, 0xf2, 0x51,
	0xbd, 0xb8, 0xda, 0x5c, 0xcd, 0x9d, 0x97, 0xaf, 0x36, 0xbf, 0x21, 0xce, 0x49, 0xae, 0xda, 0x88,
	0x10, 0xff, 0xdc, 0x0d, 0x2b, 0xaa, 0x59, 0xf2, 0xa4, 0x57, 0xad, 0x59, 0x32, 0x15, 0x72, 0xdf,
	0xea, 0x97, 0x1a, 0xbc, 0x31, 0xb3, 0x48, 0x92, 0x3d, 0x1a, 0x10, 0x74, 0x04, 0x60, 0x5d, 0xf1,
	0xa6, 0xa2, 0x07, 0xa7, 0x5f, 0xd5, 0x3f, 0xba, 0x4d, 0x75, 0xc5, 0x74, 0xba, 0xef, 0xbe, 0x9f,
	0x7c, 0xb2, 0x5c, 0xe7, 0x9e, 0x17, 0xe0, 0x28, 0xea, 0x05, 0x84, 0x71, 0x92, 0x78, 0x59, 0x66,
	0x52, 0xef, 0x60, 0x9c, 0xaf, 0x43, 0x4f, 0x14, 0xfc, 0xf4, 0x09, 0xe8, 0xa0, 0x0f, 0x00, 0xd6,
	0x15, 0x1d, 0xc7, 0x14, 0x47, 0xdf, 0x92, 0x34, 0xef, 0x4c, 0x32, 0x57, 0xf4, 0x04, 0x38, 0x0f,
	0x05, 0xd2, 0x7d, 0x64, 0x82, 0x84, 0xde, 0x03, 0xb8, 0x54, 0xf8, 0x70, 0xa3, 0x95, 0xe9, 0xa1,
	0xd5, 0xef, 0xba, 0x4e, 0x9a, 0xc7, 0x82, 0xa3, 0x83, 0x5c, 0x03, 0x0e, 0xef, 0x80, 0x86, 0x87,
	0xe8, 0x23, 0x80, 0x75, 0x45, 0x67, 0x39, 0x15, 0x47, 0xdf, 0x7a, 0xea, 0x80, 0xd6, 0x04, 0xd0,
	0xa3, 0xa6, 0x31, 0x50, 0x96, 0xb0, 0x63, 0x00, 0xeb, 0x8a, 0x9e, 0x63, 0xca, 0xa4, 0x6f, 0x4a,
	0x0c, 0x44, 0xea, 0x98, 0x8b, 0x54, 0x6c, 0x68, 0x79, 0x93, 0x34, 0x86, 0x3e, 0x5b, 0xb7, 0x9a,
	0xea, 0xeb, 0x64, 0x68, 0x68, 0x51, 0x53, 0x34, 0x86, 0xce, 0xe1, 0xe8, 0xdf, 0x4e, 0xb5, 0xa1,
	0x25, 0x92, 0x99, 0xa1, 0x25, 0x52, 0xa1, 0xa1, 0x25, 0x8d, 0xd2, 0xd0, 0xa6, 0xd2, 0x98, 0x19,
	0x5a, 0x72, 0xe8, 0x0c, 0x9d, 0x13, 0x47, 0xdf, 0x69, 0xe9, 0x80, 0xcc, 0x0c, 0x7d, 0x06, 0x48,
	0x6d, 0xe8, 0x1c, 0x93, 0xfe, 0xdd, 0x33, 0x10, 0xa9, 0x63, 0xcc, 0xb4, 0x5d, 0x11, 0xff, 0x56,
	0xae, 0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x67, 0x36, 0xdc, 0x57, 0xa3, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResourceTeamServiceClient is the client API for ResourceTeamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceTeamServiceClient interface {
	// Create ResourceTeamAgent
	CreateResourceTeamAgent(ctx context.Context, in *CreateResourceTeamAgentRequest, opts ...grpc.CallOption) (*ResourceTeamAgent, error)
	// List of ResourceTeamAgent
	SearchResourceTeamAgent(ctx context.Context, in *SearchResourceTeamAgentRequest, opts ...grpc.CallOption) (*ListResourceTeamAgent, error)
	// ResourceTeamAgent item
	ReadResourceTeamAgent(ctx context.Context, in *ReadResourceTeamAgentRequest, opts ...grpc.CallOption) (*ResourceTeamAgent, error)
	// Update ResourceTeamAgent
	UpdateResourceTeamAgent(ctx context.Context, in *UpdateResourceTeamAgentRequest, opts ...grpc.CallOption) (*ResourceTeamAgent, error)
	// Remove ResourceTeamAgent
	DeleteResourceTeamAgent(ctx context.Context, in *DeleteResourceTeamAgentRequest, opts ...grpc.CallOption) (*ResourceTeamAgent, error)
	//SKill
	// Create ResourceTeamSkill
	CreateResourceTeamSkill(ctx context.Context, in *CreateResourceTeamSkillRequest, opts ...grpc.CallOption) (*ResourceTeamSkill, error)
	// List of ResourceTeamSkill
	SearchResourceTeamSkill(ctx context.Context, in *SearchResourceTeamSkillRequest, opts ...grpc.CallOption) (*ListResourceTeamSkill, error)
	// ResourceTeamSkill item
	ReadResourceTeamSkill(ctx context.Context, in *ReadResourceTeamSkillRequest, opts ...grpc.CallOption) (*ResourceTeamSkill, error)
	// Update ResourceTeamSkill
	UpdateResourceTeamSkill(ctx context.Context, in *UpdateResourceTeamSkillRequest, opts ...grpc.CallOption) (*ResourceTeamSkill, error)
	// Remove ResourceTeamSkill
	DeleteResourceTeamSkill(ctx context.Context, in *DeleteResourceTeamSkillRequest, opts ...grpc.CallOption) (*ResourceTeamSkill, error)
}

type resourceTeamServiceClient struct {
	cc *grpc.ClientConn
}

func NewResourceTeamServiceClient(cc *grpc.ClientConn) ResourceTeamServiceClient {
	return &resourceTeamServiceClient{cc}
}

func (c *resourceTeamServiceClient) CreateResourceTeamAgent(ctx context.Context, in *CreateResourceTeamAgentRequest, opts ...grpc.CallOption) (*ResourceTeamAgent, error) {
	out := new(ResourceTeamAgent)
	err := c.cc.Invoke(ctx, "/engine.ResourceTeamService/CreateResourceTeamAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceTeamServiceClient) SearchResourceTeamAgent(ctx context.Context, in *SearchResourceTeamAgentRequest, opts ...grpc.CallOption) (*ListResourceTeamAgent, error) {
	out := new(ListResourceTeamAgent)
	err := c.cc.Invoke(ctx, "/engine.ResourceTeamService/SearchResourceTeamAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceTeamServiceClient) ReadResourceTeamAgent(ctx context.Context, in *ReadResourceTeamAgentRequest, opts ...grpc.CallOption) (*ResourceTeamAgent, error) {
	out := new(ResourceTeamAgent)
	err := c.cc.Invoke(ctx, "/engine.ResourceTeamService/ReadResourceTeamAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceTeamServiceClient) UpdateResourceTeamAgent(ctx context.Context, in *UpdateResourceTeamAgentRequest, opts ...grpc.CallOption) (*ResourceTeamAgent, error) {
	out := new(ResourceTeamAgent)
	err := c.cc.Invoke(ctx, "/engine.ResourceTeamService/UpdateResourceTeamAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceTeamServiceClient) DeleteResourceTeamAgent(ctx context.Context, in *DeleteResourceTeamAgentRequest, opts ...grpc.CallOption) (*ResourceTeamAgent, error) {
	out := new(ResourceTeamAgent)
	err := c.cc.Invoke(ctx, "/engine.ResourceTeamService/DeleteResourceTeamAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceTeamServiceClient) CreateResourceTeamSkill(ctx context.Context, in *CreateResourceTeamSkillRequest, opts ...grpc.CallOption) (*ResourceTeamSkill, error) {
	out := new(ResourceTeamSkill)
	err := c.cc.Invoke(ctx, "/engine.ResourceTeamService/CreateResourceTeamSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceTeamServiceClient) SearchResourceTeamSkill(ctx context.Context, in *SearchResourceTeamSkillRequest, opts ...grpc.CallOption) (*ListResourceTeamSkill, error) {
	out := new(ListResourceTeamSkill)
	err := c.cc.Invoke(ctx, "/engine.ResourceTeamService/SearchResourceTeamSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceTeamServiceClient) ReadResourceTeamSkill(ctx context.Context, in *ReadResourceTeamSkillRequest, opts ...grpc.CallOption) (*ResourceTeamSkill, error) {
	out := new(ResourceTeamSkill)
	err := c.cc.Invoke(ctx, "/engine.ResourceTeamService/ReadResourceTeamSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceTeamServiceClient) UpdateResourceTeamSkill(ctx context.Context, in *UpdateResourceTeamSkillRequest, opts ...grpc.CallOption) (*ResourceTeamSkill, error) {
	out := new(ResourceTeamSkill)
	err := c.cc.Invoke(ctx, "/engine.ResourceTeamService/UpdateResourceTeamSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceTeamServiceClient) DeleteResourceTeamSkill(ctx context.Context, in *DeleteResourceTeamSkillRequest, opts ...grpc.CallOption) (*ResourceTeamSkill, error) {
	out := new(ResourceTeamSkill)
	err := c.cc.Invoke(ctx, "/engine.ResourceTeamService/DeleteResourceTeamSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceTeamServiceServer is the server API for ResourceTeamService service.
type ResourceTeamServiceServer interface {
	// Create ResourceTeamAgent
	CreateResourceTeamAgent(context.Context, *CreateResourceTeamAgentRequest) (*ResourceTeamAgent, error)
	// List of ResourceTeamAgent
	SearchResourceTeamAgent(context.Context, *SearchResourceTeamAgentRequest) (*ListResourceTeamAgent, error)
	// ResourceTeamAgent item
	ReadResourceTeamAgent(context.Context, *ReadResourceTeamAgentRequest) (*ResourceTeamAgent, error)
	// Update ResourceTeamAgent
	UpdateResourceTeamAgent(context.Context, *UpdateResourceTeamAgentRequest) (*ResourceTeamAgent, error)
	// Remove ResourceTeamAgent
	DeleteResourceTeamAgent(context.Context, *DeleteResourceTeamAgentRequest) (*ResourceTeamAgent, error)
	//SKill
	// Create ResourceTeamSkill
	CreateResourceTeamSkill(context.Context, *CreateResourceTeamSkillRequest) (*ResourceTeamSkill, error)
	// List of ResourceTeamSkill
	SearchResourceTeamSkill(context.Context, *SearchResourceTeamSkillRequest) (*ListResourceTeamSkill, error)
	// ResourceTeamSkill item
	ReadResourceTeamSkill(context.Context, *ReadResourceTeamSkillRequest) (*ResourceTeamSkill, error)
	// Update ResourceTeamSkill
	UpdateResourceTeamSkill(context.Context, *UpdateResourceTeamSkillRequest) (*ResourceTeamSkill, error)
	// Remove ResourceTeamSkill
	DeleteResourceTeamSkill(context.Context, *DeleteResourceTeamSkillRequest) (*ResourceTeamSkill, error)
}

// UnimplementedResourceTeamServiceServer can be embedded to have forward compatible implementations.
type UnimplementedResourceTeamServiceServer struct {
}

func (*UnimplementedResourceTeamServiceServer) CreateResourceTeamAgent(ctx context.Context, req *CreateResourceTeamAgentRequest) (*ResourceTeamAgent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResourceTeamAgent not implemented")
}
func (*UnimplementedResourceTeamServiceServer) SearchResourceTeamAgent(ctx context.Context, req *SearchResourceTeamAgentRequest) (*ListResourceTeamAgent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchResourceTeamAgent not implemented")
}
func (*UnimplementedResourceTeamServiceServer) ReadResourceTeamAgent(ctx context.Context, req *ReadResourceTeamAgentRequest) (*ResourceTeamAgent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadResourceTeamAgent not implemented")
}
func (*UnimplementedResourceTeamServiceServer) UpdateResourceTeamAgent(ctx context.Context, req *UpdateResourceTeamAgentRequest) (*ResourceTeamAgent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateResourceTeamAgent not implemented")
}
func (*UnimplementedResourceTeamServiceServer) DeleteResourceTeamAgent(ctx context.Context, req *DeleteResourceTeamAgentRequest) (*ResourceTeamAgent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResourceTeamAgent not implemented")
}
func (*UnimplementedResourceTeamServiceServer) CreateResourceTeamSkill(ctx context.Context, req *CreateResourceTeamSkillRequest) (*ResourceTeamSkill, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResourceTeamSkill not implemented")
}
func (*UnimplementedResourceTeamServiceServer) SearchResourceTeamSkill(ctx context.Context, req *SearchResourceTeamSkillRequest) (*ListResourceTeamSkill, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchResourceTeamSkill not implemented")
}
func (*UnimplementedResourceTeamServiceServer) ReadResourceTeamSkill(ctx context.Context, req *ReadResourceTeamSkillRequest) (*ResourceTeamSkill, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadResourceTeamSkill not implemented")
}
func (*UnimplementedResourceTeamServiceServer) UpdateResourceTeamSkill(ctx context.Context, req *UpdateResourceTeamSkillRequest) (*ResourceTeamSkill, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateResourceTeamSkill not implemented")
}
func (*UnimplementedResourceTeamServiceServer) DeleteResourceTeamSkill(ctx context.Context, req *DeleteResourceTeamSkillRequest) (*ResourceTeamSkill, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResourceTeamSkill not implemented")
}

func RegisterResourceTeamServiceServer(s *grpc.Server, srv ResourceTeamServiceServer) {
	s.RegisterService(&_ResourceTeamService_serviceDesc, srv)
}

func _ResourceTeamService_CreateResourceTeamAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceTeamAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceTeamServiceServer).CreateResourceTeamAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.ResourceTeamService/CreateResourceTeamAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceTeamServiceServer).CreateResourceTeamAgent(ctx, req.(*CreateResourceTeamAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceTeamService_SearchResourceTeamAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchResourceTeamAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceTeamServiceServer).SearchResourceTeamAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.ResourceTeamService/SearchResourceTeamAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceTeamServiceServer).SearchResourceTeamAgent(ctx, req.(*SearchResourceTeamAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceTeamService_ReadResourceTeamAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadResourceTeamAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceTeamServiceServer).ReadResourceTeamAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.ResourceTeamService/ReadResourceTeamAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceTeamServiceServer).ReadResourceTeamAgent(ctx, req.(*ReadResourceTeamAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceTeamService_UpdateResourceTeamAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateResourceTeamAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceTeamServiceServer).UpdateResourceTeamAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.ResourceTeamService/UpdateResourceTeamAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceTeamServiceServer).UpdateResourceTeamAgent(ctx, req.(*UpdateResourceTeamAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceTeamService_DeleteResourceTeamAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceTeamAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceTeamServiceServer).DeleteResourceTeamAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.ResourceTeamService/DeleteResourceTeamAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceTeamServiceServer).DeleteResourceTeamAgent(ctx, req.(*DeleteResourceTeamAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceTeamService_CreateResourceTeamSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceTeamSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceTeamServiceServer).CreateResourceTeamSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.ResourceTeamService/CreateResourceTeamSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceTeamServiceServer).CreateResourceTeamSkill(ctx, req.(*CreateResourceTeamSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceTeamService_SearchResourceTeamSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchResourceTeamSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceTeamServiceServer).SearchResourceTeamSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.ResourceTeamService/SearchResourceTeamSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceTeamServiceServer).SearchResourceTeamSkill(ctx, req.(*SearchResourceTeamSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceTeamService_ReadResourceTeamSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadResourceTeamSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceTeamServiceServer).ReadResourceTeamSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.ResourceTeamService/ReadResourceTeamSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceTeamServiceServer).ReadResourceTeamSkill(ctx, req.(*ReadResourceTeamSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceTeamService_UpdateResourceTeamSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateResourceTeamSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceTeamServiceServer).UpdateResourceTeamSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.ResourceTeamService/UpdateResourceTeamSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceTeamServiceServer).UpdateResourceTeamSkill(ctx, req.(*UpdateResourceTeamSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceTeamService_DeleteResourceTeamSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceTeamSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceTeamServiceServer).DeleteResourceTeamSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine.ResourceTeamService/DeleteResourceTeamSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceTeamServiceServer).DeleteResourceTeamSkill(ctx, req.(*DeleteResourceTeamSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceTeamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "engine.ResourceTeamService",
	HandlerType: (*ResourceTeamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateResourceTeamAgent",
			Handler:    _ResourceTeamService_CreateResourceTeamAgent_Handler,
		},
		{
			MethodName: "SearchResourceTeamAgent",
			Handler:    _ResourceTeamService_SearchResourceTeamAgent_Handler,
		},
		{
			MethodName: "ReadResourceTeamAgent",
			Handler:    _ResourceTeamService_ReadResourceTeamAgent_Handler,
		},
		{
			MethodName: "UpdateResourceTeamAgent",
			Handler:    _ResourceTeamService_UpdateResourceTeamAgent_Handler,
		},
		{
			MethodName: "DeleteResourceTeamAgent",
			Handler:    _ResourceTeamService_DeleteResourceTeamAgent_Handler,
		},
		{
			MethodName: "CreateResourceTeamSkill",
			Handler:    _ResourceTeamService_CreateResourceTeamSkill_Handler,
		},
		{
			MethodName: "SearchResourceTeamSkill",
			Handler:    _ResourceTeamService_SearchResourceTeamSkill_Handler,
		},
		{
			MethodName: "ReadResourceTeamSkill",
			Handler:    _ResourceTeamService_ReadResourceTeamSkill_Handler,
		},
		{
			MethodName: "UpdateResourceTeamSkill",
			Handler:    _ResourceTeamService_UpdateResourceTeamSkill_Handler,
		},
		{
			MethodName: "DeleteResourceTeamSkill",
			Handler:    _ResourceTeamService_DeleteResourceTeamSkill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resource_in_team.proto",
}
